/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods02.tables.daos;


import com.projectods.database.jooq.ods02.tables.AuditoriaOds02;
import com.projectods.database.jooq.ods02.tables.records.AuditoriaOds02Record;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * Auditoría de cambios en el sistema ODS02
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class AuditoriaOds02Dao extends DAOImpl<AuditoriaOds02Record, com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02, Integer> {

    /**
     * Create a new AuditoriaOds02Dao without any configuration
     */
    public AuditoriaOds02Dao() {
        super(AuditoriaOds02.AUDITORIA_ODS02, com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02.class);
    }

    /**
     * Create a new AuditoriaOds02Dao with an attached configuration
     */
    @Autowired
    public AuditoriaOds02Dao(Configuration configuration) {
        super(AuditoriaOds02.AUDITORIA_ODS02, com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02.class, configuration);
    }

    @Override
    public Integer getId(com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02 object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AuditoriaOds02.AUDITORIA_ODS02.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchById(Integer... values) {
        return fetch(AuditoriaOds02.AUDITORIA_ODS02.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02 fetchOneById(Integer value) {
        return fetchOne(AuditoriaOds02.AUDITORIA_ODS02.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchOptionalById(Integer value) {
        return fetchOptional(AuditoriaOds02.AUDITORIA_ODS02.ID, value);
    }

    /**
     * Fetch records that have <code>tabla_afectada BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchRangeOfTablaAfectada(String lowerInclusive, String upperInclusive) {
        return fetchRange(AuditoriaOds02.AUDITORIA_ODS02.TABLA_AFECTADA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tabla_afectada IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchByTablaAfectada(String... values) {
        return fetch(AuditoriaOds02.AUDITORIA_ODS02.TABLA_AFECTADA, values);
    }

    /**
     * Fetch records that have <code>registro_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchRangeOfRegistroId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AuditoriaOds02.AUDITORIA_ODS02.REGISTRO_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>registro_id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchByRegistroId(Integer... values) {
        return fetch(AuditoriaOds02.AUDITORIA_ODS02.REGISTRO_ID, values);
    }

    /**
     * Fetch records that have <code>accion BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchRangeOfAccion(String lowerInclusive, String upperInclusive) {
        return fetchRange(AuditoriaOds02.AUDITORIA_ODS02.ACCION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>accion IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchByAccion(String... values) {
        return fetch(AuditoriaOds02.AUDITORIA_ODS02.ACCION, values);
    }

    /**
     * Fetch records that have <code>usuario_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchRangeOfUsuarioId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AuditoriaOds02.AUDITORIA_ODS02.USUARIO_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>usuario_id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchByUsuarioId(Integer... values) {
        return fetch(AuditoriaOds02.AUDITORIA_ODS02.USUARIO_ID, values);
    }

    /**
     * Fetch records that have <code>valores_anteriores BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchRangeOfValoresAnteriores(String lowerInclusive, String upperInclusive) {
        return fetchRange(AuditoriaOds02.AUDITORIA_ODS02.VALORES_ANTERIORES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>valores_anteriores IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchByValoresAnteriores(String... values) {
        return fetch(AuditoriaOds02.AUDITORIA_ODS02.VALORES_ANTERIORES, values);
    }

    /**
     * Fetch records that have <code>valores_nuevos BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchRangeOfValoresNuevos(String lowerInclusive, String upperInclusive) {
        return fetchRange(AuditoriaOds02.AUDITORIA_ODS02.VALORES_NUEVOS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>valores_nuevos IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchByValoresNuevos(String... values) {
        return fetch(AuditoriaOds02.AUDITORIA_ODS02.VALORES_NUEVOS, values);
    }

    /**
     * Fetch records that have <code>fecha_cambio BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchRangeOfFechaCambio(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(AuditoriaOds02.AUDITORIA_ODS02.FECHA_CAMBIO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fecha_cambio IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchByFechaCambio(LocalDateTime... values) {
        return fetch(AuditoriaOds02.AUDITORIA_ODS02.FECHA_CAMBIO, values);
    }

    /**
     * Fetch records that have <code>ip_address BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchRangeOfIpAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(AuditoriaOds02.AUDITORIA_ODS02.IP_ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ip_address IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods02.tables.pojos.AuditoriaOds02> fetchByIpAddress(String... values) {
        return fetch(AuditoriaOds02.AUDITORIA_ODS02.IP_ADDRESS, values);
    }
}
