/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods02.tables.records;


import com.odsProject.odsProject.database.jooq.ods02.tables.VistaAdminDetalleIndicadores;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAdminDetalleIndicadoresRecord extends TableRecordImpl<VistaAdminDetalleIndicadoresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.proyecto_id</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setProyectoId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.proyecto_id</code>.
     */
    public Integer getProyectoId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.nombre_proyecto</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setNombreProyecto(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.nombre_proyecto</code>.
     */
    public String getNombreProyecto() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.indicador_master_id</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setIndicadorMasterId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.indicador_master_id</code>.
     */
    public Integer getIndicadorMasterId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.indicador_codigo</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setIndicadorCodigo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.indicador_codigo</code>.
     */
    public String getIndicadorCodigo() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.indicador_nombre</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setIndicadorNombre(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.indicador_nombre</code>.
     */
    public String getIndicadorNombre() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.formula_custom</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setFormulaCustom(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.formula_custom</code>.
     */
    public String getFormulaCustom() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.valor_actual</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setValorActual(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.valor_actual</code>.
     */
    public BigDecimal getValorActual() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>ods02.vista_admin_detalle_indicadores.meta_valor</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setMetaValor(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ods02.vista_admin_detalle_indicadores.meta_valor</code>.
     */
    public BigDecimal getMetaValor() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.meta_unidad</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setMetaUnidad(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.meta_unidad</code>.
     */
    public String getMetaUnidad() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.meta_nombre</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setMetaNombre(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.meta_nombre</code>.
     */
    public String getMetaNombre() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.estado_indicador</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setEstadoIndicador(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.estado_indicador</code>.
     */
    public String getEstadoIndicador() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.porcentaje_logro</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setPorcentajeLogro(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.porcentaje_logro</code>.
     */
    public BigDecimal getPorcentajeLogro() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for
     * <code>ods02.vista_admin_detalle_indicadores.ultima_actualizacion</code>.
     */
    public VistaAdminDetalleIndicadoresRecord setUltimaActualizacion(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods02.vista_admin_detalle_indicadores.ultima_actualizacion</code>.
     */
    public LocalDateTime getUltimaActualizacion() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaAdminDetalleIndicadoresRecord
     */
    public VistaAdminDetalleIndicadoresRecord() {
        super(VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES);
    }

    /**
     * Create a detached, initialised VistaAdminDetalleIndicadoresRecord
     */
    public VistaAdminDetalleIndicadoresRecord(Integer proyectoId, String nombreProyecto, Integer indicadorMasterId, String indicadorCodigo, String indicadorNombre, String formulaCustom, BigDecimal valorActual, BigDecimal metaValor, String metaUnidad, String metaNombre, String estadoIndicador, BigDecimal porcentajeLogro, LocalDateTime ultimaActualizacion) {
        super(VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES);

        setProyectoId(proyectoId);
        setNombreProyecto(nombreProyecto);
        setIndicadorMasterId(indicadorMasterId);
        setIndicadorCodigo(indicadorCodigo);
        setIndicadorNombre(indicadorNombre);
        setFormulaCustom(formulaCustom);
        setValorActual(valorActual);
        setMetaValor(metaValor);
        setMetaUnidad(metaUnidad);
        setMetaNombre(metaNombre);
        setEstadoIndicador(estadoIndicador);
        setPorcentajeLogro(porcentajeLogro);
        setUltimaActualizacion(ultimaActualizacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaAdminDetalleIndicadoresRecord
     */
    public VistaAdminDetalleIndicadoresRecord(com.odsProject.odsProject.database.jooq.ods02.tables.pojos.VistaAdminDetalleIndicadores value) {
        super(VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES);

        if (value != null) {
            setProyectoId(value.getProyectoId());
            setNombreProyecto(value.getNombreProyecto());
            setIndicadorMasterId(value.getIndicadorMasterId());
            setIndicadorCodigo(value.getIndicadorCodigo());
            setIndicadorNombre(value.getIndicadorNombre());
            setFormulaCustom(value.getFormulaCustom());
            setValorActual(value.getValorActual());
            setMetaValor(value.getMetaValor());
            setMetaUnidad(value.getMetaUnidad());
            setMetaNombre(value.getMetaNombre());
            setEstadoIndicador(value.getEstadoIndicador());
            setPorcentajeLogro(value.getPorcentajeLogro());
            setUltimaActualizacion(value.getUltimaActualizacion());
            resetChangedOnNotNull();
        }
    }
}
