/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods07.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAdminAuditoriaReciente implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String tablaAfectada;
    private final Integer registroId;
    private final String accion;
    private final String usuario;
    private final LocalDateTime fechaCambio;
    private final String ipAddress;

    public VistaAdminAuditoriaReciente(VistaAdminAuditoriaReciente value) {
        this.id = value.id;
        this.tablaAfectada = value.tablaAfectada;
        this.registroId = value.registroId;
        this.accion = value.accion;
        this.usuario = value.usuario;
        this.fechaCambio = value.fechaCambio;
        this.ipAddress = value.ipAddress;
    }

    public VistaAdminAuditoriaReciente(
        Integer id,
        String tablaAfectada,
        Integer registroId,
        String accion,
        String usuario,
        LocalDateTime fechaCambio,
        String ipAddress
    ) {
        this.id = id;
        this.tablaAfectada = tablaAfectada;
        this.registroId = registroId;
        this.accion = accion;
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
        this.ipAddress = ipAddress;
    }

    /**
     * Getter for <code>ods07.vista_admin_auditoria_reciente.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for
     * <code>ods07.vista_admin_auditoria_reciente.tabla_afectada</code>.
     */
    public String getTablaAfectada() {
        return this.tablaAfectada;
    }

    /**
     * Getter for <code>ods07.vista_admin_auditoria_reciente.registro_id</code>.
     */
    public Integer getRegistroId() {
        return this.registroId;
    }

    /**
     * Getter for <code>ods07.vista_admin_auditoria_reciente.accion</code>.
     */
    public String getAccion() {
        return this.accion;
    }

    /**
     * Getter for <code>ods07.vista_admin_auditoria_reciente.usuario</code>.
     */
    public String getUsuario() {
        return this.usuario;
    }

    /**
     * Getter for
     * <code>ods07.vista_admin_auditoria_reciente.fecha_cambio</code>.
     */
    public LocalDateTime getFechaCambio() {
        return this.fechaCambio;
    }

    /**
     * Getter for <code>ods07.vista_admin_auditoria_reciente.ip_address</code>.
     */
    public String getIpAddress() {
        return this.ipAddress;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VistaAdminAuditoriaReciente other = (VistaAdminAuditoriaReciente) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.tablaAfectada == null) {
            if (other.tablaAfectada != null)
                return false;
        }
        else if (!this.tablaAfectada.equals(other.tablaAfectada))
            return false;
        if (this.registroId == null) {
            if (other.registroId != null)
                return false;
        }
        else if (!this.registroId.equals(other.registroId))
            return false;
        if (this.accion == null) {
            if (other.accion != null)
                return false;
        }
        else if (!this.accion.equals(other.accion))
            return false;
        if (this.usuario == null) {
            if (other.usuario != null)
                return false;
        }
        else if (!this.usuario.equals(other.usuario))
            return false;
        if (this.fechaCambio == null) {
            if (other.fechaCambio != null)
                return false;
        }
        else if (!this.fechaCambio.equals(other.fechaCambio))
            return false;
        if (this.ipAddress == null) {
            if (other.ipAddress != null)
                return false;
        }
        else if (!this.ipAddress.equals(other.ipAddress))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.tablaAfectada == null) ? 0 : this.tablaAfectada.hashCode());
        result = prime * result + ((this.registroId == null) ? 0 : this.registroId.hashCode());
        result = prime * result + ((this.accion == null) ? 0 : this.accion.hashCode());
        result = prime * result + ((this.usuario == null) ? 0 : this.usuario.hashCode());
        result = prime * result + ((this.fechaCambio == null) ? 0 : this.fechaCambio.hashCode());
        result = prime * result + ((this.ipAddress == null) ? 0 : this.ipAddress.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VistaAdminAuditoriaReciente (");

        sb.append(id);
        sb.append(", ").append(tablaAfectada);
        sb.append(", ").append(registroId);
        sb.append(", ").append(accion);
        sb.append(", ").append(usuario);
        sb.append(", ").append(fechaCambio);
        sb.append(", ").append(ipAddress);

        sb.append(")");
        return sb.toString();
    }
}
