/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods10.tables.records;


import com.odsProject.odsProject.database.jooq.ods10.tables.MedicionesHistoricas;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicionesHistoricasRecord extends UpdatableRecordImpl<MedicionesHistoricasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ods10.mediciones_historicas.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ods10.mediciones_historicas.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>ods10.mediciones_historicas.proyecto_indicador_id</code>.
     */
    public void setProyectoIndicadorId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>ods10.mediciones_historicas.proyecto_indicador_id</code>.
     */
    public Integer getProyectoIndicadorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ods10.mediciones_historicas.valor_calculado</code>.
     */
    public void setValorCalculado(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>ods10.mediciones_historicas.valor_calculado</code>.
     */
    public BigDecimal getValorCalculado() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>ods10.mediciones_historicas.fecha_medicion</code>.
     */
    public void setFechaMedicion(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>ods10.mediciones_historicas.fecha_medicion</code>.
     */
    public LocalDate getFechaMedicion() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>ods10.mediciones_historicas.responsable</code>.
     */
    public void setResponsable(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ods10.mediciones_historicas.responsable</code>.
     */
    public String getResponsable() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ods10.mediciones_historicas.metodo_medicion</code>.
     */
    public void setMetodoMedicion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ods10.mediciones_historicas.metodo_medicion</code>.
     */
    public String getMetodoMedicion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ods10.mediciones_historicas.observaciones</code>.
     */
    public void setObservaciones(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ods10.mediciones_historicas.observaciones</code>.
     */
    public String getObservaciones() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ods10.mediciones_historicas.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>ods10.mediciones_historicas.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicionesHistoricasRecord
     */
    public MedicionesHistoricasRecord() {
        super(MedicionesHistoricas.MEDICIONES_HISTORICAS);
    }

    /**
     * Create a detached, initialised MedicionesHistoricasRecord
     */
    public MedicionesHistoricasRecord(Integer id, Integer proyectoIndicadorId, BigDecimal valorCalculado, LocalDate fechaMedicion, String responsable, String metodoMedicion, String observaciones, LocalDateTime createdAt) {
        super(MedicionesHistoricas.MEDICIONES_HISTORICAS);

        setId(id);
        setProyectoIndicadorId(proyectoIndicadorId);
        setValorCalculado(valorCalculado);
        setFechaMedicion(fechaMedicion);
        setResponsable(responsable);
        setMetodoMedicion(metodoMedicion);
        setObservaciones(observaciones);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MedicionesHistoricasRecord
     */
    public MedicionesHistoricasRecord(com.odsProject.odsProject.database.jooq.ods10.tables.pojos.MedicionesHistoricas value) {
        super(MedicionesHistoricas.MEDICIONES_HISTORICAS);

        if (value != null) {
            setId(value.getId());
            setProyectoIndicadorId(value.getProyectoIndicadorId());
            setValorCalculado(value.getValorCalculado());
            setFechaMedicion(value.getFechaMedicion());
            setResponsable(value.getResponsable());
            setMetodoMedicion(value.getMetodoMedicion());
            setObservaciones(value.getObservaciones());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
