/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods_login;


import com.projectods.database.jooq.ods_login.tables.IntentosLogin;
import com.projectods.database.jooq.ods_login.tables.Permisos;
import com.projectods.database.jooq.ods_login.tables.RecoveryTokens;
import com.projectods.database.jooq.ods_login.tables.SeguridadConfig;
import com.projectods.database.jooq.ods_login.tables.Sesiones;
import com.projectods.database.jooq.ods_login.tables.Usuarios;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in ods_login.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SESIONES_IDX_ACTIVE = Internal.createIndex(DSL.name("idx_active"), Sesiones.SESIONES, new OrderField[] { Sesiones.SESIONES.IS_ACTIVE }, false);
    public static final Index USUARIOS_IDX_ACTIVE = Internal.createIndex(DSL.name("idx_active"), Usuarios.USUARIOS, new OrderField[] { Usuarios.USUARIOS.IS_ACTIVE }, false);
    public static final Index USUARIOS_IDX_EMAIL = Internal.createIndex(DSL.name("idx_email"), Usuarios.USUARIOS, new OrderField[] { Usuarios.USUARIOS.EMAIL }, false);
    public static final Index RECOVERY_TOKENS_IDX_EXPIRES = Internal.createIndex(DSL.name("idx_expires"), RecoveryTokens.RECOVERY_TOKENS, new OrderField[] { RecoveryTokens.RECOVERY_TOKENS.EXPIRES_AT }, false);
    public static final Index SESIONES_IDX_EXPIRES = Internal.createIndex(DSL.name("idx_expires"), Sesiones.SESIONES, new OrderField[] { Sesiones.SESIONES.EXPIRES_AT }, false);
    public static final Index INTENTOS_LOGIN_IDX_IP_FECHA = Internal.createIndex(DSL.name("idx_ip_fecha"), IntentosLogin.INTENTOS_LOGIN, new OrderField[] { IntentosLogin.INTENTOS_LOGIN.IP_ADDRESS, IntentosLogin.INTENTOS_LOGIN.CREATED_AT }, false);
    public static final Index SEGURIDAD_CONFIG_IDX_KEY = Internal.createIndex(DSL.name("idx_key"), SeguridadConfig.SEGURIDAD_CONFIG, new OrderField[] { SeguridadConfig.SEGURIDAD_CONFIG.CONFIG_KEY }, false);
    public static final Index PERMISOS_IDX_RESOURCE = Internal.createIndex(DSL.name("idx_resource"), Permisos.PERMISOS, new OrderField[] { Permisos.PERMISOS.RESOURCE }, false);
    public static final Index PERMISOS_IDX_ROLE = Internal.createIndex(DSL.name("idx_role"), Permisos.PERMISOS, new OrderField[] { Permisos.PERMISOS.ROLE }, false);
    public static final Index USUARIOS_IDX_ROLE = Internal.createIndex(DSL.name("idx_role"), Usuarios.USUARIOS, new OrderField[] { Usuarios.USUARIOS.ROLE }, false);
    public static final Index INTENTOS_LOGIN_IDX_SUCCESS = Internal.createIndex(DSL.name("idx_success"), IntentosLogin.INTENTOS_LOGIN, new OrderField[] { IntentosLogin.INTENTOS_LOGIN.SUCCESS }, false);
    public static final Index RECOVERY_TOKENS_IDX_TOKEN = Internal.createIndex(DSL.name("idx_token"), RecoveryTokens.RECOVERY_TOKENS, new OrderField[] { RecoveryTokens.RECOVERY_TOKENS.TOKEN }, false);
    public static final Index SESIONES_IDX_TOKEN = Internal.createIndex(DSL.name("idx_token"), Sesiones.SESIONES, new OrderField[] { Sesiones.SESIONES.SESSION_TOKEN }, false);
    public static final Index USUARIOS_IDX_USERNAME = Internal.createIndex(DSL.name("idx_username"), Usuarios.USUARIOS, new OrderField[] { Usuarios.USUARIOS.USERNAME }, false);
    public static final Index INTENTOS_LOGIN_IDX_USERNAME_FECHA = Internal.createIndex(DSL.name("idx_username_fecha"), IntentosLogin.INTENTOS_LOGIN, new OrderField[] { IntentosLogin.INTENTOS_LOGIN.USERNAME, IntentosLogin.INTENTOS_LOGIN.CREATED_AT }, false);
    public static final Index RECOVERY_TOKENS_IDX_USUARIO = Internal.createIndex(DSL.name("idx_usuario"), RecoveryTokens.RECOVERY_TOKENS, new OrderField[] { RecoveryTokens.RECOVERY_TOKENS.USUARIO_ID }, false);
    public static final Index SESIONES_IDX_USUARIO = Internal.createIndex(DSL.name("idx_usuario"), Sesiones.SESIONES, new OrderField[] { Sesiones.SESIONES.USUARIO_ID }, false);
}
