/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods_login;


import com.projectods.database.jooq.ods_login.routines.SpCerrarSesion;
import com.projectods.database.jooq.ods_login.routines.SpCrearSesion;
import com.projectods.database.jooq.ods_login.routines.SpValidarLogin;
import com.projectods.database.jooq.ods_login.routines.SpValidarSesion;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in ods_login.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>ods_login.sp_cerrar_sesion</code>
     */
    public static SpCerrarSesion spCerrarSesion(
          Configuration configuration
        , String pSessionToken
    ) {
        SpCerrarSesion p = new SpCerrarSesion();
        p.setPSessionToken(pSessionToken);

        p.execute(configuration);
        return p;
    }

    /**
     * Call <code>ods_login.sp_crear_sesion</code>
     */
    public static SpCrearSesion spCrearSesion(
          Configuration configuration
        , Integer pUsuarioId
        , String pIpAddress
        , String pUserAgent
    ) {
        SpCrearSesion p = new SpCrearSesion();
        p.setPUsuarioId(pUsuarioId);
        p.setPIpAddress(pIpAddress);
        p.setPUserAgent(pUserAgent);

        p.execute(configuration);
        return p;
    }

    /**
     * Call <code>ods_login.sp_validar_login</code>
     */
    public static SpValidarLogin spValidarLogin(
          Configuration configuration
        , String pUsername
        , String pPassword
        , String pIpAddress
        , String pUserAgent
    ) {
        SpValidarLogin p = new SpValidarLogin();
        p.setPUsername(pUsername);
        p.setPPassword(pPassword);
        p.setPIpAddress(pIpAddress);
        p.setPUserAgent(pUserAgent);

        p.execute(configuration);
        return p;
    }

    /**
     * Call <code>ods_login.sp_validar_sesion</code>
     */
    public static SpValidarSesion spValidarSesion(
          Configuration configuration
        , String pSessionToken
        , String pIpAddress
    ) {
        SpValidarSesion p = new SpValidarSesion();
        p.setPSessionToken(pSessionToken);
        p.setPIpAddress(pIpAddress);

        p.execute(configuration);
        return p;
    }
}
