/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods09;


import com.projectods.database.jooq.ods09.tables.AuditoriaOds09;
import com.projectods.database.jooq.ods09.tables.Indicadores;
import com.projectods.database.jooq.ods09.tables.MedicionesHistoricas;
import com.projectods.database.jooq.ods09.tables.MetasProyecto;
import com.projectods.database.jooq.ods09.tables.Proyectos;
import com.projectods.database.jooq.ods09.tables.VistaAdminAuditoriaReciente;
import com.projectods.database.jooq.ods09.tables.VistaAdminDetalleIndicadores;
import com.projectods.database.jooq.ods09.tables.VistaAdminEstadisticasGenerales;
import com.projectods.database.jooq.ods09.tables.VistaAdminResumenGeneral;


/**
 * Convenience access to all tables in ods09.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Auditoría de cambios en el sistema ODS09
     */
    public static final AuditoriaOds09 AUDITORIA_ODS09 = AuditoriaOds09.AUDITORIA_ODS09;

    /**
     * Indicadores medidos por cada proyecto ODS09
     */
    public static final Indicadores INDICADORES = Indicadores.INDICADORES;

    /**
     * Historial de mediciones de indicadores ODS09
     */
    public static final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * Metas específicas establecidas por cada proyecto ODS09
     */
    public static final MetasProyecto METAS_PROYECTO = MetasProyecto.METAS_PROYECTO;

    /**
     * Proyectos ODS09 creados por usuarios
     */
    public static final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * VIEW
     */
    public static final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * VIEW
     */
    public static final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * VIEW
     */
    public static final VistaAdminEstadisticasGenerales VISTA_ADMIN_ESTADISTICAS_GENERALES = VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES;

    /**
     * VIEW
     */
    public static final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;
}
