/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods14;


import com.projectods.database.jooq.ods14.tables.AuditoriaOds14;
import com.projectods.database.jooq.ods14.tables.Indicadores;
import com.projectods.database.jooq.ods14.tables.MedicionesHistoricas;
import com.projectods.database.jooq.ods14.tables.MetasProyecto;
import com.projectods.database.jooq.ods14.tables.Proyectos;
import com.projectods.database.jooq.ods14.tables.VistaAdminAuditoriaReciente;
import com.projectods.database.jooq.ods14.tables.VistaAdminDetalleIndicadores;
import com.projectods.database.jooq.ods14.tables.VistaAdminEstadisticasGenerales;
import com.projectods.database.jooq.ods14.tables.VistaAdminResumenGeneral;


/**
 * Convenience access to all tables in ods14.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Auditoría de cambios en el sistema ODS14
     */
    public static final AuditoriaOds14 AUDITORIA_ODS14 = AuditoriaOds14.AUDITORIA_ODS14;

    /**
     * Indicadores medidos por cada proyecto ODS14
     */
    public static final Indicadores INDICADORES = Indicadores.INDICADORES;

    /**
     * Historial de mediciones de indicadores ODS14
     */
    public static final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * Metas específicas establecidas por cada proyecto ODS14
     */
    public static final MetasProyecto METAS_PROYECTO = MetasProyecto.METAS_PROYECTO;

    /**
     * Proyectos ODS14 creados por usuarios
     */
    public static final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * VIEW
     */
    public static final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * VIEW
     */
    public static final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * VIEW
     */
    public static final VistaAdminEstadisticasGenerales VISTA_ADMIN_ESTADISTICAS_GENERALES = VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES;

    /**
     * VIEW
     */
    public static final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;
}
