/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods13.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * Metas específicas establecidas por cada proyecto ODS13
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MetasProyecto implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Integer proyectoId;
    private final String metaCodigo;
    private final String metaDescripcion;
    private final BigDecimal valorMeta;
    private final String unidadMedida;
    private final LocalDate fechaLimite;
    private final LocalDateTime createdAt;

    public MetasProyecto(MetasProyecto value) {
        this.id = value.id;
        this.proyectoId = value.proyectoId;
        this.metaCodigo = value.metaCodigo;
        this.metaDescripcion = value.metaDescripcion;
        this.valorMeta = value.valorMeta;
        this.unidadMedida = value.unidadMedida;
        this.fechaLimite = value.fechaLimite;
        this.createdAt = value.createdAt;
    }

    public MetasProyecto(
        Integer id,
        Integer proyectoId,
        String metaCodigo,
        String metaDescripcion,
        BigDecimal valorMeta,
        String unidadMedida,
        LocalDate fechaLimite,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.proyectoId = proyectoId;
        this.metaCodigo = metaCodigo;
        this.metaDescripcion = metaDescripcion;
        this.valorMeta = valorMeta;
        this.unidadMedida = unidadMedida;
        this.fechaLimite = fechaLimite;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>ods13.metas_proyecto.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>ods13.metas_proyecto.proyecto_id</code>.
     */
    public Integer getProyectoId() {
        return this.proyectoId;
    }

    /**
     * Getter for <code>ods13.metas_proyecto.meta_codigo</code>.
     */
    public String getMetaCodigo() {
        return this.metaCodigo;
    }

    /**
     * Getter for <code>ods13.metas_proyecto.meta_descripcion</code>.
     */
    public String getMetaDescripcion() {
        return this.metaDescripcion;
    }

    /**
     * Getter for <code>ods13.metas_proyecto.valor_meta</code>.
     */
    public BigDecimal getValorMeta() {
        return this.valorMeta;
    }

    /**
     * Getter for <code>ods13.metas_proyecto.unidad_medida</code>.
     */
    public String getUnidadMedida() {
        return this.unidadMedida;
    }

    /**
     * Getter for <code>ods13.metas_proyecto.fecha_limite</code>.
     */
    public LocalDate getFechaLimite() {
        return this.fechaLimite;
    }

    /**
     * Getter for <code>ods13.metas_proyecto.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MetasProyecto other = (MetasProyecto) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.proyectoId == null) {
            if (other.proyectoId != null)
                return false;
        }
        else if (!this.proyectoId.equals(other.proyectoId))
            return false;
        if (this.metaCodigo == null) {
            if (other.metaCodigo != null)
                return false;
        }
        else if (!this.metaCodigo.equals(other.metaCodigo))
            return false;
        if (this.metaDescripcion == null) {
            if (other.metaDescripcion != null)
                return false;
        }
        else if (!this.metaDescripcion.equals(other.metaDescripcion))
            return false;
        if (this.valorMeta == null) {
            if (other.valorMeta != null)
                return false;
        }
        else if (!this.valorMeta.equals(other.valorMeta))
            return false;
        if (this.unidadMedida == null) {
            if (other.unidadMedida != null)
                return false;
        }
        else if (!this.unidadMedida.equals(other.unidadMedida))
            return false;
        if (this.fechaLimite == null) {
            if (other.fechaLimite != null)
                return false;
        }
        else if (!this.fechaLimite.equals(other.fechaLimite))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.proyectoId == null) ? 0 : this.proyectoId.hashCode());
        result = prime * result + ((this.metaCodigo == null) ? 0 : this.metaCodigo.hashCode());
        result = prime * result + ((this.metaDescripcion == null) ? 0 : this.metaDescripcion.hashCode());
        result = prime * result + ((this.valorMeta == null) ? 0 : this.valorMeta.hashCode());
        result = prime * result + ((this.unidadMedida == null) ? 0 : this.unidadMedida.hashCode());
        result = prime * result + ((this.fechaLimite == null) ? 0 : this.fechaLimite.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MetasProyecto (");

        sb.append(id);
        sb.append(", ").append(proyectoId);
        sb.append(", ").append(metaCodigo);
        sb.append(", ").append(metaDescripcion);
        sb.append(", ").append(valorMeta);
        sb.append(", ").append(unidadMedida);
        sb.append(", ").append(fechaLimite);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
