/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods_login.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * Tokens para recuperación de contraseña
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RecoveryTokens implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer usuarioId;
    private String token;
    private String email;
    private LocalDateTime createdAt;
    private LocalDateTime expiresAt;
    private Byte used;
    private String ipAddress;

    public RecoveryTokens() {}

    public RecoveryTokens(RecoveryTokens value) {
        this.id = value.id;
        this.usuarioId = value.usuarioId;
        this.token = value.token;
        this.email = value.email;
        this.createdAt = value.createdAt;
        this.expiresAt = value.expiresAt;
        this.used = value.used;
        this.ipAddress = value.ipAddress;
    }

    public RecoveryTokens(
        Integer id,
        Integer usuarioId,
        String token,
        String email,
        LocalDateTime createdAt,
        LocalDateTime expiresAt,
        Byte used,
        String ipAddress
    ) {
        this.id = id;
        this.usuarioId = usuarioId;
        this.token = token;
        this.email = email;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.used = used;
        this.ipAddress = ipAddress;
    }

    /**
     * Getter for <code>ods_login.recovery_tokens.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ods_login.recovery_tokens.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>ods_login.recovery_tokens.usuario_id</code>.
     */
    @NotNull
    public Integer getUsuarioId() {
        return this.usuarioId;
    }

    /**
     * Setter for <code>ods_login.recovery_tokens.usuario_id</code>.
     */
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }

    /**
     * Getter for <code>ods_login.recovery_tokens.token</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getToken() {
        return this.token;
    }

    /**
     * Setter for <code>ods_login.recovery_tokens.token</code>.
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * Getter for <code>ods_login.recovery_tokens.email</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>ods_login.recovery_tokens.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>ods_login.recovery_tokens.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>ods_login.recovery_tokens.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>ods_login.recovery_tokens.expires_at</code>.
     */
    @NotNull
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Setter for <code>ods_login.recovery_tokens.expires_at</code>.
     */
    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * Getter for <code>ods_login.recovery_tokens.used</code>.
     */
    public Byte getUsed() {
        return this.used;
    }

    /**
     * Setter for <code>ods_login.recovery_tokens.used</code>.
     */
    public void setUsed(Byte used) {
        this.used = used;
    }

    /**
     * Getter for <code>ods_login.recovery_tokens.ip_address</code>.
     */
    @Size(max = 45)
    public String getIpAddress() {
        return this.ipAddress;
    }

    /**
     * Setter for <code>ods_login.recovery_tokens.ip_address</code>.
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RecoveryTokens other = (RecoveryTokens) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.usuarioId == null) {
            if (other.usuarioId != null)
                return false;
        }
        else if (!this.usuarioId.equals(other.usuarioId))
            return false;
        if (this.token == null) {
            if (other.token != null)
                return false;
        }
        else if (!this.token.equals(other.token))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.expiresAt == null) {
            if (other.expiresAt != null)
                return false;
        }
        else if (!this.expiresAt.equals(other.expiresAt))
            return false;
        if (this.used == null) {
            if (other.used != null)
                return false;
        }
        else if (!this.used.equals(other.used))
            return false;
        if (this.ipAddress == null) {
            if (other.ipAddress != null)
                return false;
        }
        else if (!this.ipAddress.equals(other.ipAddress))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.usuarioId == null) ? 0 : this.usuarioId.hashCode());
        result = prime * result + ((this.token == null) ? 0 : this.token.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.expiresAt == null) ? 0 : this.expiresAt.hashCode());
        result = prime * result + ((this.used == null) ? 0 : this.used.hashCode());
        result = prime * result + ((this.ipAddress == null) ? 0 : this.ipAddress.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RecoveryTokens (");

        sb.append(id);
        sb.append(", ").append(usuarioId);
        sb.append(", ").append(token);
        sb.append(", ").append(email);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(used);
        sb.append(", ").append(ipAddress);

        sb.append(")");
        return sb.toString();
    }
}
