/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods_login.tables.pojos;


import com.projectods.database.jooq.ods_login.enums.VistaAdminSesionesActivasRole;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAdminSesionesActivas implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String sessionToken;
    private String username;
    private String fullName;
    private VistaAdminSesionesActivasRole role;
    private String ipAddress;
    private String userAgent;
    private LocalDateTime createdAt;
    private LocalDateTime expiresAt;
    private Long segundosRestantes;
    private String estadoSesion;

    public VistaAdminSesionesActivas() {}

    public VistaAdminSesionesActivas(VistaAdminSesionesActivas value) {
        this.id = value.id;
        this.sessionToken = value.sessionToken;
        this.username = value.username;
        this.fullName = value.fullName;
        this.role = value.role;
        this.ipAddress = value.ipAddress;
        this.userAgent = value.userAgent;
        this.createdAt = value.createdAt;
        this.expiresAt = value.expiresAt;
        this.segundosRestantes = value.segundosRestantes;
        this.estadoSesion = value.estadoSesion;
    }

    public VistaAdminSesionesActivas(
        Integer id,
        String sessionToken,
        String username,
        String fullName,
        VistaAdminSesionesActivasRole role,
        String ipAddress,
        String userAgent,
        LocalDateTime createdAt,
        LocalDateTime expiresAt,
        Long segundosRestantes,
        String estadoSesion
    ) {
        this.id = id;
        this.sessionToken = sessionToken;
        this.username = username;
        this.fullName = fullName;
        this.role = role;
        this.ipAddress = ipAddress;
        this.userAgent = userAgent;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.segundosRestantes = segundosRestantes;
        this.estadoSesion = estadoSesion;
    }

    /**
     * Getter for <code>ods_login.vista_admin_sesiones_activas.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ods_login.vista_admin_sesiones_activas.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_sesiones_activas.session_token</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getSessionToken() {
        return this.sessionToken;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_sesiones_activas.session_token</code>.
     */
    public void setSessionToken(String sessionToken) {
        this.sessionToken = sessionToken;
    }

    /**
     * Getter for <code>ods_login.vista_admin_sesiones_activas.username</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>ods_login.vista_admin_sesiones_activas.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>ods_login.vista_admin_sesiones_activas.full_name</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>ods_login.vista_admin_sesiones_activas.full_name</code>.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for <code>ods_login.vista_admin_sesiones_activas.role</code>.
     */
    public VistaAdminSesionesActivasRole getRole() {
        return this.role;
    }

    /**
     * Setter for <code>ods_login.vista_admin_sesiones_activas.role</code>.
     */
    public void setRole(VistaAdminSesionesActivasRole role) {
        this.role = role;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_sesiones_activas.ip_address</code>.
     */
    @Size(max = 45)
    public String getIpAddress() {
        return this.ipAddress;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_sesiones_activas.ip_address</code>.
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_sesiones_activas.user_agent</code>.
     */
    @Size(max = 65535)
    public String getUserAgent() {
        return this.userAgent;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_sesiones_activas.user_agent</code>.
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_sesiones_activas.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_sesiones_activas.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_sesiones_activas.expires_at</code>.
     */
    @NotNull
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_sesiones_activas.expires_at</code>.
     */
    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_sesiones_activas.segundos_restantes</code>.
     */
    public Long getSegundosRestantes() {
        return this.segundosRestantes;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_sesiones_activas.segundos_restantes</code>.
     */
    public void setSegundosRestantes(Long segundosRestantes) {
        this.segundosRestantes = segundosRestantes;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_sesiones_activas.estado_sesion</code>.
     */
    @Size(max = 11)
    public String getEstadoSesion() {
        return this.estadoSesion;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_sesiones_activas.estado_sesion</code>.
     */
    public void setEstadoSesion(String estadoSesion) {
        this.estadoSesion = estadoSesion;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VistaAdminSesionesActivas other = (VistaAdminSesionesActivas) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.sessionToken == null) {
            if (other.sessionToken != null)
                return false;
        }
        else if (!this.sessionToken.equals(other.sessionToken))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        if (this.ipAddress == null) {
            if (other.ipAddress != null)
                return false;
        }
        else if (!this.ipAddress.equals(other.ipAddress))
            return false;
        if (this.userAgent == null) {
            if (other.userAgent != null)
                return false;
        }
        else if (!this.userAgent.equals(other.userAgent))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.expiresAt == null) {
            if (other.expiresAt != null)
                return false;
        }
        else if (!this.expiresAt.equals(other.expiresAt))
            return false;
        if (this.segundosRestantes == null) {
            if (other.segundosRestantes != null)
                return false;
        }
        else if (!this.segundosRestantes.equals(other.segundosRestantes))
            return false;
        if (this.estadoSesion == null) {
            if (other.estadoSesion != null)
                return false;
        }
        else if (!this.estadoSesion.equals(other.estadoSesion))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.sessionToken == null) ? 0 : this.sessionToken.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        result = prime * result + ((this.ipAddress == null) ? 0 : this.ipAddress.hashCode());
        result = prime * result + ((this.userAgent == null) ? 0 : this.userAgent.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.expiresAt == null) ? 0 : this.expiresAt.hashCode());
        result = prime * result + ((this.segundosRestantes == null) ? 0 : this.segundosRestantes.hashCode());
        result = prime * result + ((this.estadoSesion == null) ? 0 : this.estadoSesion.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VistaAdminSesionesActivas (");

        sb.append(id);
        sb.append(", ").append(sessionToken);
        sb.append(", ").append(username);
        sb.append(", ").append(fullName);
        sb.append(", ").append(role);
        sb.append(", ").append(ipAddress);
        sb.append(", ").append(userAgent);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(segundosRestantes);
        sb.append(", ").append(estadoSesion);

        sb.append(")");
        return sb.toString();
    }
}
