/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables;


import com.odsProject.odsProject.database.jooq.ods_login.Indexes;
import com.odsProject.odsProject.database.jooq.ods_login.Keys;
import com.odsProject.odsProject.database.jooq.ods_login.OdsLogin;
import com.odsProject.odsProject.database.jooq.ods_login.tables.records.IndicadorMasterRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * Catálogo maestro de todos los indicadores oficiales con sus fórmulas
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndicadorMaster extends TableImpl<IndicadorMasterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods_login.indicador_master</code>
     */
    public static final IndicadorMaster INDICADOR_MASTER = new IndicadorMaster();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndicadorMasterRecord> getRecordType() {
        return IndicadorMasterRecord.class;
    }

    /**
     * The column <code>ods_login.indicador_master.id</code>.
     */
    public final TableField<IndicadorMasterRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ods_login.indicador_master.ods_id</code>.
     */
    public final TableField<IndicadorMasterRecord, UByte> ODS_ID = createField(DSL.name("ods_id"), SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ods_login.indicador_master.codigo</code>.
     */
    public final TableField<IndicadorMasterRecord, String> CODIGO = createField(DSL.name("codigo"), SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>ods_login.indicador_master.nombre</code>.
     */
    public final TableField<IndicadorMasterRecord, String> NOMBRE = createField(DSL.name("nombre"), SQLDataType.CLOB(65535).nullable(false), this, "");

    /**
     * The column <code>ods_login.indicador_master.descripcion</code>.
     */
    public final TableField<IndicadorMasterRecord, String> DESCRIPCION = createField(DSL.name("descripcion"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods_login.indicador_master.formula_default</code>.
     */
    public final TableField<IndicadorMasterRecord, String> FORMULA_DEFAULT = createField(DSL.name("formula_default"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods_login.indicador_master.unidad_medida_default</code>.
     */
    public final TableField<IndicadorMasterRecord, String> UNIDAD_MEDIDA_DEFAULT = createField(DSL.name("unidad_medida_default"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ods_login.indicador_master.created_at</code>.
     */
    public final TableField<IndicadorMasterRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    private IndicadorMaster(Name alias, Table<IndicadorMasterRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IndicadorMaster(Name alias, Table<IndicadorMasterRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Catálogo maestro de todos los indicadores oficiales con sus fórmulas"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ods_login.indicador_master</code> table reference
     */
    public IndicadorMaster(String alias) {
        this(DSL.name(alias), INDICADOR_MASTER);
    }

    /**
     * Create an aliased <code>ods_login.indicador_master</code> table reference
     */
    public IndicadorMaster(Name alias) {
        this(alias, INDICADOR_MASTER);
    }

    /**
     * Create a <code>ods_login.indicador_master</code> table reference
     */
    public IndicadorMaster() {
        this(DSL.name("indicador_master"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OdsLogin.ODS_LOGIN;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.INDICADOR_MASTER_ODS_ID);
    }

    @Override
    public Identity<IndicadorMasterRecord, Integer> getIdentity() {
        return (Identity<IndicadorMasterRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<IndicadorMasterRecord> getPrimaryKey() {
        return Keys.KEY_INDICADOR_MASTER_PRIMARY;
    }

    @Override
    public List<UniqueKey<IndicadorMasterRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_INDICADOR_MASTER_CODIGO);
    }

    @Override
    public List<ForeignKey<IndicadorMasterRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INDICADOR_MASTER_IBFK_1);
    }

    @Override
    public IndicadorMaster as(String alias) {
        return new IndicadorMaster(DSL.name(alias), this);
    }

    @Override
    public IndicadorMaster as(Name alias) {
        return new IndicadorMaster(alias, this);
    }

    @Override
    public IndicadorMaster as(Table<?> alias) {
        return new IndicadorMaster(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndicadorMaster rename(String name) {
        return new IndicadorMaster(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndicadorMaster rename(Name name) {
        return new IndicadorMaster(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndicadorMaster rename(Table<?> name) {
        return new IndicadorMaster(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndicadorMaster where(Condition condition) {
        return new IndicadorMaster(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndicadorMaster where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndicadorMaster where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndicadorMaster where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndicadorMaster where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndicadorMaster where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndicadorMaster where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndicadorMaster where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndicadorMaster whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndicadorMaster whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
