/*
 * This file is generated by jOOQ.
 */
package odsProject.database.jooq.ods_login.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import odsProject.database.jooq.ods_login.Indexes;
import odsProject.database.jooq.ods_login.Keys;
import odsProject.database.jooq.ods_login.OdsLogin;
import odsProject.database.jooq.ods_login.tables.records.IntentosLoginRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Registro de intentos de login para seguridad
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IntentosLogin extends TableImpl<IntentosLoginRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods_login.intentos_login</code>
     */
    public static final IntentosLogin INTENTOS_LOGIN = new IntentosLogin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IntentosLoginRecord> getRecordType() {
        return IntentosLoginRecord.class;
    }

    /**
     * The column <code>ods_login.intentos_login.id</code>.
     */
    public final TableField<IntentosLoginRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ods_login.intentos_login.username</code>.
     */
    public final TableField<IntentosLoginRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>ods_login.intentos_login.ip_address</code>.
     */
    public final TableField<IntentosLoginRecord, String> IP_ADDRESS = createField(DSL.name("ip_address"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ods_login.intentos_login.user_agent</code>.
     */
    public final TableField<IntentosLoginRecord, String> USER_AGENT = createField(DSL.name("user_agent"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods_login.intentos_login.success</code>.
     */
    public final TableField<IntentosLoginRecord, Byte> SUCCESS = createField(DSL.name("success"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>ods_login.intentos_login.failure_reason</code>.
     */
    public final TableField<IntentosLoginRecord, String> FAILURE_REASON = createField(DSL.name("failure_reason"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ods_login.intentos_login.created_at</code>.
     */
    public final TableField<IntentosLoginRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    private IntentosLogin(Name alias, Table<IntentosLoginRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IntentosLogin(Name alias, Table<IntentosLoginRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Registro de intentos de login para seguridad"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ods_login.intentos_login</code> table reference
     */
    public IntentosLogin(String alias) {
        this(DSL.name(alias), INTENTOS_LOGIN);
    }

    /**
     * Create an aliased <code>ods_login.intentos_login</code> table reference
     */
    public IntentosLogin(Name alias) {
        this(alias, INTENTOS_LOGIN);
    }

    /**
     * Create a <code>ods_login.intentos_login</code> table reference
     */
    public IntentosLogin() {
        this(DSL.name("intentos_login"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OdsLogin.ODS_LOGIN;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.INTENTOS_LOGIN_IDX_IP_FECHA, Indexes.INTENTOS_LOGIN_IDX_SUCCESS, Indexes.INTENTOS_LOGIN_IDX_USERNAME_FECHA);
    }

    @Override
    public Identity<IntentosLoginRecord, Integer> getIdentity() {
        return (Identity<IntentosLoginRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<IntentosLoginRecord> getPrimaryKey() {
        return Keys.KEY_INTENTOS_LOGIN_PRIMARY;
    }

    @Override
    public IntentosLogin as(String alias) {
        return new IntentosLogin(DSL.name(alias), this);
    }

    @Override
    public IntentosLogin as(Name alias) {
        return new IntentosLogin(alias, this);
    }

    @Override
    public IntentosLogin as(Table<?> alias) {
        return new IntentosLogin(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IntentosLogin rename(String name) {
        return new IntentosLogin(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IntentosLogin rename(Name name) {
        return new IntentosLogin(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IntentosLogin rename(Table<?> name) {
        return new IntentosLogin(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IntentosLogin where(Condition condition) {
        return new IntentosLogin(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IntentosLogin where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IntentosLogin where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IntentosLogin where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IntentosLogin where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IntentosLogin where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IntentosLogin where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IntentosLogin where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IntentosLogin whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IntentosLogin whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
