/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables;


import com.odsProject.odsProject.database.jooq.ods_login.Keys;
import com.odsProject.odsProject.database.jooq.ods_login.OdsLogin;
import com.odsProject.odsProject.database.jooq.ods_login.tables.records.SodsiRegionesMideplanRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SodsiRegionesMideplan extends TableImpl<SodsiRegionesMideplanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods_login.sodsi_regiones_mideplan</code>
     */
    public static final SodsiRegionesMideplan SODSI_REGIONES_MIDEPLAN = new SodsiRegionesMideplan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SodsiRegionesMideplanRecord> getRecordType() {
        return SodsiRegionesMideplanRecord.class;
    }

    /**
     * The column <code>ods_login.sodsi_regiones_mideplan.id</code>.
     */
    public final TableField<SodsiRegionesMideplanRecord, UByte> ID = createField(DSL.name("id"), SQLDataType.TINYINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>ods_login.sodsi_regiones_mideplan.nombre</code>.
     */
    public final TableField<SodsiRegionesMideplanRecord, String> NOMBRE = createField(DSL.name("nombre"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>ods_login.sodsi_regiones_mideplan.codigo</code>.
     */
    public final TableField<SodsiRegionesMideplanRecord, String> CODIGO = createField(DSL.name("codigo"), SQLDataType.VARCHAR(30).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ods_login.sodsi_regiones_mideplan.es_na</code>.
     */
    public final TableField<SodsiRegionesMideplanRecord, Byte> ES_NA = createField(DSL.name("es_na"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>ods_login.sodsi_regiones_mideplan.orden</code>.
     */
    public final TableField<SodsiRegionesMideplanRecord, UByte> ORDEN = createField(DSL.name("orden"), SQLDataType.TINYINTUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINTUNSIGNED)), this, "");

    private SodsiRegionesMideplan(Name alias, Table<SodsiRegionesMideplanRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SodsiRegionesMideplan(Name alias, Table<SodsiRegionesMideplanRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ods_login.sodsi_regiones_mideplan</code> table
     * reference
     */
    public SodsiRegionesMideplan(String alias) {
        this(DSL.name(alias), SODSI_REGIONES_MIDEPLAN);
    }

    /**
     * Create an aliased <code>ods_login.sodsi_regiones_mideplan</code> table
     * reference
     */
    public SodsiRegionesMideplan(Name alias) {
        this(alias, SODSI_REGIONES_MIDEPLAN);
    }

    /**
     * Create a <code>ods_login.sodsi_regiones_mideplan</code> table reference
     */
    public SodsiRegionesMideplan() {
        this(DSL.name("sodsi_regiones_mideplan"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OdsLogin.ODS_LOGIN;
    }

    @Override
    public Identity<SodsiRegionesMideplanRecord, UByte> getIdentity() {
        return (Identity<SodsiRegionesMideplanRecord, UByte>) super.getIdentity();
    }

    @Override
    public UniqueKey<SodsiRegionesMideplanRecord> getPrimaryKey() {
        return Keys.KEY_SODSI_REGIONES_MIDEPLAN_PRIMARY;
    }

    @Override
    public List<UniqueKey<SodsiRegionesMideplanRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SODSI_REGIONES_MIDEPLAN_NOMBRE);
    }

    @Override
    public SodsiRegionesMideplan as(String alias) {
        return new SodsiRegionesMideplan(DSL.name(alias), this);
    }

    @Override
    public SodsiRegionesMideplan as(Name alias) {
        return new SodsiRegionesMideplan(alias, this);
    }

    @Override
    public SodsiRegionesMideplan as(Table<?> alias) {
        return new SodsiRegionesMideplan(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SodsiRegionesMideplan rename(String name) {
        return new SodsiRegionesMideplan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SodsiRegionesMideplan rename(Name name) {
        return new SodsiRegionesMideplan(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SodsiRegionesMideplan rename(Table<?> name) {
        return new SodsiRegionesMideplan(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiRegionesMideplan where(Condition condition) {
        return new SodsiRegionesMideplan(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiRegionesMideplan where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiRegionesMideplan where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiRegionesMideplan where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SodsiRegionesMideplan where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SodsiRegionesMideplan where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SodsiRegionesMideplan where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SodsiRegionesMideplan where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiRegionesMideplan whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiRegionesMideplan whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
