/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables;


import com.odsProject.odsProject.database.jooq.ods_login.Keys;
import com.odsProject.odsProject.database.jooq.ods_login.OdsLogin;
import com.odsProject.odsProject.database.jooq.ods_login.enums.SodsiAliadoTipoAmbito;
import com.odsProject.odsProject.database.jooq.ods_login.enums.SodsiAliadoTipoTipo;
import com.odsProject.odsProject.database.jooq.ods_login.tables.records.SodsiAliadoTipoRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SodsiAliadoTipo extends TableImpl<SodsiAliadoTipoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods_login.sodsi_aliado_tipo</code>
     */
    public static final SodsiAliadoTipo SODSI_ALIADO_TIPO = new SodsiAliadoTipo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SodsiAliadoTipoRecord> getRecordType() {
        return SodsiAliadoTipoRecord.class;
    }

    /**
     * The column <code>ods_login.sodsi_aliado_tipo.id</code>.
     */
    public final TableField<SodsiAliadoTipoRecord, UShort> ID = createField(DSL.name("id"), SQLDataType.SMALLINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>ods_login.sodsi_aliado_tipo.ambito</code>.
     */
    public final TableField<SodsiAliadoTipoRecord, SodsiAliadoTipoAmbito> AMBITO = createField(DSL.name("ambito"), SQLDataType.VARCHAR(13).nullable(false).asEnumDataType(SodsiAliadoTipoAmbito.class), this, "");

    /**
     * The column <code>ods_login.sodsi_aliado_tipo.tipo</code>.
     */
    public final TableField<SodsiAliadoTipoRecord, SodsiAliadoTipoTipo> TIPO = createField(DSL.name("tipo"), SQLDataType.VARCHAR(13).nullable(false).asEnumDataType(SodsiAliadoTipoTipo.class), this, "");

    /**
     * The column <code>ods_login.sodsi_aliado_tipo.etiqueta</code>.
     */
    public final TableField<SodsiAliadoTipoRecord, String> ETIQUETA = createField(DSL.name("etiqueta"), SQLDataType.VARCHAR(120).nullable(false), this, "");

    /**
     * The column <code>ods_login.sodsi_aliado_tipo.orden</code>.
     */
    public final TableField<SodsiAliadoTipoRecord, UShort> ORDEN = createField(DSL.name("orden"), SQLDataType.SMALLINTUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINTUNSIGNED)), this, "");

    private SodsiAliadoTipo(Name alias, Table<SodsiAliadoTipoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SodsiAliadoTipo(Name alias, Table<SodsiAliadoTipoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ods_login.sodsi_aliado_tipo</code> table
     * reference
     */
    public SodsiAliadoTipo(String alias) {
        this(DSL.name(alias), SODSI_ALIADO_TIPO);
    }

    /**
     * Create an aliased <code>ods_login.sodsi_aliado_tipo</code> table
     * reference
     */
    public SodsiAliadoTipo(Name alias) {
        this(alias, SODSI_ALIADO_TIPO);
    }

    /**
     * Create a <code>ods_login.sodsi_aliado_tipo</code> table reference
     */
    public SodsiAliadoTipo() {
        this(DSL.name("sodsi_aliado_tipo"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OdsLogin.ODS_LOGIN;
    }

    @Override
    public Identity<SodsiAliadoTipoRecord, UShort> getIdentity() {
        return (Identity<SodsiAliadoTipoRecord, UShort>) super.getIdentity();
    }

    @Override
    public UniqueKey<SodsiAliadoTipoRecord> getPrimaryKey() {
        return Keys.KEY_SODSI_ALIADO_TIPO_PRIMARY;
    }

    @Override
    public List<UniqueKey<SodsiAliadoTipoRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SODSI_ALIADO_TIPO_UK_SODSI_ALIADO_AMBITO_TIPO);
    }

    @Override
    public SodsiAliadoTipo as(String alias) {
        return new SodsiAliadoTipo(DSL.name(alias), this);
    }

    @Override
    public SodsiAliadoTipo as(Name alias) {
        return new SodsiAliadoTipo(alias, this);
    }

    @Override
    public SodsiAliadoTipo as(Table<?> alias) {
        return new SodsiAliadoTipo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SodsiAliadoTipo rename(String name) {
        return new SodsiAliadoTipo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SodsiAliadoTipo rename(Name name) {
        return new SodsiAliadoTipo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SodsiAliadoTipo rename(Table<?> name) {
        return new SodsiAliadoTipo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiAliadoTipo where(Condition condition) {
        return new SodsiAliadoTipo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiAliadoTipo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiAliadoTipo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiAliadoTipo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SodsiAliadoTipo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SodsiAliadoTipo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SodsiAliadoTipo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SodsiAliadoTipo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiAliadoTipo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SodsiAliadoTipo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
