/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods_login.tables.records;


import com.projectods.database.jooq.ods_login.enums.VistaAdminIntentosLoginRole;
import com.projectods.database.jooq.ods_login.tables.VistaAdminIntentosLogin;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAdminIntentosLoginRecord extends TableRecordImpl<VistaAdminIntentosLoginRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ods_login.vista_admin_intentos_login.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ods_login.vista_admin_intentos_login.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.username</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ods_login.vista_admin_intentos_login.success</code>.
     */
    public void setSuccess(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.success</code>.
     */
    @NotNull
    public Byte getSuccess() {
        return (Byte) get(2);
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_intentos_login.failure_reason</code>.
     */
    public void setFailureReason(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_intentos_login.failure_reason</code>.
     */
    @Size(max = 100)
    public String getFailureReason() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ods_login.vista_admin_intentos_login.ip_address</code>.
     */
    public void setIpAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.ip_address</code>.
     */
    @Size(max = 45)
    public String getIpAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ods_login.vista_admin_intentos_login.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.user_agent</code>.
     */
    @Size(max = 65535)
    public String getUserAgent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ods_login.vista_admin_intentos_login.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>ods_login.vista_admin_intentos_login.periodo</code>.
     */
    public void setPeriodo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.periodo</code>.
     */
    @Size(max = 16)
    public String getPeriodo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ods_login.vista_admin_intentos_login.full_name</code>.
     */
    public void setFullName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.full_name</code>.
     */
    @Size(max = 100)
    public String getFullName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ods_login.vista_admin_intentos_login.role</code>.
     */
    public void setRole(VistaAdminIntentosLoginRole value) {
        set(9, value);
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.role</code>.
     */
    public VistaAdminIntentosLoginRole getRole() {
        return (VistaAdminIntentosLoginRole) get(9);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaAdminIntentosLoginRecord
     */
    public VistaAdminIntentosLoginRecord() {
        super(VistaAdminIntentosLogin.VISTA_ADMIN_INTENTOS_LOGIN);
    }

    /**
     * Create a detached, initialised VistaAdminIntentosLoginRecord
     */
    public VistaAdminIntentosLoginRecord(Integer id, String username, Byte success, String failureReason, String ipAddress, String userAgent, LocalDateTime createdAt, String periodo, String fullName, VistaAdminIntentosLoginRole role) {
        super(VistaAdminIntentosLogin.VISTA_ADMIN_INTENTOS_LOGIN);

        setId(id);
        setUsername(username);
        setSuccess(success);
        setFailureReason(failureReason);
        setIpAddress(ipAddress);
        setUserAgent(userAgent);
        setCreatedAt(createdAt);
        setPeriodo(periodo);
        setFullName(fullName);
        setRole(role);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaAdminIntentosLoginRecord
     */
    public VistaAdminIntentosLoginRecord(com.projectods.database.jooq.ods_login.tables.pojos.VistaAdminIntentosLogin value) {
        super(VistaAdminIntentosLogin.VISTA_ADMIN_INTENTOS_LOGIN);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setSuccess(value.getSuccess());
            setFailureReason(value.getFailureReason());
            setIpAddress(value.getIpAddress());
            setUserAgent(value.getUserAgent());
            setCreatedAt(value.getCreatedAt());
            setPeriodo(value.getPeriodo());
            setFullName(value.getFullName());
            setRole(value.getRole());
            resetChangedOnNotNull();
        }
    }
}
