/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.records;


import com.odsProject.odsProject.database.jooq.ods_login.tables.IntentosLogin;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Registro de intentos de login para seguridad
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IntentosLoginRecord extends UpdatableRecordImpl<IntentosLoginRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ods_login.intentos_login.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ods_login.intentos_login.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ods_login.intentos_login.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ods_login.intentos_login.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ods_login.intentos_login.ip_address</code>.
     */
    public void setIpAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ods_login.intentos_login.ip_address</code>.
     */
    public String getIpAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ods_login.intentos_login.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ods_login.intentos_login.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ods_login.intentos_login.success</code>.
     */
    public void setSuccess(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>ods_login.intentos_login.success</code>.
     */
    public Byte getSuccess() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>ods_login.intentos_login.failure_reason</code>.
     */
    public void setFailureReason(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ods_login.intentos_login.failure_reason</code>.
     */
    public String getFailureReason() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ods_login.intentos_login.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>ods_login.intentos_login.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IntentosLoginRecord
     */
    public IntentosLoginRecord() {
        super(IntentosLogin.INTENTOS_LOGIN);
    }

    /**
     * Create a detached, initialised IntentosLoginRecord
     */
    public IntentosLoginRecord(Integer id, String username, String ipAddress, String userAgent, Byte success, String failureReason, LocalDateTime createdAt) {
        super(IntentosLogin.INTENTOS_LOGIN);

        setId(id);
        setUsername(username);
        setIpAddress(ipAddress);
        setUserAgent(userAgent);
        setSuccess(success);
        setFailureReason(failureReason);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IntentosLoginRecord
     */
    public IntentosLoginRecord(com.odsProject.odsProject.database.jooq.ods_login.tables.pojos.IntentosLogin value) {
        super(IntentosLogin.INTENTOS_LOGIN);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setIpAddress(value.getIpAddress());
            setUserAgent(value.getUserAgent());
            setSuccess(value.getSuccess());
            setFailureReason(value.getFailureReason());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
