/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.records;


import com.odsProject.odsProject.database.jooq.ods_login.tables.PermisosOds;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * Qué ODS puede gestionar cada usuario
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PermisosOdsRecord extends UpdatableRecordImpl<PermisosOdsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ods_login.permisos_ods.id</code>.
     */
    public PermisosOdsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ods_login.permisos_ods.usuario_id</code>.
     */
    public PermisosOdsRecord setUsuarioId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.usuario_id</code>.
     */
    public Integer getUsuarioId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ods_login.permisos_ods.ods_num</code>.
     */
    public PermisosOdsRecord setOdsNum(UByte value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.ods_num</code>.
     */
    public UByte getOdsNum() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>ods_login.permisos_ods.puede_crear</code>.
     */
    public PermisosOdsRecord setPuedeCrear(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.puede_crear</code>.
     */
    public Byte getPuedeCrear() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>ods_login.permisos_ods.puede_editar</code>.
     */
    public PermisosOdsRecord setPuedeEditar(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.puede_editar</code>.
     */
    public Byte getPuedeEditar() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>ods_login.permisos_ods.puede_ver</code>.
     */
    public PermisosOdsRecord setPuedeVer(Byte value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.puede_ver</code>.
     */
    public Byte getPuedeVer() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>ods_login.permisos_ods.created_at</code>.
     */
    public PermisosOdsRecord setCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermisosOdsRecord
     */
    public PermisosOdsRecord() {
        super(PermisosOds.PERMISOS_ODS);
    }

    /**
     * Create a detached, initialised PermisosOdsRecord
     */
    public PermisosOdsRecord(Integer id, Integer usuarioId, UByte odsNum, Byte puedeCrear, Byte puedeEditar, Byte puedeVer, LocalDateTime createdAt) {
        super(PermisosOds.PERMISOS_ODS);

        setId(id);
        setUsuarioId(usuarioId);
        setOdsNum(odsNum);
        setPuedeCrear(puedeCrear);
        setPuedeEditar(puedeEditar);
        setPuedeVer(puedeVer);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PermisosOdsRecord
     */
    public PermisosOdsRecord(com.odsProject.odsProject.database.jooq.ods_login.tables.pojos.PermisosOds value) {
        super(PermisosOds.PERMISOS_ODS);

        if (value != null) {
            setId(value.getId());
            setUsuarioId(value.getUsuarioId());
            setOdsNum(value.getOdsNum());
            setPuedeCrear(value.getPuedeCrear());
            setPuedeEditar(value.getPuedeEditar());
            setPuedeVer(value.getPuedeVer());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
