/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.records;


import com.odsProject.odsProject.database.jooq.ods_login.enums.SodsiUnidadesProgramaticasTipo;
import com.odsProject.odsProject.database.jooq.ods_login.tables.SodsiUnidadesProgramaticas;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SodsiUnidadesProgramaticasRecord extends UpdatableRecordImpl<SodsiUnidadesProgramaticasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ods_login.sodsi_unidades_programaticas.id</code>.
     */
    public SodsiUnidadesProgramaticasRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_unidades_programaticas.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ods_login.sodsi_unidades_programaticas.codigo</code>.
     */
    public SodsiUnidadesProgramaticasRecord setCodigo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_unidades_programaticas.codigo</code>.
     */
    public String getCodigo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ods_login.sodsi_unidades_programaticas.nombre</code>.
     */
    public SodsiUnidadesProgramaticasRecord setNombre(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_unidades_programaticas.nombre</code>.
     */
    public String getNombre() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ods_login.sodsi_unidades_programaticas.tipo</code>.
     */
    public SodsiUnidadesProgramaticasRecord setTipo(SodsiUnidadesProgramaticasTipo value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_unidades_programaticas.tipo</code>.
     */
    public SodsiUnidadesProgramaticasTipo getTipo() {
        return (SodsiUnidadesProgramaticasTipo) get(3);
    }

    /**
     * Setter for <code>ods_login.sodsi_unidades_programaticas.sede_ref</code>.
     * Nombre sede UTN de referencia
     */
    public SodsiUnidadesProgramaticasRecord setSedeRef(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_unidades_programaticas.sede_ref</code>.
     * Nombre sede UTN de referencia
     */
    public String getSedeRef() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ods_login.sodsi_unidades_programaticas.activo</code>.
     */
    public SodsiUnidadesProgramaticasRecord setActivo(Byte value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_unidades_programaticas.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>ods_login.sodsi_unidades_programaticas.orden</code>.
     */
    public SodsiUnidadesProgramaticasRecord setOrden(UShort value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_unidades_programaticas.orden</code>.
     */
    public UShort getOrden() {
        return (UShort) get(6);
    }

    /**
     * Setter for
     * <code>ods_login.sodsi_unidades_programaticas.created_at</code>.
     */
    public SodsiUnidadesProgramaticasRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods_login.sodsi_unidades_programaticas.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SodsiUnidadesProgramaticasRecord
     */
    public SodsiUnidadesProgramaticasRecord() {
        super(SodsiUnidadesProgramaticas.SODSI_UNIDADES_PROGRAMATICAS);
    }

    /**
     * Create a detached, initialised SodsiUnidadesProgramaticasRecord
     */
    public SodsiUnidadesProgramaticasRecord(Integer id, String codigo, String nombre, SodsiUnidadesProgramaticasTipo tipo, String sedeRef, Byte activo, UShort orden, LocalDateTime createdAt) {
        super(SodsiUnidadesProgramaticas.SODSI_UNIDADES_PROGRAMATICAS);

        setId(id);
        setCodigo(codigo);
        setNombre(nombre);
        setTipo(tipo);
        setSedeRef(sedeRef);
        setActivo(activo);
        setOrden(orden);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SodsiUnidadesProgramaticasRecord
     */
    public SodsiUnidadesProgramaticasRecord(com.odsProject.odsProject.database.jooq.ods_login.tables.pojos.SodsiUnidadesProgramaticas value) {
        super(SodsiUnidadesProgramaticas.SODSI_UNIDADES_PROGRAMATICAS);

        if (value != null) {
            setId(value.getId());
            setCodigo(value.getCodigo());
            setNombre(value.getNombre());
            setTipo(value.getTipo());
            setSedeRef(value.getSedeRef());
            setActivo(value.getActivo());
            setOrden(value.getOrden());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
