/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.records;


import com.odsProject.odsProject.database.jooq.ods_login.tables.Usuarios;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * Usuarios centrales; referenciados por todas las bases ods_XX
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsuariosRecord extends UpdatableRecordImpl<UsuariosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ods_login.usuarios.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ods_login.usuarios.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ods_login.usuarios.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ods_login.usuarios.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ods_login.usuarios.full_name</code>.
     */
    public void setFullName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.full_name</code>.
     */
    public String getFullName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ods_login.usuarios.rol_id</code>.
     */
    public void setRolId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.rol_id</code>.
     */
    public Integer getRolId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>ods_login.usuarios.is_active</code>.
     */
    public void setIsActive(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.is_active</code>.
     */
    public Byte getIsActive() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>ods_login.usuarios.email_verificado</code>.
     */
    public void setEmailVerificado(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.email_verificado</code>.
     */
    public Byte getEmailVerificado() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>ods_login.usuarios.ultimo_login</code>.
     */
    public void setUltimoLogin(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.ultimo_login</code>.
     */
    public LocalDateTime getUltimoLogin() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>ods_login.usuarios.intentos_fallidos</code>.
     */
    public void setIntentosFallidos(UByte value) {
        set(9, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.intentos_fallidos</code>.
     */
    public UByte getIntentosFallidos() {
        return (UByte) get(9);
    }

    /**
     * Setter for <code>ods_login.usuarios.bloqueado_hasta</code>.
     */
    public void setBloqueadoHasta(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.bloqueado_hasta</code>.
     */
    public LocalDateTime getBloqueadoHasta() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>ods_login.usuarios.token_recuperacion</code>.
     */
    public void setTokenRecuperacion(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.token_recuperacion</code>.
     */
    public String getTokenRecuperacion() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ods_login.usuarios.token_expira</code>.
     */
    public void setTokenExpira(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.token_expira</code>.
     */
    public LocalDateTime getTokenExpira() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>ods_login.usuarios.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>ods_login.usuarios.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>ods_login.usuarios.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuariosRecord
     */
    public UsuariosRecord() {
        super(Usuarios.USUARIOS);
    }

    /**
     * Create a detached, initialised UsuariosRecord
     */
    public UsuariosRecord(Integer id, String username, String email, String passwordHash, String fullName, Integer rolId, Byte isActive, Byte emailVerificado, LocalDateTime ultimoLogin, UByte intentosFallidos, LocalDateTime bloqueadoHasta, String tokenRecuperacion, LocalDateTime tokenExpira, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Usuarios.USUARIOS);

        setId(id);
        setUsername(username);
        setEmail(email);
        setPasswordHash(passwordHash);
        setFullName(fullName);
        setRolId(rolId);
        setIsActive(isActive);
        setEmailVerificado(emailVerificado);
        setUltimoLogin(ultimoLogin);
        setIntentosFallidos(intentosFallidos);
        setBloqueadoHasta(bloqueadoHasta);
        setTokenRecuperacion(tokenRecuperacion);
        setTokenExpira(tokenExpira);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsuariosRecord
     */
    public UsuariosRecord(com.odsProject.odsProject.database.jooq.ods_login.tables.pojos.Usuarios value) {
        super(Usuarios.USUARIOS);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setEmail(value.getEmail());
            setPasswordHash(value.getPasswordHash());
            setFullName(value.getFullName());
            setRolId(value.getRolId());
            setIsActive(value.getIsActive());
            setEmailVerificado(value.getEmailVerificado());
            setUltimoLogin(value.getUltimoLogin());
            setIntentosFallidos(value.getIntentosFallidos());
            setBloqueadoHasta(value.getBloqueadoHasta());
            setTokenRecuperacion(value.getTokenRecuperacion());
            setTokenExpira(value.getTokenExpira());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
