/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods02.tables;


import com.odsProject.odsProject.database.jooq.ods02.Indexes;
import com.odsProject.odsProject.database.jooq.ods02.Keys;
import com.odsProject.odsProject.database.jooq.ods02.Ods02;
import com.odsProject.odsProject.database.jooq.ods02.tables.records.AuditoriaOds02Record;
import com.odsProject.odsProject.database.jooq.ods_login.tables.Usuarios.UsuariosPath;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Auditoría de cambios en el sistema ODS02
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditoriaOds02 extends TableImpl<AuditoriaOds02Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods02.auditoria_ods02</code>
     */
    public static final AuditoriaOds02 AUDITORIA_ODS02 = new AuditoriaOds02();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditoriaOds02Record> getRecordType() {
        return AuditoriaOds02Record.class;
    }

    /**
     * The column <code>ods02.auditoria_ods02.id</code>.
     */
    public final TableField<AuditoriaOds02Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ods02.auditoria_ods02.tabla_afectada</code>.
     */
    public final TableField<AuditoriaOds02Record, String> TABLA_AFECTADA = createField(DSL.name("tabla_afectada"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>ods02.auditoria_ods02.registro_id</code>.
     */
    public final TableField<AuditoriaOds02Record, Integer> REGISTRO_ID = createField(DSL.name("registro_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ods02.auditoria_ods02.accion</code>.
     */
    public final TableField<AuditoriaOds02Record, String> ACCION = createField(DSL.name("accion"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>ods02.auditoria_ods02.usuario_id</code>.
     */
    public final TableField<AuditoriaOds02Record, Integer> USUARIO_ID = createField(DSL.name("usuario_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ods02.auditoria_ods02.valores_anteriores</code>.
     */
    public final TableField<AuditoriaOds02Record, String> VALORES_ANTERIORES = createField(DSL.name("valores_anteriores"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods02.auditoria_ods02.valores_nuevos</code>.
     */
    public final TableField<AuditoriaOds02Record, String> VALORES_NUEVOS = createField(DSL.name("valores_nuevos"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods02.auditoria_ods02.fecha_cambio</code>.
     */
    public final TableField<AuditoriaOds02Record, LocalDateTime> FECHA_CAMBIO = createField(DSL.name("fecha_cambio"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>ods02.auditoria_ods02.ip_address</code>.
     */
    public final TableField<AuditoriaOds02Record, String> IP_ADDRESS = createField(DSL.name("ip_address"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private AuditoriaOds02(Name alias, Table<AuditoriaOds02Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuditoriaOds02(Name alias, Table<AuditoriaOds02Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Auditoría de cambios en el sistema ODS02"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ods02.auditoria_ods02</code> table reference
     */
    public AuditoriaOds02(String alias) {
        this(DSL.name(alias), AUDITORIA_ODS02);
    }

    /**
     * Create an aliased <code>ods02.auditoria_ods02</code> table reference
     */
    public AuditoriaOds02(Name alias) {
        this(alias, AUDITORIA_ODS02);
    }

    /**
     * Create a <code>ods02.auditoria_ods02</code> table reference
     */
    public AuditoriaOds02() {
        this(DSL.name("auditoria_ods02"), null);
    }

    public <O extends Record> AuditoriaOds02(Table<O> path, ForeignKey<O, AuditoriaOds02Record> childPath, InverseForeignKey<O, AuditoriaOds02Record> parentPath) {
        super(path, childPath, parentPath, AUDITORIA_ODS02);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuditoriaOds02Path extends AuditoriaOds02 implements Path<AuditoriaOds02Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuditoriaOds02Path(Table<O> path, ForeignKey<O, AuditoriaOds02Record> childPath, InverseForeignKey<O, AuditoriaOds02Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuditoriaOds02Path(Name alias, Table<AuditoriaOds02Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuditoriaOds02Path as(String alias) {
            return new AuditoriaOds02Path(DSL.name(alias), this);
        }

        @Override
        public AuditoriaOds02Path as(Name alias) {
            return new AuditoriaOds02Path(alias, this);
        }

        @Override
        public AuditoriaOds02Path as(Table<?> alias) {
            return new AuditoriaOds02Path(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ods02.ODS02;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUDITORIA_ODS02_IDX_AUDITORIA_FECHA_TABLA, Indexes.AUDITORIA_ODS02_IDX_FECHA, Indexes.AUDITORIA_ODS02_IDX_TABLA_REGISTRO, Indexes.AUDITORIA_ODS02_USUARIO_ID);
    }

    @Override
    public Identity<AuditoriaOds02Record, Integer> getIdentity() {
        return (Identity<AuditoriaOds02Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuditoriaOds02Record> getPrimaryKey() {
        return Keys.KEY_AUDITORIA_ODS02_PRIMARY;
    }

    @Override
    public List<ForeignKey<AuditoriaOds02Record, ?>> getReferences() {
        return Arrays.asList(Keys.AUDITORIA_ODS02_IBFK_1);
    }

    private transient UsuariosPath _usuarios;

    /**
     * Get the implicit join path to the <code>ods_login.usuarios</code> table.
     */
    public UsuariosPath usuarios() {
        if (_usuarios == null)
            _usuarios = new UsuariosPath(this, Keys.AUDITORIA_ODS02_IBFK_1, null);

        return _usuarios;
    }

    @Override
    public List<Check<AuditoriaOds02Record>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("valores_anteriores"), "json_valid(`valores_anteriores`)", true),
            Internal.createCheck(this, DSL.name("valores_nuevos"), "json_valid(`valores_nuevos`)", true)
        );
    }

    @Override
    public AuditoriaOds02 as(String alias) {
        return new AuditoriaOds02(DSL.name(alias), this);
    }

    @Override
    public AuditoriaOds02 as(Name alias) {
        return new AuditoriaOds02(alias, this);
    }

    @Override
    public AuditoriaOds02 as(Table<?> alias) {
        return new AuditoriaOds02(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds02 rename(String name) {
        return new AuditoriaOds02(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds02 rename(Name name) {
        return new AuditoriaOds02(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds02 rename(Table<?> name) {
        return new AuditoriaOds02(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds02 where(Condition condition) {
        return new AuditoriaOds02(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds02 where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds02 where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds02 where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds02 where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds02 where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds02 where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds02 where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds02 whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds02 whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
