/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum AuditoriaLoginEvento implements EnumType {

    LOGIN_OK("LOGIN_OK"),

    LOGIN_FALLIDO("LOGIN_FALLIDO"),

    LOGOUT("LOGOUT"),

    TOKEN_RECUPERACION("TOKEN_RECUPERACION"),

    CAMBIO_PASSWORD("CAMBIO_PASSWORD"),

    CUENTA_BLOQUEADA("CUENTA_BLOQUEADA"),

    SESION_EXPIRADA("SESION_EXPIRADA"),

    REGISTRO("REGISTRO");

    private final String literal;

    private AuditoriaLoginEvento(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static AuditoriaLoginEvento lookupLiteral(String literal) {
        return EnumType.lookupLiteral(AuditoriaLoginEvento.class, literal);
    }
}
