/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods13.tables.records;


import com.odsProject.odsProject.database.jooq.ods13.tables.ProyectoIndicadores;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProyectoIndicadoresRecord extends UpdatableRecordImpl<ProyectoIndicadoresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ods13.proyecto_indicadores.id</code>.
     */
    public ProyectoIndicadoresRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ods13.proyecto_indicadores.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ods13.proyecto_indicadores.proyecto_id</code>.
     */
    public ProyectoIndicadoresRecord setProyectoId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ods13.proyecto_indicadores.proyecto_id</code>.
     */
    public Integer getProyectoId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ods13.proyecto_indicadores.indicador_master_id</code>.
     */
    public ProyectoIndicadoresRecord setIndicadorMasterId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ods13.proyecto_indicadores.indicador_master_id</code>.
     */
    public Integer getIndicadorMasterId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ods13.proyecto_indicadores.formula_custom</code>.
     */
    public ProyectoIndicadoresRecord setFormulaCustom(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ods13.proyecto_indicadores.formula_custom</code>.
     */
    public String getFormulaCustom() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ods13.proyecto_indicadores.valor_actual</code>.
     */
    public ProyectoIndicadoresRecord setValorActual(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ods13.proyecto_indicadores.valor_actual</code>.
     */
    public BigDecimal getValorActual() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>ods13.proyecto_indicadores.meta_valor</code>.
     */
    public ProyectoIndicadoresRecord setMetaValor(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ods13.proyecto_indicadores.meta_valor</code>.
     */
    public BigDecimal getMetaValor() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>ods13.proyecto_indicadores.meta_unidad</code>.
     */
    public ProyectoIndicadoresRecord setMetaUnidad(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ods13.proyecto_indicadores.meta_unidad</code>.
     */
    public String getMetaUnidad() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ods13.proyecto_indicadores.meta_nombre</code>.
     */
    public ProyectoIndicadoresRecord setMetaNombre(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ods13.proyecto_indicadores.meta_nombre</code>.
     */
    public String getMetaNombre() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>ods13.proyecto_indicadores.fecha_proxima_medicion</code>.
     */
    public ProyectoIndicadoresRecord setFechaProximaMedicion(LocalDate value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>ods13.proyecto_indicadores.fecha_proxima_medicion</code>.
     */
    public LocalDate getFechaProximaMedicion() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>ods13.proyecto_indicadores.created_at</code>.
     */
    public ProyectoIndicadoresRecord setCreatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ods13.proyecto_indicadores.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>ods13.proyecto_indicadores.updated_at</code>.
     */
    public ProyectoIndicadoresRecord setUpdatedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ods13.proyecto_indicadores.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProyectoIndicadoresRecord
     */
    public ProyectoIndicadoresRecord() {
        super(ProyectoIndicadores.PROYECTO_INDICADORES);
    }

    /**
     * Create a detached, initialised ProyectoIndicadoresRecord
     */
    public ProyectoIndicadoresRecord(Integer id, Integer proyectoId, Integer indicadorMasterId, String formulaCustom, BigDecimal valorActual, BigDecimal metaValor, String metaUnidad, String metaNombre, LocalDate fechaProximaMedicion, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(ProyectoIndicadores.PROYECTO_INDICADORES);

        setId(id);
        setProyectoId(proyectoId);
        setIndicadorMasterId(indicadorMasterId);
        setFormulaCustom(formulaCustom);
        setValorActual(valorActual);
        setMetaValor(metaValor);
        setMetaUnidad(metaUnidad);
        setMetaNombre(metaNombre);
        setFechaProximaMedicion(fechaProximaMedicion);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProyectoIndicadoresRecord
     */
    public ProyectoIndicadoresRecord(com.odsProject.odsProject.database.jooq.ods13.tables.pojos.ProyectoIndicadores value) {
        super(ProyectoIndicadores.PROYECTO_INDICADORES);

        if (value != null) {
            setId(value.getId());
            setProyectoId(value.getProyectoId());
            setIndicadorMasterId(value.getIndicadorMasterId());
            setFormulaCustom(value.getFormulaCustom());
            setValorActual(value.getValorActual());
            setMetaValor(value.getMetaValor());
            setMetaUnidad(value.getMetaUnidad());
            setMetaNombre(value.getMetaNombre());
            setFechaProximaMedicion(value.getFechaProximaMedicion());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
