/*
 * This file is generated by jOOQ.
 */
package database.jooq.ods_login.tables;


import database.jooq.ods_login.OdsLogin;
import database.jooq.ods_login.enums.VistaAdminUsuariosRole;
import database.jooq.ods_login.tables.records.VistaAdminUsuariosRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAdminUsuarios extends TableImpl<VistaAdminUsuariosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods_login.vista_admin_usuarios</code>
     */
    public static final VistaAdminUsuarios VISTA_ADMIN_USUARIOS = new VistaAdminUsuarios();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VistaAdminUsuariosRecord> getRecordType() {
        return VistaAdminUsuariosRecord.class;
    }

    /**
     * The column <code>ods_login.vista_admin_usuarios.id</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.username</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.email</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.full_name</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.role</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, VistaAdminUsuariosRole> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(5).defaultValue(DSL.field(DSL.raw("'user'"), SQLDataType.VARCHAR)).asEnumDataType(VistaAdminUsuariosRole.class), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.department</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, String> DEPARTMENT = createField(DSL.name("department"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.organization</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, String> ORGANIZATION = createField(DSL.name("organization"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.created_at</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.last_login</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, LocalDateTime> LAST_LOGIN = createField(DSL.name("last_login"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.is_active</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("1"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.email_verified</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, Byte> EMAIL_VERIFIED = createField(DSL.name("email_verified"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.sesiones_activas</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, Long> SESIONES_ACTIVAS = createField(DSL.name("sesiones_activas"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>ods_login.vista_admin_usuarios.ultima_sesion</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, LocalDateTime> ULTIMA_SESION = createField(DSL.name("ultima_sesion"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>ods_login.vista_admin_usuarios.logins_exitosos_30d</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, Long> LOGINS_EXITOSOS_30D = createField(DSL.name("logins_exitosos_30d"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>ods_login.vista_admin_usuarios.logins_fallidos_30d</code>.
     */
    public final TableField<VistaAdminUsuariosRecord, Long> LOGINS_FALLIDOS_30D = createField(DSL.name("logins_fallidos_30d"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    private VistaAdminUsuarios(Name alias, Table<VistaAdminUsuariosRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VistaAdminUsuarios(Name alias, Table<VistaAdminUsuariosRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view `vista_admin_usuarios` as select `u`.`id` AS `id`,`u`.`username` AS `username`,`u`.`email` AS `email`,`u`.`full_name` AS `full_name`,`u`.`role` AS `role`,`u`.`department` AS `department`,`u`.`organization` AS `organization`,`u`.`created_at` AS `created_at`,`u`.`last_login` AS `last_login`,`u`.`is_active` AS `is_active`,`u`.`email_verified` AS `email_verified`,count(distinct `s`.`id`) AS `sesiones_activas`,max(`s`.`created_at`) AS `ultima_sesion`,count(distinct case when `il`.`success` = 1 and `il`.`created_at` > current_timestamp() - interval 30 day then `il`.`id` end) AS `logins_exitosos_30d`,count(distinct case when `il`.`success` = 0 and `il`.`created_at` > current_timestamp() - interval 30 day then `il`.`id` end) AS `logins_fallidos_30d` from ((`ods_login`.`usuarios` `u` left join `ods_login`.`sesiones` `s` on(`u`.`id` = `s`.`usuario_id` and `s`.`is_active` = 1 and `s`.`expires_at` > current_timestamp())) left join `ods_login`.`intentos_login` `il` on(`u`.`username` = `il`.`username` and `il`.`created_at` > current_timestamp() - interval 30 day)) group by `u`.`id`,`u`.`username`,`u`.`email`,`u`.`full_name`,`u`.`role`,`u`.`department`,`u`.`organization`,`u`.`created_at`,`u`.`last_login`,`u`.`is_active`,`u`.`email_verified` order by `u`.`created_at` desc"), where);
    }

    /**
     * Create an aliased <code>ods_login.vista_admin_usuarios</code> table
     * reference
     */
    public VistaAdminUsuarios(String alias) {
        this(DSL.name(alias), VISTA_ADMIN_USUARIOS);
    }

    /**
     * Create an aliased <code>ods_login.vista_admin_usuarios</code> table
     * reference
     */
    public VistaAdminUsuarios(Name alias) {
        this(alias, VISTA_ADMIN_USUARIOS);
    }

    /**
     * Create a <code>ods_login.vista_admin_usuarios</code> table reference
     */
    public VistaAdminUsuarios() {
        this(DSL.name("vista_admin_usuarios"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OdsLogin.ODS_LOGIN;
    }

    @Override
    public VistaAdminUsuarios as(String alias) {
        return new VistaAdminUsuarios(DSL.name(alias), this);
    }

    @Override
    public VistaAdminUsuarios as(Name alias) {
        return new VistaAdminUsuarios(alias, this);
    }

    @Override
    public VistaAdminUsuarios as(Table<?> alias) {
        return new VistaAdminUsuarios(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaAdminUsuarios rename(String name) {
        return new VistaAdminUsuarios(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaAdminUsuarios rename(Name name) {
        return new VistaAdminUsuarios(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaAdminUsuarios rename(Table<?> name) {
        return new VistaAdminUsuarios(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaAdminUsuarios where(Condition condition) {
        return new VistaAdminUsuarios(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaAdminUsuarios where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaAdminUsuarios where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaAdminUsuarios where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaAdminUsuarios where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaAdminUsuarios where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaAdminUsuarios where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaAdminUsuarios where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaAdminUsuarios whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaAdminUsuarios whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
