/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods05.tables;


import com.odsProject.odsProject.database.jooq.ods05.Indexes;
import com.odsProject.odsProject.database.jooq.ods05.Keys;
import com.odsProject.odsProject.database.jooq.ods05.Ods05;
import com.odsProject.odsProject.database.jooq.ods05.tables.records.AuditoriaOds05Record;
import com.odsProject.odsProject.database.jooq.ods_login.tables.Usuarios.UsuariosPath;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Auditoría de cambios en el sistema ODS05
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditoriaOds05 extends TableImpl<AuditoriaOds05Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods05.auditoria_ods05</code>
     */
    public static final AuditoriaOds05 AUDITORIA_ODS05 = new AuditoriaOds05();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditoriaOds05Record> getRecordType() {
        return AuditoriaOds05Record.class;
    }

    /**
     * The column <code>ods05.auditoria_ods05.id</code>.
     */
    public final TableField<AuditoriaOds05Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ods05.auditoria_ods05.tabla_afectada</code>.
     */
    public final TableField<AuditoriaOds05Record, String> TABLA_AFECTADA = createField(DSL.name("tabla_afectada"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>ods05.auditoria_ods05.registro_id</code>.
     */
    public final TableField<AuditoriaOds05Record, Integer> REGISTRO_ID = createField(DSL.name("registro_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ods05.auditoria_ods05.accion</code>.
     */
    public final TableField<AuditoriaOds05Record, String> ACCION = createField(DSL.name("accion"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>ods05.auditoria_ods05.usuario_id</code>.
     */
    public final TableField<AuditoriaOds05Record, Integer> USUARIO_ID = createField(DSL.name("usuario_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ods05.auditoria_ods05.valores_anteriores</code>.
     */
    public final TableField<AuditoriaOds05Record, String> VALORES_ANTERIORES = createField(DSL.name("valores_anteriores"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods05.auditoria_ods05.valores_nuevos</code>.
     */
    public final TableField<AuditoriaOds05Record, String> VALORES_NUEVOS = createField(DSL.name("valores_nuevos"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods05.auditoria_ods05.fecha_cambio</code>.
     */
    public final TableField<AuditoriaOds05Record, LocalDateTime> FECHA_CAMBIO = createField(DSL.name("fecha_cambio"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>ods05.auditoria_ods05.ip_address</code>.
     */
    public final TableField<AuditoriaOds05Record, String> IP_ADDRESS = createField(DSL.name("ip_address"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private AuditoriaOds05(Name alias, Table<AuditoriaOds05Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuditoriaOds05(Name alias, Table<AuditoriaOds05Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Auditoría de cambios en el sistema ODS05"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ods05.auditoria_ods05</code> table reference
     */
    public AuditoriaOds05(String alias) {
        this(DSL.name(alias), AUDITORIA_ODS05);
    }

    /**
     * Create an aliased <code>ods05.auditoria_ods05</code> table reference
     */
    public AuditoriaOds05(Name alias) {
        this(alias, AUDITORIA_ODS05);
    }

    /**
     * Create a <code>ods05.auditoria_ods05</code> table reference
     */
    public AuditoriaOds05() {
        this(DSL.name("auditoria_ods05"), null);
    }

    public <O extends Record> AuditoriaOds05(Table<O> path, ForeignKey<O, AuditoriaOds05Record> childPath, InverseForeignKey<O, AuditoriaOds05Record> parentPath) {
        super(path, childPath, parentPath, AUDITORIA_ODS05);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuditoriaOds05Path extends AuditoriaOds05 implements Path<AuditoriaOds05Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuditoriaOds05Path(Table<O> path, ForeignKey<O, AuditoriaOds05Record> childPath, InverseForeignKey<O, AuditoriaOds05Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuditoriaOds05Path(Name alias, Table<AuditoriaOds05Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuditoriaOds05Path as(String alias) {
            return new AuditoriaOds05Path(DSL.name(alias), this);
        }

        @Override
        public AuditoriaOds05Path as(Name alias) {
            return new AuditoriaOds05Path(alias, this);
        }

        @Override
        public AuditoriaOds05Path as(Table<?> alias) {
            return new AuditoriaOds05Path(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ods05.ODS05;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUDITORIA_ODS05_IDX_AUDITORIA_FECHA_TABLA, Indexes.AUDITORIA_ODS05_IDX_FECHA, Indexes.AUDITORIA_ODS05_IDX_TABLA_REGISTRO, Indexes.AUDITORIA_ODS05_USUARIO_ID);
    }

    @Override
    public Identity<AuditoriaOds05Record, Integer> getIdentity() {
        return (Identity<AuditoriaOds05Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuditoriaOds05Record> getPrimaryKey() {
        return Keys.KEY_AUDITORIA_ODS05_PRIMARY;
    }

    @Override
    public List<ForeignKey<AuditoriaOds05Record, ?>> getReferences() {
        return Arrays.asList(Keys.AUDITORIA_ODS05_IBFK_1);
    }

    private transient UsuariosPath _usuarios;

    /**
     * Get the implicit join path to the <code>ods_login.usuarios</code> table.
     */
    public UsuariosPath usuarios() {
        if (_usuarios == null)
            _usuarios = new UsuariosPath(this, Keys.AUDITORIA_ODS05_IBFK_1, null);

        return _usuarios;
    }

    @Override
    public List<Check<AuditoriaOds05Record>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("valores_anteriores"), "json_valid(`valores_anteriores`)", true),
            Internal.createCheck(this, DSL.name("valores_nuevos"), "json_valid(`valores_nuevos`)", true)
        );
    }

    @Override
    public AuditoriaOds05 as(String alias) {
        return new AuditoriaOds05(DSL.name(alias), this);
    }

    @Override
    public AuditoriaOds05 as(Name alias) {
        return new AuditoriaOds05(alias, this);
    }

    @Override
    public AuditoriaOds05 as(Table<?> alias) {
        return new AuditoriaOds05(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds05 rename(String name) {
        return new AuditoriaOds05(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds05 rename(Name name) {
        return new AuditoriaOds05(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds05 rename(Table<?> name) {
        return new AuditoriaOds05(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds05 where(Condition condition) {
        return new AuditoriaOds05(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds05 where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds05 where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds05 where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds05 where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds05 where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds05 where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds05 where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds05 whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds05 whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
