/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods17.tables;


import com.odsProject.odsProject.database.jooq.ods17.Indexes;
import com.odsProject.odsProject.database.jooq.ods17.Keys;
import com.odsProject.odsProject.database.jooq.ods17.Ods17;
import com.odsProject.odsProject.database.jooq.ods17.tables.records.AuditoriaOds17Record;
import com.odsProject.odsProject.database.jooq.ods_login.tables.Usuarios.UsuariosPath;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Auditoría de cambios en el sistema ODS17
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditoriaOds17 extends TableImpl<AuditoriaOds17Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods17.auditoria_ods17</code>
     */
    public static final AuditoriaOds17 AUDITORIA_ODS17 = new AuditoriaOds17();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditoriaOds17Record> getRecordType() {
        return AuditoriaOds17Record.class;
    }

    /**
     * The column <code>ods17.auditoria_ods17.id</code>.
     */
    public final TableField<AuditoriaOds17Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ods17.auditoria_ods17.tabla_afectada</code>.
     */
    public final TableField<AuditoriaOds17Record, String> TABLA_AFECTADA = createField(DSL.name("tabla_afectada"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>ods17.auditoria_ods17.registro_id</code>.
     */
    public final TableField<AuditoriaOds17Record, Integer> REGISTRO_ID = createField(DSL.name("registro_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ods17.auditoria_ods17.accion</code>.
     */
    public final TableField<AuditoriaOds17Record, String> ACCION = createField(DSL.name("accion"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>ods17.auditoria_ods17.usuario_id</code>.
     */
    public final TableField<AuditoriaOds17Record, Integer> USUARIO_ID = createField(DSL.name("usuario_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ods17.auditoria_ods17.valores_anteriores</code>.
     */
    public final TableField<AuditoriaOds17Record, String> VALORES_ANTERIORES = createField(DSL.name("valores_anteriores"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods17.auditoria_ods17.valores_nuevos</code>.
     */
    public final TableField<AuditoriaOds17Record, String> VALORES_NUEVOS = createField(DSL.name("valores_nuevos"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods17.auditoria_ods17.fecha_cambio</code>.
     */
    public final TableField<AuditoriaOds17Record, LocalDateTime> FECHA_CAMBIO = createField(DSL.name("fecha_cambio"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>ods17.auditoria_ods17.ip_address</code>.
     */
    public final TableField<AuditoriaOds17Record, String> IP_ADDRESS = createField(DSL.name("ip_address"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private AuditoriaOds17(Name alias, Table<AuditoriaOds17Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuditoriaOds17(Name alias, Table<AuditoriaOds17Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Auditoría de cambios en el sistema ODS17"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ods17.auditoria_ods17</code> table reference
     */
    public AuditoriaOds17(String alias) {
        this(DSL.name(alias), AUDITORIA_ODS17);
    }

    /**
     * Create an aliased <code>ods17.auditoria_ods17</code> table reference
     */
    public AuditoriaOds17(Name alias) {
        this(alias, AUDITORIA_ODS17);
    }

    /**
     * Create a <code>ods17.auditoria_ods17</code> table reference
     */
    public AuditoriaOds17() {
        this(DSL.name("auditoria_ods17"), null);
    }

    public <O extends Record> AuditoriaOds17(Table<O> path, ForeignKey<O, AuditoriaOds17Record> childPath, InverseForeignKey<O, AuditoriaOds17Record> parentPath) {
        super(path, childPath, parentPath, AUDITORIA_ODS17);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuditoriaOds17Path extends AuditoriaOds17 implements Path<AuditoriaOds17Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuditoriaOds17Path(Table<O> path, ForeignKey<O, AuditoriaOds17Record> childPath, InverseForeignKey<O, AuditoriaOds17Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuditoriaOds17Path(Name alias, Table<AuditoriaOds17Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuditoriaOds17Path as(String alias) {
            return new AuditoriaOds17Path(DSL.name(alias), this);
        }

        @Override
        public AuditoriaOds17Path as(Name alias) {
            return new AuditoriaOds17Path(alias, this);
        }

        @Override
        public AuditoriaOds17Path as(Table<?> alias) {
            return new AuditoriaOds17Path(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ods17.ODS17;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUDITORIA_ODS17_IDX_AUDITORIA_FECHA_TABLA, Indexes.AUDITORIA_ODS17_IDX_FECHA, Indexes.AUDITORIA_ODS17_IDX_TABLA_REGISTRO, Indexes.AUDITORIA_ODS17_USUARIO_ID);
    }

    @Override
    public Identity<AuditoriaOds17Record, Integer> getIdentity() {
        return (Identity<AuditoriaOds17Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuditoriaOds17Record> getPrimaryKey() {
        return Keys.KEY_AUDITORIA_ODS17_PRIMARY;
    }

    @Override
    public List<ForeignKey<AuditoriaOds17Record, ?>> getReferences() {
        return Arrays.asList(Keys.AUDITORIA_ODS17_IBFK_1);
    }

    private transient UsuariosPath _usuarios;

    /**
     * Get the implicit join path to the <code>ods_login.usuarios</code> table.
     */
    public UsuariosPath usuarios() {
        if (_usuarios == null)
            _usuarios = new UsuariosPath(this, Keys.AUDITORIA_ODS17_IBFK_1, null);

        return _usuarios;
    }

    @Override
    public List<Check<AuditoriaOds17Record>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("valores_anteriores"), "json_valid(`valores_anteriores`)", true),
            Internal.createCheck(this, DSL.name("valores_nuevos"), "json_valid(`valores_nuevos`)", true)
        );
    }

    @Override
    public AuditoriaOds17 as(String alias) {
        return new AuditoriaOds17(DSL.name(alias), this);
    }

    @Override
    public AuditoriaOds17 as(Name alias) {
        return new AuditoriaOds17(alias, this);
    }

    @Override
    public AuditoriaOds17 as(Table<?> alias) {
        return new AuditoriaOds17(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds17 rename(String name) {
        return new AuditoriaOds17(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds17 rename(Name name) {
        return new AuditoriaOds17(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds17 rename(Table<?> name) {
        return new AuditoriaOds17(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds17 where(Condition condition) {
        return new AuditoriaOds17(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds17 where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds17 where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds17 where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds17 where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds17 where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds17 where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds17 where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds17 whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds17 whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
