/*
 * This file is generated by jOOQ.
 */
package odsProject.database.jooq.ods17.tables;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import odsProject.database.jooq.ods17.Indexes;
import odsProject.database.jooq.ods17.Keys;
import odsProject.database.jooq.ods17.Ods17;
import odsProject.database.jooq.ods17.tables.Proyectos.ProyectosPath;
import odsProject.database.jooq.ods17.tables.records.MetasProyectoRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Metas específicas establecidas por cada proyecto ODS17
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MetasProyecto extends TableImpl<MetasProyectoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods17.metas_proyecto</code>
     */
    public static final MetasProyecto METAS_PROYECTO = new MetasProyecto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MetasProyectoRecord> getRecordType() {
        return MetasProyectoRecord.class;
    }

    /**
     * The column <code>ods17.metas_proyecto.id</code>.
     */
    public final TableField<MetasProyectoRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ods17.metas_proyecto.proyecto_id</code>.
     */
    public final TableField<MetasProyectoRecord, Integer> PROYECTO_ID = createField(DSL.name("proyecto_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ods17.metas_proyecto.meta_codigo</code>.
     */
    public final TableField<MetasProyectoRecord, String> META_CODIGO = createField(DSL.name("meta_codigo"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>ods17.metas_proyecto.meta_descripcion</code>.
     */
    public final TableField<MetasProyectoRecord, String> META_DESCRIPCION = createField(DSL.name("meta_descripcion"), SQLDataType.CLOB(65535).nullable(false), this, "");

    /**
     * The column <code>ods17.metas_proyecto.valor_meta</code>.
     */
    public final TableField<MetasProyectoRecord, BigDecimal> VALOR_META = createField(DSL.name("valor_meta"), SQLDataType.DECIMAL(15, 4).nullable(false), this, "");

    /**
     * The column <code>ods17.metas_proyecto.unidad_medida</code>.
     */
    public final TableField<MetasProyectoRecord, String> UNIDAD_MEDIDA = createField(DSL.name("unidad_medida"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>ods17.metas_proyecto.fecha_limite</code>.
     */
    public final TableField<MetasProyectoRecord, LocalDate> FECHA_LIMITE = createField(DSL.name("fecha_limite"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>ods17.metas_proyecto.created_at</code>.
     */
    public final TableField<MetasProyectoRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    private MetasProyecto(Name alias, Table<MetasProyectoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MetasProyecto(Name alias, Table<MetasProyectoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Metas específicas establecidas por cada proyecto ODS17"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ods17.metas_proyecto</code> table reference
     */
    public MetasProyecto(String alias) {
        this(DSL.name(alias), METAS_PROYECTO);
    }

    /**
     * Create an aliased <code>ods17.metas_proyecto</code> table reference
     */
    public MetasProyecto(Name alias) {
        this(alias, METAS_PROYECTO);
    }

    /**
     * Create a <code>ods17.metas_proyecto</code> table reference
     */
    public MetasProyecto() {
        this(DSL.name("metas_proyecto"), null);
    }

    public <O extends Record> MetasProyecto(Table<O> path, ForeignKey<O, MetasProyectoRecord> childPath, InverseForeignKey<O, MetasProyectoRecord> parentPath) {
        super(path, childPath, parentPath, METAS_PROYECTO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MetasProyectoPath extends MetasProyecto implements Path<MetasProyectoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MetasProyectoPath(Table<O> path, ForeignKey<O, MetasProyectoRecord> childPath, InverseForeignKey<O, MetasProyectoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MetasProyectoPath(Name alias, Table<MetasProyectoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MetasProyectoPath as(String alias) {
            return new MetasProyectoPath(DSL.name(alias), this);
        }

        @Override
        public MetasProyectoPath as(Name alias) {
            return new MetasProyectoPath(alias, this);
        }

        @Override
        public MetasProyectoPath as(Table<?> alias) {
            return new MetasProyectoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ods17.ODS17;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.METAS_PROYECTO_IDX_PROYECTO_META);
    }

    @Override
    public Identity<MetasProyectoRecord, Integer> getIdentity() {
        return (Identity<MetasProyectoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MetasProyectoRecord> getPrimaryKey() {
        return Keys.KEY_METAS_PROYECTO_PRIMARY;
    }

    @Override
    public List<ForeignKey<MetasProyectoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.METAS_PROYECTO_IBFK_1);
    }

    private transient ProyectosPath _proyectos;

    /**
     * Get the implicit join path to the <code>ods17.proyectos</code> table.
     */
    public ProyectosPath proyectos() {
        if (_proyectos == null)
            _proyectos = new ProyectosPath(this, Keys.METAS_PROYECTO_IBFK_1, null);

        return _proyectos;
    }

    @Override
    public MetasProyecto as(String alias) {
        return new MetasProyecto(DSL.name(alias), this);
    }

    @Override
    public MetasProyecto as(Name alias) {
        return new MetasProyecto(alias, this);
    }

    @Override
    public MetasProyecto as(Table<?> alias) {
        return new MetasProyecto(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MetasProyecto rename(String name) {
        return new MetasProyecto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MetasProyecto rename(Name name) {
        return new MetasProyecto(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MetasProyecto rename(Table<?> name) {
        return new MetasProyecto(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MetasProyecto where(Condition condition) {
        return new MetasProyecto(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MetasProyecto where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MetasProyecto where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MetasProyecto where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MetasProyecto where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MetasProyecto where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MetasProyecto where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MetasProyecto where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MetasProyecto whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MetasProyecto whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
