/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods17.tables.records;


import com.odsProject.odsProject.database.jooq.ods17.enums.VistaAdminResumenGeneralEstado;
import com.odsProject.odsProject.database.jooq.ods17.tables.VistaAdminResumenGeneral;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAdminResumenGeneralRecord extends TableRecordImpl<VistaAdminResumenGeneralRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ods17.vista_admin_resumen_general.proyecto_id</code>.
     */
    public void setProyectoId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ods17.vista_admin_resumen_general.proyecto_id</code>.
     */
    public Integer getProyectoId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>ods17.vista_admin_resumen_general.nombre_proyecto</code>.
     */
    public void setNombreProyecto(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>ods17.vista_admin_resumen_general.nombre_proyecto</code>.
     */
    public String getNombreProyecto() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>ods17.vista_admin_resumen_general.usuario_creador</code>.
     */
    public void setUsuarioCreador(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>ods17.vista_admin_resumen_general.usuario_creador</code>.
     */
    public String getUsuarioCreador() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ods17.vista_admin_resumen_general.sede_nombre</code>.
     */
    public void setSedeNombre(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ods17.vista_admin_resumen_general.sede_nombre</code>.
     */
    public String getSedeNombre() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ods17.vista_admin_resumen_general.ods_nombre</code>.
     */
    public void setOdsNombre(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ods17.vista_admin_resumen_general.ods_nombre</code>.
     */
    public String getOdsNombre() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ods17.vista_admin_resumen_general.fecha_inicio</code>.
     */
    public void setFechaInicio(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>ods17.vista_admin_resumen_general.fecha_inicio</code>.
     */
    public LocalDate getFechaInicio() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>ods17.vista_admin_resumen_general.fecha_fin</code>.
     */
    public void setFechaFin(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>ods17.vista_admin_resumen_general.fecha_fin</code>.
     */
    public LocalDate getFechaFin() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>ods17.vista_admin_resumen_general.estado</code>.
     */
    public void setEstado(VistaAdminResumenGeneralEstado value) {
        set(7, value);
    }

    /**
     * Getter for <code>ods17.vista_admin_resumen_general.estado</code>.
     */
    public VistaAdminResumenGeneralEstado getEstado() {
        return (VistaAdminResumenGeneralEstado) get(7);
    }

    /**
     * Setter for
     * <code>ods17.vista_admin_resumen_general.total_indicadores</code>.
     */
    public void setTotalIndicadores(Long value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>ods17.vista_admin_resumen_general.total_indicadores</code>.
     */
    public Long getTotalIndicadores() {
        return (Long) get(8);
    }

    /**
     * Setter for
     * <code>ods17.vista_admin_resumen_general.indicadores_logrados</code>.
     */
    public void setIndicadoresLogrados(Long value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>ods17.vista_admin_resumen_general.indicadores_logrados</code>.
     */
    public Long getIndicadoresLogrados() {
        return (Long) get(9);
    }

    /**
     * Setter for
     * <code>ods17.vista_admin_resumen_general.progreso_porcentaje</code>.
     */
    public void setProgresoPorcentaje(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>ods17.vista_admin_resumen_general.progreso_porcentaje</code>.
     */
    public BigDecimal getProgresoPorcentaje() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>ods17.vista_admin_resumen_general.fecha_creacion</code>.
     */
    public void setFechaCreacion(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>ods17.vista_admin_resumen_general.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaAdminResumenGeneralRecord
     */
    public VistaAdminResumenGeneralRecord() {
        super(VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL);
    }

    /**
     * Create a detached, initialised VistaAdminResumenGeneralRecord
     */
    public VistaAdminResumenGeneralRecord(Integer proyectoId, String nombreProyecto, String usuarioCreador, String sedeNombre, String odsNombre, LocalDate fechaInicio, LocalDate fechaFin, VistaAdminResumenGeneralEstado estado, Long totalIndicadores, Long indicadoresLogrados, BigDecimal progresoPorcentaje, LocalDateTime fechaCreacion) {
        super(VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL);

        setProyectoId(proyectoId);
        setNombreProyecto(nombreProyecto);
        setUsuarioCreador(usuarioCreador);
        setSedeNombre(sedeNombre);
        setOdsNombre(odsNombre);
        setFechaInicio(fechaInicio);
        setFechaFin(fechaFin);
        setEstado(estado);
        setTotalIndicadores(totalIndicadores);
        setIndicadoresLogrados(indicadoresLogrados);
        setProgresoPorcentaje(progresoPorcentaje);
        setFechaCreacion(fechaCreacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaAdminResumenGeneralRecord
     */
    public VistaAdminResumenGeneralRecord(com.odsProject.odsProject.database.jooq.ods17.tables.pojos.VistaAdminResumenGeneral value) {
        super(VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL);

        if (value != null) {
            setProyectoId(value.getProyectoId());
            setNombreProyecto(value.getNombreProyecto());
            setUsuarioCreador(value.getUsuarioCreador());
            setSedeNombre(value.getSedeNombre());
            setOdsNombre(value.getOdsNombre());
            setFechaInicio(value.getFechaInicio());
            setFechaFin(value.getFechaFin());
            setEstado(value.getEstado());
            setTotalIndicadores(value.getTotalIndicadores());
            setIndicadoresLogrados(value.getIndicadoresLogrados());
            setProgresoPorcentaje(value.getProgresoPorcentaje());
            setFechaCreacion(value.getFechaCreacion());
            resetChangedOnNotNull();
        }
    }
}
