/*
 * This file is generated by jOOQ.
 */
package database.jooq.ods03;


import database.jooq.DefaultCatalog;
import database.jooq.ods03.tables.AuditoriaOds03;
import database.jooq.ods03.tables.Indicadores;
import database.jooq.ods03.tables.MedicionesHistoricas;
import database.jooq.ods03.tables.MetasProyecto;
import database.jooq.ods03.tables.Proyectos;
import database.jooq.ods03.tables.VistaAdminAuditoriaReciente;
import database.jooq.ods03.tables.VistaAdminDetalleIndicadores;
import database.jooq.ods03.tables.VistaAdminEstadisticasGenerales;
import database.jooq.ods03.tables.VistaAdminResumenGeneral;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ods03 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods03</code>
     */
    public static final Ods03 ODS03 = new Ods03();

    /**
     * Auditoría de cambios en el sistema ODS03
     */
    public final AuditoriaOds03 AUDITORIA_ODS03 = AuditoriaOds03.AUDITORIA_ODS03;

    /**
     * Indicadores medidos por cada proyecto ODS03
     */
    public final Indicadores INDICADORES = Indicadores.INDICADORES;

    /**
     * Historial de mediciones de indicadores ODS03
     */
    public final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * Metas específicas establecidas por cada proyecto ODS03
     */
    public final MetasProyecto METAS_PROYECTO = MetasProyecto.METAS_PROYECTO;

    /**
     * Proyectos ODS03 creados por usuarios
     */
    public final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * The table <code>ods03.vista_admin_auditoria_reciente</code>.
     */
    public final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * The table <code>ods03.vista_admin_detalle_indicadores</code>.
     */
    public final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * The table <code>ods03.vista_admin_estadisticas_generales</code>.
     */
    public final VistaAdminEstadisticasGenerales VISTA_ADMIN_ESTADISTICAS_GENERALES = VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES;

    /**
     * The table <code>ods03.vista_admin_resumen_general</code>.
     */
    public final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;

    /**
     * No further instances allowed
     */
    private Ods03() {
        super("ods03", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuditoriaOds03.AUDITORIA_ODS03,
            Indicadores.INDICADORES,
            MedicionesHistoricas.MEDICIONES_HISTORICAS,
            MetasProyecto.METAS_PROYECTO,
            Proyectos.PROYECTOS,
            VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE,
            VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES,
            VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES,
            VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL
        );
    }
}
