/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.pojos;


import com.odsProject.odsProject.database.jooq.ods_login.enums.IndicadorParametrosMasterTipoDato;

import java.io.Serializable;


/**
 * Parámetros necesarios para las fórmulas maestras
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndicadorParametrosMaster implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer indicadorId;
    private String nombreParametro;
    private String descripcionParam;
    private IndicadorParametrosMasterTipoDato tipoDato;

    public IndicadorParametrosMaster() {}

    public IndicadorParametrosMaster(IndicadorParametrosMaster value) {
        this.id = value.id;
        this.indicadorId = value.indicadorId;
        this.nombreParametro = value.nombreParametro;
        this.descripcionParam = value.descripcionParam;
        this.tipoDato = value.tipoDato;
    }

    public IndicadorParametrosMaster(
        Integer id,
        Integer indicadorId,
        String nombreParametro,
        String descripcionParam,
        IndicadorParametrosMasterTipoDato tipoDato
    ) {
        this.id = id;
        this.indicadorId = indicadorId;
        this.nombreParametro = nombreParametro;
        this.descripcionParam = descripcionParam;
        this.tipoDato = tipoDato;
    }

    /**
     * Getter for <code>ods_login.indicador_parametros_master.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ods_login.indicador_parametros_master.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>ods_login.indicador_parametros_master.indicador_id</code>.
     */
    public Integer getIndicadorId() {
        return this.indicadorId;
    }

    /**
     * Setter for
     * <code>ods_login.indicador_parametros_master.indicador_id</code>.
     */
    public void setIndicadorId(Integer indicadorId) {
        this.indicadorId = indicadorId;
    }

    /**
     * Getter for
     * <code>ods_login.indicador_parametros_master.nombre_parametro</code>.
     */
    public String getNombreParametro() {
        return this.nombreParametro;
    }

    /**
     * Setter for
     * <code>ods_login.indicador_parametros_master.nombre_parametro</code>.
     */
    public void setNombreParametro(String nombreParametro) {
        this.nombreParametro = nombreParametro;
    }

    /**
     * Getter for
     * <code>ods_login.indicador_parametros_master.descripcion_param</code>.
     */
    public String getDescripcionParam() {
        return this.descripcionParam;
    }

    /**
     * Setter for
     * <code>ods_login.indicador_parametros_master.descripcion_param</code>.
     */
    public void setDescripcionParam(String descripcionParam) {
        this.descripcionParam = descripcionParam;
    }

    /**
     * Getter for <code>ods_login.indicador_parametros_master.tipo_dato</code>.
     */
    public IndicadorParametrosMasterTipoDato getTipoDato() {
        return this.tipoDato;
    }

    /**
     * Setter for <code>ods_login.indicador_parametros_master.tipo_dato</code>.
     */
    public void setTipoDato(IndicadorParametrosMasterTipoDato tipoDato) {
        this.tipoDato = tipoDato;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final IndicadorParametrosMaster other = (IndicadorParametrosMaster) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.indicadorId == null) {
            if (other.indicadorId != null)
                return false;
        }
        else if (!this.indicadorId.equals(other.indicadorId))
            return false;
        if (this.nombreParametro == null) {
            if (other.nombreParametro != null)
                return false;
        }
        else if (!this.nombreParametro.equals(other.nombreParametro))
            return false;
        if (this.descripcionParam == null) {
            if (other.descripcionParam != null)
                return false;
        }
        else if (!this.descripcionParam.equals(other.descripcionParam))
            return false;
        if (this.tipoDato == null) {
            if (other.tipoDato != null)
                return false;
        }
        else if (!this.tipoDato.equals(other.tipoDato))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.indicadorId == null) ? 0 : this.indicadorId.hashCode());
        result = prime * result + ((this.nombreParametro == null) ? 0 : this.nombreParametro.hashCode());
        result = prime * result + ((this.descripcionParam == null) ? 0 : this.descripcionParam.hashCode());
        result = prime * result + ((this.tipoDato == null) ? 0 : this.tipoDato.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IndicadorParametrosMaster (");

        sb.append(id);
        sb.append(", ").append(indicadorId);
        sb.append(", ").append(nombreParametro);
        sb.append(", ").append(descripcionParam);
        sb.append(", ").append(tipoDato);

        sb.append(")");
        return sb.toString();
    }
}
