/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UByte;


/**
 * Catálogo central de los 17 ODS
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OdsCatalog implements Serializable {

    private static final long serialVersionUID = 1L;

    private UByte id;
    private String nombre;
    private String descripcion;
    private String colorHex;
    private String iconoUrl;
    private LocalDateTime createdAt;

    public OdsCatalog() {}

    public OdsCatalog(OdsCatalog value) {
        this.id = value.id;
        this.nombre = value.nombre;
        this.descripcion = value.descripcion;
        this.colorHex = value.colorHex;
        this.iconoUrl = value.iconoUrl;
        this.createdAt = value.createdAt;
    }

    public OdsCatalog(
        UByte id,
        String nombre,
        String descripcion,
        String colorHex,
        String iconoUrl,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.colorHex = colorHex;
        this.iconoUrl = iconoUrl;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>ods_login.ods_catalog.id</code>.
     */
    public UByte getId() {
        return this.id;
    }

    /**
     * Setter for <code>ods_login.ods_catalog.id</code>.
     */
    public void setId(UByte id) {
        this.id = id;
    }

    /**
     * Getter for <code>ods_login.ods_catalog.nombre</code>.
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Setter for <code>ods_login.ods_catalog.nombre</code>.
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * Getter for <code>ods_login.ods_catalog.descripcion</code>.
     */
    public String getDescripcion() {
        return this.descripcion;
    }

    /**
     * Setter for <code>ods_login.ods_catalog.descripcion</code>.
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * Getter for <code>ods_login.ods_catalog.color_hex</code>.
     */
    public String getColorHex() {
        return this.colorHex;
    }

    /**
     * Setter for <code>ods_login.ods_catalog.color_hex</code>.
     */
    public void setColorHex(String colorHex) {
        this.colorHex = colorHex;
    }

    /**
     * Getter for <code>ods_login.ods_catalog.icono_url</code>.
     */
    public String getIconoUrl() {
        return this.iconoUrl;
    }

    /**
     * Setter for <code>ods_login.ods_catalog.icono_url</code>.
     */
    public void setIconoUrl(String iconoUrl) {
        this.iconoUrl = iconoUrl;
    }

    /**
     * Getter for <code>ods_login.ods_catalog.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>ods_login.ods_catalog.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OdsCatalog other = (OdsCatalog) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.nombre == null) {
            if (other.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(other.nombre))
            return false;
        if (this.descripcion == null) {
            if (other.descripcion != null)
                return false;
        }
        else if (!this.descripcion.equals(other.descripcion))
            return false;
        if (this.colorHex == null) {
            if (other.colorHex != null)
                return false;
        }
        else if (!this.colorHex.equals(other.colorHex))
            return false;
        if (this.iconoUrl == null) {
            if (other.iconoUrl != null)
                return false;
        }
        else if (!this.iconoUrl.equals(other.iconoUrl))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.nombre == null) ? 0 : this.nombre.hashCode());
        result = prime * result + ((this.descripcion == null) ? 0 : this.descripcion.hashCode());
        result = prime * result + ((this.colorHex == null) ? 0 : this.colorHex.hashCode());
        result = prime * result + ((this.iconoUrl == null) ? 0 : this.iconoUrl.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OdsCatalog (");

        sb.append(id);
        sb.append(", ").append(nombre);
        sb.append(", ").append(descripcion);
        sb.append(", ").append(colorHex);
        sb.append(", ").append(iconoUrl);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
