/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UByte;


/**
 * Qué ODS puede gestionar cada usuario
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PermisosOds implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer usuarioId;
    private UByte odsNum;
    private Byte puedeCrear;
    private Byte puedeEditar;
    private Byte puedeVer;
    private LocalDateTime createdAt;

    public PermisosOds() {}

    public PermisosOds(PermisosOds value) {
        this.id = value.id;
        this.usuarioId = value.usuarioId;
        this.odsNum = value.odsNum;
        this.puedeCrear = value.puedeCrear;
        this.puedeEditar = value.puedeEditar;
        this.puedeVer = value.puedeVer;
        this.createdAt = value.createdAt;
    }

    public PermisosOds(
        Integer id,
        Integer usuarioId,
        UByte odsNum,
        Byte puedeCrear,
        Byte puedeEditar,
        Byte puedeVer,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.usuarioId = usuarioId;
        this.odsNum = odsNum;
        this.puedeCrear = puedeCrear;
        this.puedeEditar = puedeEditar;
        this.puedeVer = puedeVer;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ods_login.permisos_ods.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.usuario_id</code>.
     */
    public Integer getUsuarioId() {
        return this.usuarioId;
    }

    /**
     * Setter for <code>ods_login.permisos_ods.usuario_id</code>.
     */
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.ods_num</code>.
     */
    public UByte getOdsNum() {
        return this.odsNum;
    }

    /**
     * Setter for <code>ods_login.permisos_ods.ods_num</code>.
     */
    public void setOdsNum(UByte odsNum) {
        this.odsNum = odsNum;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.puede_crear</code>.
     */
    public Byte getPuedeCrear() {
        return this.puedeCrear;
    }

    /**
     * Setter for <code>ods_login.permisos_ods.puede_crear</code>.
     */
    public void setPuedeCrear(Byte puedeCrear) {
        this.puedeCrear = puedeCrear;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.puede_editar</code>.
     */
    public Byte getPuedeEditar() {
        return this.puedeEditar;
    }

    /**
     * Setter for <code>ods_login.permisos_ods.puede_editar</code>.
     */
    public void setPuedeEditar(Byte puedeEditar) {
        this.puedeEditar = puedeEditar;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.puede_ver</code>.
     */
    public Byte getPuedeVer() {
        return this.puedeVer;
    }

    /**
     * Setter for <code>ods_login.permisos_ods.puede_ver</code>.
     */
    public void setPuedeVer(Byte puedeVer) {
        this.puedeVer = puedeVer;
    }

    /**
     * Getter for <code>ods_login.permisos_ods.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>ods_login.permisos_ods.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PermisosOds other = (PermisosOds) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.usuarioId == null) {
            if (other.usuarioId != null)
                return false;
        }
        else if (!this.usuarioId.equals(other.usuarioId))
            return false;
        if (this.odsNum == null) {
            if (other.odsNum != null)
                return false;
        }
        else if (!this.odsNum.equals(other.odsNum))
            return false;
        if (this.puedeCrear == null) {
            if (other.puedeCrear != null)
                return false;
        }
        else if (!this.puedeCrear.equals(other.puedeCrear))
            return false;
        if (this.puedeEditar == null) {
            if (other.puedeEditar != null)
                return false;
        }
        else if (!this.puedeEditar.equals(other.puedeEditar))
            return false;
        if (this.puedeVer == null) {
            if (other.puedeVer != null)
                return false;
        }
        else if (!this.puedeVer.equals(other.puedeVer))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.usuarioId == null) ? 0 : this.usuarioId.hashCode());
        result = prime * result + ((this.odsNum == null) ? 0 : this.odsNum.hashCode());
        result = prime * result + ((this.puedeCrear == null) ? 0 : this.puedeCrear.hashCode());
        result = prime * result + ((this.puedeEditar == null) ? 0 : this.puedeEditar.hashCode());
        result = prime * result + ((this.puedeVer == null) ? 0 : this.puedeVer.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PermisosOds (");

        sb.append(id);
        sb.append(", ").append(usuarioId);
        sb.append(", ").append(odsNum);
        sb.append(", ").append(puedeCrear);
        sb.append(", ").append(puedeEditar);
        sb.append(", ").append(puedeVer);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
