/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SodsiBeneficiarioCategoria implements Serializable {

    private static final long serialVersionUID = 1L;

    private UByte id;
    private String codigo;
    private String nombre;
    private Byte esNa;
    private UByte orden;

    public SodsiBeneficiarioCategoria() {}

    public SodsiBeneficiarioCategoria(SodsiBeneficiarioCategoria value) {
        this.id = value.id;
        this.codigo = value.codigo;
        this.nombre = value.nombre;
        this.esNa = value.esNa;
        this.orden = value.orden;
    }

    public SodsiBeneficiarioCategoria(
        UByte id,
        String codigo,
        String nombre,
        Byte esNa,
        UByte orden
    ) {
        this.id = id;
        this.codigo = codigo;
        this.nombre = nombre;
        this.esNa = esNa;
        this.orden = orden;
    }

    /**
     * Getter for <code>ods_login.sodsi_beneficiario_categoria.id</code>.
     */
    public UByte getId() {
        return this.id;
    }

    /**
     * Setter for <code>ods_login.sodsi_beneficiario_categoria.id</code>.
     */
    public SodsiBeneficiarioCategoria setId(UByte id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_beneficiario_categoria.codigo</code>.
     */
    public String getCodigo() {
        return this.codigo;
    }

    /**
     * Setter for <code>ods_login.sodsi_beneficiario_categoria.codigo</code>.
     */
    public SodsiBeneficiarioCategoria setCodigo(String codigo) {
        this.codigo = codigo;
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_beneficiario_categoria.nombre</code>.
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Setter for <code>ods_login.sodsi_beneficiario_categoria.nombre</code>.
     */
    public SodsiBeneficiarioCategoria setNombre(String nombre) {
        this.nombre = nombre;
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_beneficiario_categoria.es_na</code>.
     */
    public Byte getEsNa() {
        return this.esNa;
    }

    /**
     * Setter for <code>ods_login.sodsi_beneficiario_categoria.es_na</code>.
     */
    public SodsiBeneficiarioCategoria setEsNa(Byte esNa) {
        this.esNa = esNa;
        return this;
    }

    /**
     * Getter for <code>ods_login.sodsi_beneficiario_categoria.orden</code>.
     */
    public UByte getOrden() {
        return this.orden;
    }

    /**
     * Setter for <code>ods_login.sodsi_beneficiario_categoria.orden</code>.
     */
    public SodsiBeneficiarioCategoria setOrden(UByte orden) {
        this.orden = orden;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SodsiBeneficiarioCategoria other = (SodsiBeneficiarioCategoria) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.codigo == null) {
            if (other.codigo != null)
                return false;
        }
        else if (!this.codigo.equals(other.codigo))
            return false;
        if (this.nombre == null) {
            if (other.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(other.nombre))
            return false;
        if (this.esNa == null) {
            if (other.esNa != null)
                return false;
        }
        else if (!this.esNa.equals(other.esNa))
            return false;
        if (this.orden == null) {
            if (other.orden != null)
                return false;
        }
        else if (!this.orden.equals(other.orden))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.codigo == null) ? 0 : this.codigo.hashCode());
        result = prime * result + ((this.nombre == null) ? 0 : this.nombre.hashCode());
        result = prime * result + ((this.esNa == null) ? 0 : this.esNa.hashCode());
        result = prime * result + ((this.orden == null) ? 0 : this.orden.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SodsiBeneficiarioCategoria (");

        sb.append(id);
        sb.append(", ").append(codigo);
        sb.append(", ").append(nombre);
        sb.append(", ").append(esNa);
        sb.append(", ").append(orden);

        sb.append(")");
        return sb.toString();
    }
}
