/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UByte;


/**
 * Usuarios centrales; referenciados por todas las bases ods_XX
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Usuarios implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String username;
    private String email;
    private String passwordHash;
    private String fullName;
    private Integer rolId;
    private Integer sedeId;
    private Byte isActive;
    private Byte emailVerificado;
    private LocalDateTime ultimoLogin;
    private UByte intentosFallidos;
    private LocalDateTime bloqueadoHasta;
    private String tokenRecuperacion;
    private LocalDateTime tokenExpira;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Usuarios() {}

    public Usuarios(Usuarios value) {
        this.id = value.id;
        this.username = value.username;
        this.email = value.email;
        this.passwordHash = value.passwordHash;
        this.fullName = value.fullName;
        this.rolId = value.rolId;
        this.sedeId = value.sedeId;
        this.isActive = value.isActive;
        this.emailVerificado = value.emailVerificado;
        this.ultimoLogin = value.ultimoLogin;
        this.intentosFallidos = value.intentosFallidos;
        this.bloqueadoHasta = value.bloqueadoHasta;
        this.tokenRecuperacion = value.tokenRecuperacion;
        this.tokenExpira = value.tokenExpira;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Usuarios(
        Integer id,
        String username,
        String email,
        String passwordHash,
        String fullName,
        Integer rolId,
        Integer sedeId,
        Byte isActive,
        Byte emailVerificado,
        LocalDateTime ultimoLogin,
        UByte intentosFallidos,
        LocalDateTime bloqueadoHasta,
        String tokenRecuperacion,
        LocalDateTime tokenExpira,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.passwordHash = passwordHash;
        this.fullName = fullName;
        this.rolId = rolId;
        this.sedeId = sedeId;
        this.isActive = isActive;
        this.emailVerificado = emailVerificado;
        this.ultimoLogin = ultimoLogin;
        this.intentosFallidos = intentosFallidos;
        this.bloqueadoHasta = bloqueadoHasta;
        this.tokenRecuperacion = tokenRecuperacion;
        this.tokenExpira = tokenExpira;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>ods_login.usuarios.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ods_login.usuarios.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>ods_login.usuarios.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>ods_login.usuarios.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>ods_login.usuarios.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>ods_login.usuarios.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>ods_login.usuarios.password_hash</code>.
     */
    public String getPasswordHash() {
        return this.passwordHash;
    }

    /**
     * Setter for <code>ods_login.usuarios.password_hash</code>.
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * Getter for <code>ods_login.usuarios.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>ods_login.usuarios.full_name</code>.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for <code>ods_login.usuarios.rol_id</code>.
     */
    public Integer getRolId() {
        return this.rolId;
    }

    /**
     * Setter for <code>ods_login.usuarios.rol_id</code>.
     */
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }

    /**
     * Getter for <code>ods_login.usuarios.sede_id</code>.
     */
    public Integer getSedeId() {
        return this.sedeId;
    }

    /**
     * Setter for <code>ods_login.usuarios.sede_id</code>.
     */
    public void setSedeId(Integer sedeId) {
        this.sedeId = sedeId;
    }

    /**
     * Getter for <code>ods_login.usuarios.is_active</code>.
     */
    public Byte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>ods_login.usuarios.is_active</code>.
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * Getter for <code>ods_login.usuarios.email_verificado</code>.
     */
    public Byte getEmailVerificado() {
        return this.emailVerificado;
    }

    /**
     * Setter for <code>ods_login.usuarios.email_verificado</code>.
     */
    public void setEmailVerificado(Byte emailVerificado) {
        this.emailVerificado = emailVerificado;
    }

    /**
     * Getter for <code>ods_login.usuarios.ultimo_login</code>.
     */
    public LocalDateTime getUltimoLogin() {
        return this.ultimoLogin;
    }

    /**
     * Setter for <code>ods_login.usuarios.ultimo_login</code>.
     */
    public void setUltimoLogin(LocalDateTime ultimoLogin) {
        this.ultimoLogin = ultimoLogin;
    }

    /**
     * Getter for <code>ods_login.usuarios.intentos_fallidos</code>.
     */
    public UByte getIntentosFallidos() {
        return this.intentosFallidos;
    }

    /**
     * Setter for <code>ods_login.usuarios.intentos_fallidos</code>.
     */
    public void setIntentosFallidos(UByte intentosFallidos) {
        this.intentosFallidos = intentosFallidos;
    }

    /**
     * Getter for <code>ods_login.usuarios.bloqueado_hasta</code>.
     */
    public LocalDateTime getBloqueadoHasta() {
        return this.bloqueadoHasta;
    }

    /**
     * Setter for <code>ods_login.usuarios.bloqueado_hasta</code>.
     */
    public void setBloqueadoHasta(LocalDateTime bloqueadoHasta) {
        this.bloqueadoHasta = bloqueadoHasta;
    }

    /**
     * Getter for <code>ods_login.usuarios.token_recuperacion</code>.
     */
    public String getTokenRecuperacion() {
        return this.tokenRecuperacion;
    }

    /**
     * Setter for <code>ods_login.usuarios.token_recuperacion</code>.
     */
    public void setTokenRecuperacion(String tokenRecuperacion) {
        this.tokenRecuperacion = tokenRecuperacion;
    }

    /**
     * Getter for <code>ods_login.usuarios.token_expira</code>.
     */
    public LocalDateTime getTokenExpira() {
        return this.tokenExpira;
    }

    /**
     * Setter for <code>ods_login.usuarios.token_expira</code>.
     */
    public void setTokenExpira(LocalDateTime tokenExpira) {
        this.tokenExpira = tokenExpira;
    }

    /**
     * Getter for <code>ods_login.usuarios.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>ods_login.usuarios.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>ods_login.usuarios.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>ods_login.usuarios.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Usuarios other = (Usuarios) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.passwordHash == null) {
            if (other.passwordHash != null)
                return false;
        }
        else if (!this.passwordHash.equals(other.passwordHash))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.rolId == null) {
            if (other.rolId != null)
                return false;
        }
        else if (!this.rolId.equals(other.rolId))
            return false;
        if (this.sedeId == null) {
            if (other.sedeId != null)
                return false;
        }
        else if (!this.sedeId.equals(other.sedeId))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        if (this.emailVerificado == null) {
            if (other.emailVerificado != null)
                return false;
        }
        else if (!this.emailVerificado.equals(other.emailVerificado))
            return false;
        if (this.ultimoLogin == null) {
            if (other.ultimoLogin != null)
                return false;
        }
        else if (!this.ultimoLogin.equals(other.ultimoLogin))
            return false;
        if (this.intentosFallidos == null) {
            if (other.intentosFallidos != null)
                return false;
        }
        else if (!this.intentosFallidos.equals(other.intentosFallidos))
            return false;
        if (this.bloqueadoHasta == null) {
            if (other.bloqueadoHasta != null)
                return false;
        }
        else if (!this.bloqueadoHasta.equals(other.bloqueadoHasta))
            return false;
        if (this.tokenRecuperacion == null) {
            if (other.tokenRecuperacion != null)
                return false;
        }
        else if (!this.tokenRecuperacion.equals(other.tokenRecuperacion))
            return false;
        if (this.tokenExpira == null) {
            if (other.tokenExpira != null)
                return false;
        }
        else if (!this.tokenExpira.equals(other.tokenExpira))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.passwordHash == null) ? 0 : this.passwordHash.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.rolId == null) ? 0 : this.rolId.hashCode());
        result = prime * result + ((this.sedeId == null) ? 0 : this.sedeId.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        result = prime * result + ((this.emailVerificado == null) ? 0 : this.emailVerificado.hashCode());
        result = prime * result + ((this.ultimoLogin == null) ? 0 : this.ultimoLogin.hashCode());
        result = prime * result + ((this.intentosFallidos == null) ? 0 : this.intentosFallidos.hashCode());
        result = prime * result + ((this.bloqueadoHasta == null) ? 0 : this.bloqueadoHasta.hashCode());
        result = prime * result + ((this.tokenRecuperacion == null) ? 0 : this.tokenRecuperacion.hashCode());
        result = prime * result + ((this.tokenExpira == null) ? 0 : this.tokenExpira.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Usuarios (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(email);
        sb.append(", ").append(passwordHash);
        sb.append(", ").append(fullName);
        sb.append(", ").append(rolId);
        sb.append(", ").append(sedeId);
        sb.append(", ").append(isActive);
        sb.append(", ").append(emailVerificado);
        sb.append(", ").append(ultimoLogin);
        sb.append(", ").append(intentosFallidos);
        sb.append(", ").append(bloqueadoHasta);
        sb.append(", ").append(tokenRecuperacion);
        sb.append(", ").append(tokenExpira);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
