/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.pojos;


import com.odsProject.odsProject.database.jooq.ods_login.enums.VistaAdminIntentosLoginRole;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAdminIntentosLogin implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String username;
    private final Byte success;
    private final String failureReason;
    private final String ipAddress;
    private final String userAgent;
    private final LocalDateTime createdAt;
    private final String periodo;
    private final String fullName;
    private final VistaAdminIntentosLoginRole role;

    public VistaAdminIntentosLogin(VistaAdminIntentosLogin value) {
        this.id = value.id;
        this.username = value.username;
        this.success = value.success;
        this.failureReason = value.failureReason;
        this.ipAddress = value.ipAddress;
        this.userAgent = value.userAgent;
        this.createdAt = value.createdAt;
        this.periodo = value.periodo;
        this.fullName = value.fullName;
        this.role = value.role;
    }

    public VistaAdminIntentosLogin(
        Integer id,
        String username,
        Byte success,
        String failureReason,
        String ipAddress,
        String userAgent,
        LocalDateTime createdAt,
        String periodo,
        String fullName,
        VistaAdminIntentosLoginRole role
    ) {
        this.id = id;
        this.username = username;
        this.success = success;
        this.failureReason = failureReason;
        this.ipAddress = ipAddress;
        this.userAgent = userAgent;
        this.createdAt = createdAt;
        this.periodo = periodo;
        this.fullName = fullName;
        this.role = role;
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.success</code>.
     */
    public Byte getSuccess() {
        return this.success;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_intentos_login.failure_reason</code>.
     */
    public String getFailureReason() {
        return this.failureReason;
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.ip_address</code>.
     */
    public String getIpAddress() {
        return this.ipAddress;
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.user_agent</code>.
     */
    public String getUserAgent() {
        return this.userAgent;
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.periodo</code>.
     */
    public String getPeriodo() {
        return this.periodo;
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Getter for <code>ods_login.vista_admin_intentos_login.role</code>.
     */
    public VistaAdminIntentosLoginRole getRole() {
        return this.role;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VistaAdminIntentosLogin other = (VistaAdminIntentosLogin) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.success == null) {
            if (other.success != null)
                return false;
        }
        else if (!this.success.equals(other.success))
            return false;
        if (this.failureReason == null) {
            if (other.failureReason != null)
                return false;
        }
        else if (!this.failureReason.equals(other.failureReason))
            return false;
        if (this.ipAddress == null) {
            if (other.ipAddress != null)
                return false;
        }
        else if (!this.ipAddress.equals(other.ipAddress))
            return false;
        if (this.userAgent == null) {
            if (other.userAgent != null)
                return false;
        }
        else if (!this.userAgent.equals(other.userAgent))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.periodo == null) {
            if (other.periodo != null)
                return false;
        }
        else if (!this.periodo.equals(other.periodo))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.success == null) ? 0 : this.success.hashCode());
        result = prime * result + ((this.failureReason == null) ? 0 : this.failureReason.hashCode());
        result = prime * result + ((this.ipAddress == null) ? 0 : this.ipAddress.hashCode());
        result = prime * result + ((this.userAgent == null) ? 0 : this.userAgent.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.periodo == null) ? 0 : this.periodo.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VistaAdminIntentosLogin (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(success);
        sb.append(", ").append(failureReason);
        sb.append(", ").append(ipAddress);
        sb.append(", ").append(userAgent);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(periodo);
        sb.append(", ").append(fullName);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
