/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_login.tables.pojos;


import com.odsProject.odsProject.database.jooq.ods_login.enums.VistaAdminAuditoriaLoginRecienteEvento;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAdminAuditoriaLoginReciente implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private LocalDateTime fechaEvento;
    private VistaAdminAuditoriaLoginRecienteEvento evento;
    private String username;
    private String fullName;
    private String emailIntento;
    private String ipAddress;
    private String userAgent;
    private String detalle;

    public VistaAdminAuditoriaLoginReciente() {}

    public VistaAdminAuditoriaLoginReciente(VistaAdminAuditoriaLoginReciente value) {
        this.id = value.id;
        this.fechaEvento = value.fechaEvento;
        this.evento = value.evento;
        this.username = value.username;
        this.fullName = value.fullName;
        this.emailIntento = value.emailIntento;
        this.ipAddress = value.ipAddress;
        this.userAgent = value.userAgent;
        this.detalle = value.detalle;
    }

    public VistaAdminAuditoriaLoginReciente(
        Integer id,
        LocalDateTime fechaEvento,
        VistaAdminAuditoriaLoginRecienteEvento evento,
        String username,
        String fullName,
        String emailIntento,
        String ipAddress,
        String userAgent,
        String detalle
    ) {
        this.id = id;
        this.fechaEvento = fechaEvento;
        this.evento = evento;
        this.username = username;
        this.fullName = fullName;
        this.emailIntento = emailIntento;
        this.ipAddress = ipAddress;
        this.userAgent = userAgent;
        this.detalle = detalle;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.fecha_evento</code>.
     */
    public LocalDateTime getFechaEvento() {
        return this.fechaEvento;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.fecha_evento</code>.
     */
    public void setFechaEvento(LocalDateTime fechaEvento) {
        this.fechaEvento = fechaEvento;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.evento</code>.
     */
    public VistaAdminAuditoriaLoginRecienteEvento getEvento() {
        return this.evento;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.evento</code>.
     */
    public void setEvento(VistaAdminAuditoriaLoginRecienteEvento evento) {
        this.evento = evento;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.full_name</code>.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.email_intento</code>.
     */
    public String getEmailIntento() {
        return this.emailIntento;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.email_intento</code>.
     */
    public void setEmailIntento(String emailIntento) {
        this.emailIntento = emailIntento;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.ip_address</code>.
     */
    public String getIpAddress() {
        return this.ipAddress;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.ip_address</code>.
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.user_agent</code>.
     */
    public String getUserAgent() {
        return this.userAgent;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.user_agent</code>.
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * Getter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.detalle</code>.
     */
    public String getDetalle() {
        return this.detalle;
    }

    /**
     * Setter for
     * <code>ods_login.vista_admin_auditoria_login_reciente.detalle</code>.
     */
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VistaAdminAuditoriaLoginReciente other = (VistaAdminAuditoriaLoginReciente) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fechaEvento == null) {
            if (other.fechaEvento != null)
                return false;
        }
        else if (!this.fechaEvento.equals(other.fechaEvento))
            return false;
        if (this.evento == null) {
            if (other.evento != null)
                return false;
        }
        else if (!this.evento.equals(other.evento))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.emailIntento == null) {
            if (other.emailIntento != null)
                return false;
        }
        else if (!this.emailIntento.equals(other.emailIntento))
            return false;
        if (this.ipAddress == null) {
            if (other.ipAddress != null)
                return false;
        }
        else if (!this.ipAddress.equals(other.ipAddress))
            return false;
        if (this.userAgent == null) {
            if (other.userAgent != null)
                return false;
        }
        else if (!this.userAgent.equals(other.userAgent))
            return false;
        if (this.detalle == null) {
            if (other.detalle != null)
                return false;
        }
        else if (!this.detalle.equals(other.detalle))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fechaEvento == null) ? 0 : this.fechaEvento.hashCode());
        result = prime * result + ((this.evento == null) ? 0 : this.evento.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.emailIntento == null) ? 0 : this.emailIntento.hashCode());
        result = prime * result + ((this.ipAddress == null) ? 0 : this.ipAddress.hashCode());
        result = prime * result + ((this.userAgent == null) ? 0 : this.userAgent.hashCode());
        result = prime * result + ((this.detalle == null) ? 0 : this.detalle.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VistaAdminAuditoriaLoginReciente (");

        sb.append(id);
        sb.append(", ").append(fechaEvento);
        sb.append(", ").append(evento);
        sb.append(", ").append(username);
        sb.append(", ").append(fullName);
        sb.append(", ").append(emailIntento);
        sb.append(", ").append(ipAddress);
        sb.append(", ").append(userAgent);
        sb.append(", ").append(detalle);

        sb.append(")");
        return sb.toString();
    }
}
