/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_master.tables.records;


import com.odsProject.odsProject.database.jooq.ods_master.enums.ProyectosEstado;
import com.odsProject.odsProject.database.jooq.ods_master.tables.Proyectos;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProyectosRecord extends UpdatableRecordImpl<ProyectosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ods_master.proyectos.id</code>.
     */
    public ProyectosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ods_master.proyectos.usuario_id</code>.
     */
    public ProyectosRecord setUsuarioId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.usuario_id</code>.
     */
    public Integer getUsuarioId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ods_master.proyectos.sede_id</code>.
     */
    public ProyectosRecord setSedeId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.sede_id</code>.
     */
    public Integer getSedeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ods_master.proyectos.nombre_proyecto</code>.
     */
    public ProyectosRecord setNombreProyecto(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.nombre_proyecto</code>.
     */
    public String getNombreProyecto() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ods_master.proyectos.descripcion</code>.
     */
    public ProyectosRecord setDescripcion(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ods_master.proyectos.fecha_inicio</code>.
     */
    public ProyectosRecord setFechaInicio(LocalDate value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.fecha_inicio</code>.
     */
    public LocalDate getFechaInicio() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>ods_master.proyectos.fecha_fin</code>.
     */
    public ProyectosRecord setFechaFin(LocalDate value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.fecha_fin</code>.
     */
    public LocalDate getFechaFin() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>ods_master.proyectos.meta_general</code>.
     */
    public ProyectosRecord setMetaGeneral(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.meta_general</code>.
     */
    public String getMetaGeneral() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ods_master.proyectos.eje_planes_id</code>.
     */
    public ProyectosRecord setEjePlanesId(UByte value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.eje_planes_id</code>.
     */
    public UByte getEjePlanesId() {
        return (UByte) get(8);
    }

    /**
     * Setter for <code>ods_master.proyectos.aliado_externo</code>. Aliado
     * externo texto libre SODSI
     */
    public ProyectosRecord setAliadoExterno(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.aliado_externo</code>. Aliado
     * externo texto libre SODSI
     */
    public String getAliadoExterno() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ods_master.proyectos.location_province</code>.
     */
    public ProyectosRecord setLocationProvince(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.location_province</code>.
     */
    public String getLocationProvince() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ods_master.proyectos.location_canton</code>.
     */
    public ProyectosRecord setLocationCanton(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.location_canton</code>.
     */
    public String getLocationCanton() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ods_master.proyectos.location_district</code>.
     */
    public ProyectosRecord setLocationDistrict(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.location_district</code>.
     */
    public String getLocationDistrict() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ods_master.proyectos.estado</code>.
     */
    public ProyectosRecord setEstado(ProyectosEstado value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.estado</code>.
     */
    public ProyectosEstado getEstado() {
        return (ProyectosEstado) get(13);
    }

    /**
     * Setter for <code>ods_master.proyectos.auditado_por</code>.
     */
    public ProyectosRecord setAuditadoPor(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.auditado_por</code>.
     */
    public Integer getAuditadoPor() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>ods_master.proyectos.auditado_en</code>.
     */
    public ProyectosRecord setAuditadoEn(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.auditado_en</code>.
     */
    public LocalDateTime getAuditadoEn() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>ods_master.proyectos.observaciones_cierre</code>.
     */
    public ProyectosRecord setObservacionesCierre(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.observaciones_cierre</code>.
     */
    public String getObservacionesCierre() {
        return (String) get(16);
    }

    /**
     * Setter for <code>ods_master.proyectos.fecha_envio_revision</code>.
     */
    public ProyectosRecord setFechaEnvioRevision(LocalDateTime value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.fecha_envio_revision</code>.
     */
    public LocalDateTime getFechaEnvioRevision() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>ods_master.proyectos.created_at</code>.
     */
    public ProyectosRecord setCreatedAt(LocalDateTime value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>ods_master.proyectos.updated_at</code>.
     */
    public ProyectosRecord setUpdatedAt(LocalDateTime value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyectos.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProyectosRecord
     */
    public ProyectosRecord() {
        super(Proyectos.PROYECTOS);
    }

    /**
     * Create a detached, initialised ProyectosRecord
     */
    public ProyectosRecord(Integer id, Integer usuarioId, Integer sedeId, String nombreProyecto, String descripcion, LocalDate fechaInicio, LocalDate fechaFin, String metaGeneral, UByte ejePlanesId, String aliadoExterno, String locationProvince, String locationCanton, String locationDistrict, ProyectosEstado estado, Integer auditadoPor, LocalDateTime auditadoEn, String observacionesCierre, LocalDateTime fechaEnvioRevision, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Proyectos.PROYECTOS);

        setId(id);
        setUsuarioId(usuarioId);
        setSedeId(sedeId);
        setNombreProyecto(nombreProyecto);
        setDescripcion(descripcion);
        setFechaInicio(fechaInicio);
        setFechaFin(fechaFin);
        setMetaGeneral(metaGeneral);
        setEjePlanesId(ejePlanesId);
        setAliadoExterno(aliadoExterno);
        setLocationProvince(locationProvince);
        setLocationCanton(locationCanton);
        setLocationDistrict(locationDistrict);
        setEstado(estado);
        setAuditadoPor(auditadoPor);
        setAuditadoEn(auditadoEn);
        setObservacionesCierre(observacionesCierre);
        setFechaEnvioRevision(fechaEnvioRevision);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProyectosRecord
     */
    public ProyectosRecord(com.odsProject.odsProject.database.jooq.ods_master.tables.pojos.Proyectos value) {
        super(Proyectos.PROYECTOS);

        if (value != null) {
            setId(value.getId());
            setUsuarioId(value.getUsuarioId());
            setSedeId(value.getSedeId());
            setNombreProyecto(value.getNombreProyecto());
            setDescripcion(value.getDescripcion());
            setFechaInicio(value.getFechaInicio());
            setFechaFin(value.getFechaFin());
            setMetaGeneral(value.getMetaGeneral());
            setEjePlanesId(value.getEjePlanesId());
            setAliadoExterno(value.getAliadoExterno());
            setLocationProvince(value.getLocationProvince());
            setLocationCanton(value.getLocationCanton());
            setLocationDistrict(value.getLocationDistrict());
            setEstado(value.getEstado());
            setAuditadoPor(value.getAuditadoPor());
            setAuditadoEn(value.getAuditadoEn());
            setObservacionesCierre(value.getObservacionesCierre());
            setFechaEnvioRevision(value.getFechaEnvioRevision());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
