/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_master.tables.records;


import com.odsProject.odsProject.database.jooq.ods_master.tables.ProyectoBeneficiarios;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProyectoBeneficiariosRecord extends UpdatableRecordImpl<ProyectoBeneficiariosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ods_master.proyecto_beneficiarios.id</code>.
     */
    public ProyectoBeneficiariosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyecto_beneficiarios.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ods_master.proyecto_beneficiarios.proyecto_id</code>.
     */
    public ProyectoBeneficiariosRecord setProyectoId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyecto_beneficiarios.proyecto_id</code>.
     */
    public Integer getProyectoId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ods_master.proyecto_beneficiarios.valor_id</code>.
     */
    public ProyectoBeneficiariosRecord setValorId(UShort value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ods_master.proyecto_beneficiarios.valor_id</code>.
     */
    public UShort getValorId() {
        return (UShort) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProyectoBeneficiariosRecord
     */
    public ProyectoBeneficiariosRecord() {
        super(ProyectoBeneficiarios.PROYECTO_BENEFICIARIOS);
    }

    /**
     * Create a detached, initialised ProyectoBeneficiariosRecord
     */
    public ProyectoBeneficiariosRecord(Integer id, Integer proyectoId, UShort valorId) {
        super(ProyectoBeneficiarios.PROYECTO_BENEFICIARIOS);

        setId(id);
        setProyectoId(proyectoId);
        setValorId(valorId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProyectoBeneficiariosRecord
     */
    public ProyectoBeneficiariosRecord(com.odsProject.odsProject.database.jooq.ods_master.tables.pojos.ProyectoBeneficiarios value) {
        super(ProyectoBeneficiarios.PROYECTO_BENEFICIARIOS);

        if (value != null) {
            setId(value.getId());
            setProyectoId(value.getProyectoId());
            setValorId(value.getValorId());
            resetChangedOnNotNull();
        }
    }
}
