/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods06;


import com.odsProject.odsProject.database.jooq.ods06.tables.AuditoriaOds06;
import com.odsProject.odsProject.database.jooq.ods06.tables.MedicionParametroValores;
import com.odsProject.odsProject.database.jooq.ods06.tables.MedicionesHistoricas;
import com.odsProject.odsProject.database.jooq.ods06.tables.ProyectoIndicadorParametros;
import com.odsProject.odsProject.database.jooq.ods06.tables.ProyectoIndicadores;
import com.odsProject.odsProject.database.jooq.ods06.tables.VistaAdminAuditoriaReciente;
import com.odsProject.odsProject.database.jooq.ods06.tables.VistaAdminDetalleIndicadores;
import com.odsProject.odsProject.database.jooq.ods06.tables.VistaAdminResumenGeneral;


/**
 * Convenience access to all tables in ods06.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Auditoría interna de cambios en la base de datos ODS06
     */
    public static final AuditoriaOds06 AUDITORIA_ODS06 = AuditoriaOds06.AUDITORIA_ODS06;

    /**
     * The table <code>ods06.medicion_parametro_valores</code>.
     */
    public static final MedicionParametroValores MEDICION_PARAMETRO_VALORES = MedicionParametroValores.MEDICION_PARAMETRO_VALORES;

    /**
     * The table <code>ods06.mediciones_historicas</code>.
     */
    public static final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * The table <code>ods06.proyecto_indicador_parametros</code>.
     */
    public static final ProyectoIndicadorParametros PROYECTO_INDICADOR_PARAMETROS = ProyectoIndicadorParametros.PROYECTO_INDICADOR_PARAMETROS;

    /**
     * The table <code>ods06.proyecto_indicadores</code>.
     */
    public static final ProyectoIndicadores PROYECTO_INDICADORES = ProyectoIndicadores.PROYECTO_INDICADORES;

    /**
     * The table <code>ods06.vista_admin_auditoria_reciente</code>.
     */
    public static final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * The table <code>ods06.vista_admin_detalle_indicadores</code>.
     */
    public static final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * The table <code>ods06.vista_admin_resumen_general</code>.
     */
    public static final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;
}
