/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods14;


import com.odsProject.odsProject.database.jooq.DefaultCatalog;
import com.odsProject.odsProject.database.jooq.ods14.tables.AuditoriaOds14;
import com.odsProject.odsProject.database.jooq.ods14.tables.Indicadores;
import com.odsProject.odsProject.database.jooq.ods14.tables.MedicionesHistoricas;
import com.odsProject.odsProject.database.jooq.ods14.tables.MetasProyecto;
import com.odsProject.odsProject.database.jooq.ods14.tables.Proyectos;
import com.odsProject.odsProject.database.jooq.ods14.tables.VistaAdminAuditoriaReciente;
import com.odsProject.odsProject.database.jooq.ods14.tables.VistaAdminDetalleIndicadores;
import com.odsProject.odsProject.database.jooq.ods14.tables.VistaAdminEstadisticasGenerales;
import com.odsProject.odsProject.database.jooq.ods14.tables.VistaAdminResumenGeneral;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ods14 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods14</code>
     */
    public static final Ods14 ODS14 = new Ods14();

    /**
     * Auditoría de cambios en el sistema ODS14
     */
    public final AuditoriaOds14 AUDITORIA_ODS14 = AuditoriaOds14.AUDITORIA_ODS14;

    /**
     * Indicadores medidos por cada proyecto ODS14
     */
    public final Indicadores INDICADORES = Indicadores.INDICADORES;

    /**
     * Historial de mediciones de indicadores ODS14
     */
    public final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * Metas específicas establecidas por cada proyecto ODS14
     */
    public final MetasProyecto METAS_PROYECTO = MetasProyecto.METAS_PROYECTO;

    /**
     * Proyectos ODS14 creados por usuarios
     */
    public final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * The table <code>ods14.vista_admin_auditoria_reciente</code>.
     */
    public final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * The table <code>ods14.vista_admin_detalle_indicadores</code>.
     */
    public final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * The table <code>ods14.vista_admin_estadisticas_generales</code>.
     */
    public final VistaAdminEstadisticasGenerales VISTA_ADMIN_ESTADISTICAS_GENERALES = VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES;

    /**
     * The table <code>ods14.vista_admin_resumen_general</code>.
     */
    public final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;

    /**
     * No further instances allowed
     */
    private Ods14() {
        super("ods14", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuditoriaOds14.AUDITORIA_ODS14,
            Indicadores.INDICADORES,
            MedicionesHistoricas.MEDICIONES_HISTORICAS,
            MetasProyecto.METAS_PROYECTO,
            Proyectos.PROYECTOS,
            VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE,
            VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES,
            VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES,
            VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL
        );
    }
}
