/*
 * This file is generated by jOOQ.
 */
package odsProject.database.jooq.ods07.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import odsProject.database.jooq.ods07.Indexes;
import odsProject.database.jooq.ods07.Keys;
import odsProject.database.jooq.ods07.Ods07;
import odsProject.database.jooq.ods07.tables.records.AuditoriaOds07Record;
import odsProject.database.jooq.ods_login.tables.Usuarios.UsuariosPath;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Auditoría de cambios en el sistema ODS07
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditoriaOds07 extends TableImpl<AuditoriaOds07Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods07.auditoria_ods07</code>
     */
    public static final AuditoriaOds07 AUDITORIA_ODS07 = new AuditoriaOds07();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditoriaOds07Record> getRecordType() {
        return AuditoriaOds07Record.class;
    }

    /**
     * The column <code>ods07.auditoria_ods07.id</code>.
     */
    public final TableField<AuditoriaOds07Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ods07.auditoria_ods07.tabla_afectada</code>.
     */
    public final TableField<AuditoriaOds07Record, String> TABLA_AFECTADA = createField(DSL.name("tabla_afectada"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>ods07.auditoria_ods07.registro_id</code>.
     */
    public final TableField<AuditoriaOds07Record, Integer> REGISTRO_ID = createField(DSL.name("registro_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ods07.auditoria_ods07.accion</code>.
     */
    public final TableField<AuditoriaOds07Record, String> ACCION = createField(DSL.name("accion"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>ods07.auditoria_ods07.usuario_id</code>.
     */
    public final TableField<AuditoriaOds07Record, Integer> USUARIO_ID = createField(DSL.name("usuario_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ods07.auditoria_ods07.valores_anteriores</code>.
     */
    public final TableField<AuditoriaOds07Record, String> VALORES_ANTERIORES = createField(DSL.name("valores_anteriores"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods07.auditoria_ods07.valores_nuevos</code>.
     */
    public final TableField<AuditoriaOds07Record, String> VALORES_NUEVOS = createField(DSL.name("valores_nuevos"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods07.auditoria_ods07.fecha_cambio</code>.
     */
    public final TableField<AuditoriaOds07Record, LocalDateTime> FECHA_CAMBIO = createField(DSL.name("fecha_cambio"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>ods07.auditoria_ods07.ip_address</code>.
     */
    public final TableField<AuditoriaOds07Record, String> IP_ADDRESS = createField(DSL.name("ip_address"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private AuditoriaOds07(Name alias, Table<AuditoriaOds07Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuditoriaOds07(Name alias, Table<AuditoriaOds07Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Auditoría de cambios en el sistema ODS07"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ods07.auditoria_ods07</code> table reference
     */
    public AuditoriaOds07(String alias) {
        this(DSL.name(alias), AUDITORIA_ODS07);
    }

    /**
     * Create an aliased <code>ods07.auditoria_ods07</code> table reference
     */
    public AuditoriaOds07(Name alias) {
        this(alias, AUDITORIA_ODS07);
    }

    /**
     * Create a <code>ods07.auditoria_ods07</code> table reference
     */
    public AuditoriaOds07() {
        this(DSL.name("auditoria_ods07"), null);
    }

    public <O extends Record> AuditoriaOds07(Table<O> path, ForeignKey<O, AuditoriaOds07Record> childPath, InverseForeignKey<O, AuditoriaOds07Record> parentPath) {
        super(path, childPath, parentPath, AUDITORIA_ODS07);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuditoriaOds07Path extends AuditoriaOds07 implements Path<AuditoriaOds07Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuditoriaOds07Path(Table<O> path, ForeignKey<O, AuditoriaOds07Record> childPath, InverseForeignKey<O, AuditoriaOds07Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuditoriaOds07Path(Name alias, Table<AuditoriaOds07Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuditoriaOds07Path as(String alias) {
            return new AuditoriaOds07Path(DSL.name(alias), this);
        }

        @Override
        public AuditoriaOds07Path as(Name alias) {
            return new AuditoriaOds07Path(alias, this);
        }

        @Override
        public AuditoriaOds07Path as(Table<?> alias) {
            return new AuditoriaOds07Path(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ods07.ODS07;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUDITORIA_ODS07_IDX_AUDITORIA_FECHA_TABLA, Indexes.AUDITORIA_ODS07_IDX_FECHA, Indexes.AUDITORIA_ODS07_IDX_TABLA_REGISTRO, Indexes.AUDITORIA_ODS07_USUARIO_ID);
    }

    @Override
    public Identity<AuditoriaOds07Record, Integer> getIdentity() {
        return (Identity<AuditoriaOds07Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuditoriaOds07Record> getPrimaryKey() {
        return Keys.KEY_AUDITORIA_ODS07_PRIMARY;
    }

    @Override
    public List<ForeignKey<AuditoriaOds07Record, ?>> getReferences() {
        return Arrays.asList(Keys.AUDITORIA_ODS07_IBFK_1);
    }

    private transient UsuariosPath _usuarios;

    /**
     * Get the implicit join path to the <code>ods_login.usuarios</code> table.
     */
    public UsuariosPath usuarios() {
        if (_usuarios == null)
            _usuarios = new UsuariosPath(this, Keys.AUDITORIA_ODS07_IBFK_1, null);

        return _usuarios;
    }

    @Override
    public List<Check<AuditoriaOds07Record>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("valores_anteriores"), "json_valid(`valores_anteriores`)", true),
            Internal.createCheck(this, DSL.name("valores_nuevos"), "json_valid(`valores_nuevos`)", true)
        );
    }

    @Override
    public AuditoriaOds07 as(String alias) {
        return new AuditoriaOds07(DSL.name(alias), this);
    }

    @Override
    public AuditoriaOds07 as(Name alias) {
        return new AuditoriaOds07(alias, this);
    }

    @Override
    public AuditoriaOds07 as(Table<?> alias) {
        return new AuditoriaOds07(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds07 rename(String name) {
        return new AuditoriaOds07(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds07 rename(Name name) {
        return new AuditoriaOds07(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds07 rename(Table<?> name) {
        return new AuditoriaOds07(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds07 where(Condition condition) {
        return new AuditoriaOds07(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds07 where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds07 where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds07 where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds07 where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds07 where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds07 where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds07 where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds07 whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds07 whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
