/*
 * This file is generated by jOOQ.
 */
package odsProject.database.jooq;


import java.util.Arrays;
import java.util.List;

import odsProject.database.jooq.ods01.Ods01;
import odsProject.database.jooq.ods02.Ods02;
import odsProject.database.jooq.ods03.Ods03;
import odsProject.database.jooq.ods04.Ods04;
import odsProject.database.jooq.ods05.Ods05;
import odsProject.database.jooq.ods06.Ods06;
import odsProject.database.jooq.ods07.Ods07;
import odsProject.database.jooq.ods08.Ods08;
import odsProject.database.jooq.ods09.Ods09;
import odsProject.database.jooq.ods10.Ods10;
import odsProject.database.jooq.ods11.Ods11;
import odsProject.database.jooq.ods12.Ods12;
import odsProject.database.jooq.ods13.Ods13;
import odsProject.database.jooq.ods14.Ods14;
import odsProject.database.jooq.ods15.Ods15;
import odsProject.database.jooq.ods16.Ods16;
import odsProject.database.jooq.ods17.Ods17;
import odsProject.database.jooq.ods_login.OdsLogin;

import org.jooq.Constants;
import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>ods01</code>.
     */
    public final Ods01 ODS01 = Ods01.ODS01;

    /**
     * The schema <code>ods02</code>.
     */
    public final Ods02 ODS02 = Ods02.ODS02;

    /**
     * The schema <code>ods03</code>.
     */
    public final Ods03 ODS03 = Ods03.ODS03;

    /**
     * The schema <code>ods04</code>.
     */
    public final Ods04 ODS04 = Ods04.ODS04;

    /**
     * The schema <code>ods05</code>.
     */
    public final Ods05 ODS05 = Ods05.ODS05;

    /**
     * The schema <code>ods06</code>.
     */
    public final Ods06 ODS06 = Ods06.ODS06;

    /**
     * The schema <code>ods07</code>.
     */
    public final Ods07 ODS07 = Ods07.ODS07;

    /**
     * The schema <code>ods08</code>.
     */
    public final Ods08 ODS08 = Ods08.ODS08;

    /**
     * The schema <code>ods09</code>.
     */
    public final Ods09 ODS09 = Ods09.ODS09;

    /**
     * The schema <code>ods10</code>.
     */
    public final Ods10 ODS10 = Ods10.ODS10;

    /**
     * The schema <code>ods11</code>.
     */
    public final Ods11 ODS11 = Ods11.ODS11;

    /**
     * The schema <code>ods12</code>.
     */
    public final Ods12 ODS12 = Ods12.ODS12;

    /**
     * The schema <code>ods13</code>.
     */
    public final Ods13 ODS13 = Ods13.ODS13;

    /**
     * The schema <code>ods14</code>.
     */
    public final Ods14 ODS14 = Ods14.ODS14;

    /**
     * The schema <code>ods15</code>.
     */
    public final Ods15 ODS15 = Ods15.ODS15;

    /**
     * The schema <code>ods16</code>.
     */
    public final Ods16 ODS16 = Ods16.ODS16;

    /**
     * The schema <code>ods17</code>.
     */
    public final Ods17 ODS17 = Ods17.ODS17;

    /**
     * The schema <code>ods_login</code>.
     */
    public final OdsLogin ODS_LOGIN = OdsLogin.ODS_LOGIN;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.asList(
            Ods01.ODS01,
            Ods02.ODS02,
            Ods03.ODS03,
            Ods04.ODS04,
            Ods05.ODS05,
            Ods06.ODS06,
            Ods07.ODS07,
            Ods08.ODS08,
            Ods09.ODS09,
            Ods10.ODS10,
            Ods11.ODS11,
            Ods12.ODS12,
            Ods13.ODS13,
            Ods14.ODS14,
            Ods15.ODS15,
            Ods16.ODS16,
            Ods17.ODS17,
            OdsLogin.ODS_LOGIN
        );
    }

    /**
     * A reference to the 3.19 minor release of the code generator. If this
     * doesn't compile, it's because the runtime library uses an older minor
     * release, namely: 3.19. You can turn off the generation of this reference
     * by specifying /configuration/generator/generate/jooqVersionReference
     */
    private static final String REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_19;
}
