/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods03.tables.daos;


import com.projectods.database.jooq.ods03.tables.AuditoriaOds03;
import com.projectods.database.jooq.ods03.tables.records.AuditoriaOds03Record;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * Auditoría de cambios en el sistema ODS03
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class AuditoriaOds03Dao extends DAOImpl<AuditoriaOds03Record, com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03, Integer> {

    /**
     * Create a new AuditoriaOds03Dao without any configuration
     */
    public AuditoriaOds03Dao() {
        super(AuditoriaOds03.AUDITORIA_ODS03, com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03.class);
    }

    /**
     * Create a new AuditoriaOds03Dao with an attached configuration
     */
    @Autowired
    public AuditoriaOds03Dao(Configuration configuration) {
        super(AuditoriaOds03.AUDITORIA_ODS03, com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03.class, configuration);
    }

    @Override
    public Integer getId(com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03 object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AuditoriaOds03.AUDITORIA_ODS03.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchById(Integer... values) {
        return fetch(AuditoriaOds03.AUDITORIA_ODS03.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03 fetchOneById(Integer value) {
        return fetchOne(AuditoriaOds03.AUDITORIA_ODS03.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchOptionalById(Integer value) {
        return fetchOptional(AuditoriaOds03.AUDITORIA_ODS03.ID, value);
    }

    /**
     * Fetch records that have <code>tabla_afectada BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchRangeOfTablaAfectada(String lowerInclusive, String upperInclusive) {
        return fetchRange(AuditoriaOds03.AUDITORIA_ODS03.TABLA_AFECTADA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tabla_afectada IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchByTablaAfectada(String... values) {
        return fetch(AuditoriaOds03.AUDITORIA_ODS03.TABLA_AFECTADA, values);
    }

    /**
     * Fetch records that have <code>registro_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchRangeOfRegistroId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AuditoriaOds03.AUDITORIA_ODS03.REGISTRO_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>registro_id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchByRegistroId(Integer... values) {
        return fetch(AuditoriaOds03.AUDITORIA_ODS03.REGISTRO_ID, values);
    }

    /**
     * Fetch records that have <code>accion BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchRangeOfAccion(String lowerInclusive, String upperInclusive) {
        return fetchRange(AuditoriaOds03.AUDITORIA_ODS03.ACCION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>accion IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchByAccion(String... values) {
        return fetch(AuditoriaOds03.AUDITORIA_ODS03.ACCION, values);
    }

    /**
     * Fetch records that have <code>usuario_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchRangeOfUsuarioId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AuditoriaOds03.AUDITORIA_ODS03.USUARIO_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>usuario_id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchByUsuarioId(Integer... values) {
        return fetch(AuditoriaOds03.AUDITORIA_ODS03.USUARIO_ID, values);
    }

    /**
     * Fetch records that have <code>valores_anteriores BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchRangeOfValoresAnteriores(String lowerInclusive, String upperInclusive) {
        return fetchRange(AuditoriaOds03.AUDITORIA_ODS03.VALORES_ANTERIORES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>valores_anteriores IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchByValoresAnteriores(String... values) {
        return fetch(AuditoriaOds03.AUDITORIA_ODS03.VALORES_ANTERIORES, values);
    }

    /**
     * Fetch records that have <code>valores_nuevos BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchRangeOfValoresNuevos(String lowerInclusive, String upperInclusive) {
        return fetchRange(AuditoriaOds03.AUDITORIA_ODS03.VALORES_NUEVOS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>valores_nuevos IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchByValoresNuevos(String... values) {
        return fetch(AuditoriaOds03.AUDITORIA_ODS03.VALORES_NUEVOS, values);
    }

    /**
     * Fetch records that have <code>fecha_cambio BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchRangeOfFechaCambio(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(AuditoriaOds03.AUDITORIA_ODS03.FECHA_CAMBIO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fecha_cambio IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchByFechaCambio(LocalDateTime... values) {
        return fetch(AuditoriaOds03.AUDITORIA_ODS03.FECHA_CAMBIO, values);
    }

    /**
     * Fetch records that have <code>ip_address BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchRangeOfIpAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(AuditoriaOds03.AUDITORIA_ODS03.IP_ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ip_address IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods03.tables.pojos.AuditoriaOds03> fetchByIpAddress(String... values) {
        return fetch(AuditoriaOds03.AUDITORIA_ODS03.IP_ADDRESS, values);
    }
}
