/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods06;


import com.projectods.database.jooq.ods06.tables.AuditoriaOds06;
import com.projectods.database.jooq.ods06.tables.Indicadores;
import com.projectods.database.jooq.ods06.tables.MedicionesHistoricas;
import com.projectods.database.jooq.ods06.tables.MetasProyecto;
import com.projectods.database.jooq.ods06.tables.Proyectos;
import com.projectods.database.jooq.ods06.tables.VistaAdminAuditoriaReciente;
import com.projectods.database.jooq.ods06.tables.VistaAdminDetalleIndicadores;
import com.projectods.database.jooq.ods06.tables.VistaAdminEstadisticasGenerales;
import com.projectods.database.jooq.ods06.tables.VistaAdminResumenGeneral;


/**
 * Convenience access to all tables in ods06.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Auditoría de cambios en el sistema ODS06
     */
    public static final AuditoriaOds06 AUDITORIA_ODS06 = AuditoriaOds06.AUDITORIA_ODS06;

    /**
     * Indicadores medidos por cada proyecto ODS06
     */
    public static final Indicadores INDICADORES = Indicadores.INDICADORES;

    /**
     * Historial de mediciones de indicadores ODS06
     */
    public static final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * Metas específicas establecidas por cada proyecto ODS06
     */
    public static final MetasProyecto METAS_PROYECTO = MetasProyecto.METAS_PROYECTO;

    /**
     * Proyectos ODS06 creados por usuarios
     */
    public static final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * VIEW
     */
    public static final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * VIEW
     */
    public static final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * VIEW
     */
    public static final VistaAdminEstadisticasGenerales VISTA_ADMIN_ESTADISTICAS_GENERALES = VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES;

    /**
     * VIEW
     */
    public static final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;
}
