/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_master;


import com.odsProject.odsProject.database.jooq.ods_login.tables.OdsCatalog;
import com.odsProject.odsProject.database.jooq.ods_login.tables.Sedes;
import com.odsProject.odsProject.database.jooq.ods_login.tables.Usuarios;
import com.odsProject.odsProject.database.jooq.ods_login.tables.records.OdsCatalogRecord;
import com.odsProject.odsProject.database.jooq.ods_login.tables.records.SedesRecord;
import com.odsProject.odsProject.database.jooq.ods_login.tables.records.UsuariosRecord;
import com.odsProject.odsProject.database.jooq.ods_master.tables.ProyectoChatMensajes;
import com.odsProject.odsProject.database.jooq.ods_master.tables.ProyectoDocumentos;
import com.odsProject.odsProject.database.jooq.ods_master.tables.ProyectoOds;
import com.odsProject.odsProject.database.jooq.ods_master.tables.ProyectoTransicionSolicitud;
import com.odsProject.odsProject.database.jooq.ods_master.tables.Proyectos;
import com.odsProject.odsProject.database.jooq.ods_master.tables.records.ProyectoChatMensajesRecord;
import com.odsProject.odsProject.database.jooq.ods_master.tables.records.ProyectoDocumentosRecord;
import com.odsProject.odsProject.database.jooq.ods_master.tables.records.ProyectoOdsRecord;
import com.odsProject.odsProject.database.jooq.ods_master.tables.records.ProyectoTransicionSolicitudRecord;
import com.odsProject.odsProject.database.jooq.ods_master.tables.records.ProyectosRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * ods_master.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProyectoChatMensajesRecord> KEY_PROYECTO_CHAT_MENSAJES_PRIMARY = Internal.createUniqueKey(ProyectoChatMensajes.PROYECTO_CHAT_MENSAJES, DSL.name("KEY_proyecto_chat_mensajes_PRIMARY"), new TableField[] { ProyectoChatMensajes.PROYECTO_CHAT_MENSAJES.ID }, true);
    public static final UniqueKey<ProyectoDocumentosRecord> KEY_PROYECTO_DOCUMENTOS_PRIMARY = Internal.createUniqueKey(ProyectoDocumentos.PROYECTO_DOCUMENTOS, DSL.name("KEY_proyecto_documentos_PRIMARY"), new TableField[] { ProyectoDocumentos.PROYECTO_DOCUMENTOS.ID }, true);
    public static final UniqueKey<ProyectoOdsRecord> KEY_PROYECTO_ODS_PRIMARY = Internal.createUniqueKey(ProyectoOds.PROYECTO_ODS, DSL.name("KEY_proyecto_ods_PRIMARY"), new TableField[] { ProyectoOds.PROYECTO_ODS.ID }, true);
    public static final UniqueKey<ProyectoOdsRecord> KEY_PROYECTO_ODS_UK_PROYECTO_ODS = Internal.createUniqueKey(ProyectoOds.PROYECTO_ODS, DSL.name("KEY_proyecto_ods_uk_proyecto_ods"), new TableField[] { ProyectoOds.PROYECTO_ODS.PROYECTO_ID, ProyectoOds.PROYECTO_ODS.ODS_ID }, true);
    public static final UniqueKey<ProyectoTransicionSolicitudRecord> KEY_PROYECTO_TRANSICION_SOLICITUD_PRIMARY = Internal.createUniqueKey(ProyectoTransicionSolicitud.PROYECTO_TRANSICION_SOLICITUD, DSL.name("KEY_proyecto_transicion_solicitud_PRIMARY"), new TableField[] { ProyectoTransicionSolicitud.PROYECTO_TRANSICION_SOLICITUD.ID }, true);
    public static final UniqueKey<ProyectosRecord> KEY_PROYECTOS_PRIMARY = Internal.createUniqueKey(Proyectos.PROYECTOS, DSL.name("KEY_proyectos_PRIMARY"), new TableField[] { Proyectos.PROYECTOS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ProyectoChatMensajesRecord, ProyectosRecord> PROYECTO_CHAT_MENSAJES_IBFK_1 = Internal.createForeignKey(ProyectoChatMensajes.PROYECTO_CHAT_MENSAJES, DSL.name("proyecto_chat_mensajes_ibfk_1"), new TableField[] { ProyectoChatMensajes.PROYECTO_CHAT_MENSAJES.PROYECTO_ID }, Keys.KEY_PROYECTOS_PRIMARY, new TableField[] { Proyectos.PROYECTOS.ID }, true);
    public static final ForeignKey<ProyectoChatMensajesRecord, UsuariosRecord> PROYECTO_CHAT_MENSAJES_IBFK_2 = Internal.createForeignKey(ProyectoChatMensajes.PROYECTO_CHAT_MENSAJES, DSL.name("proyecto_chat_mensajes_ibfk_2"), new TableField[] { ProyectoChatMensajes.PROYECTO_CHAT_MENSAJES.AUTOR_ID }, com.odsProject.odsProject.database.jooq.ods_login.Keys.KEY_USUARIOS_PRIMARY, new TableField[] { Usuarios.USUARIOS.ID }, true);
    public static final ForeignKey<ProyectoDocumentosRecord, ProyectosRecord> PROYECTO_DOCUMENTOS_IBFK_1 = Internal.createForeignKey(ProyectoDocumentos.PROYECTO_DOCUMENTOS, DSL.name("proyecto_documentos_ibfk_1"), new TableField[] { ProyectoDocumentos.PROYECTO_DOCUMENTOS.PROYECTO_ID }, Keys.KEY_PROYECTOS_PRIMARY, new TableField[] { Proyectos.PROYECTOS.ID }, true);
    public static final ForeignKey<ProyectoDocumentosRecord, UsuariosRecord> PROYECTO_DOCUMENTOS_IBFK_2 = Internal.createForeignKey(ProyectoDocumentos.PROYECTO_DOCUMENTOS, DSL.name("proyecto_documentos_ibfk_2"), new TableField[] { ProyectoDocumentos.PROYECTO_DOCUMENTOS.SUBIDO_POR }, com.odsProject.odsProject.database.jooq.ods_login.Keys.KEY_USUARIOS_PRIMARY, new TableField[] { Usuarios.USUARIOS.ID }, true);
    public static final ForeignKey<ProyectoOdsRecord, ProyectosRecord> PROYECTO_ODS_IBFK_1 = Internal.createForeignKey(ProyectoOds.PROYECTO_ODS, DSL.name("proyecto_ods_ibfk_1"), new TableField[] { ProyectoOds.PROYECTO_ODS.PROYECTO_ID }, Keys.KEY_PROYECTOS_PRIMARY, new TableField[] { Proyectos.PROYECTOS.ID }, true);
    public static final ForeignKey<ProyectoOdsRecord, OdsCatalogRecord> PROYECTO_ODS_IBFK_2 = Internal.createForeignKey(ProyectoOds.PROYECTO_ODS, DSL.name("proyecto_ods_ibfk_2"), new TableField[] { ProyectoOds.PROYECTO_ODS.ODS_ID }, com.odsProject.odsProject.database.jooq.ods_login.Keys.KEY_ODS_CATALOG_PRIMARY, new TableField[] { OdsCatalog.ODS_CATALOG.ID }, true);
    public static final ForeignKey<ProyectoTransicionSolicitudRecord, ProyectosRecord> PROYECTO_TRANSICION_SOLICITUD_IBFK_1 = Internal.createForeignKey(ProyectoTransicionSolicitud.PROYECTO_TRANSICION_SOLICITUD, DSL.name("proyecto_transicion_solicitud_ibfk_1"), new TableField[] { ProyectoTransicionSolicitud.PROYECTO_TRANSICION_SOLICITUD.PROYECTO_ID }, Keys.KEY_PROYECTOS_PRIMARY, new TableField[] { Proyectos.PROYECTOS.ID }, true);
    public static final ForeignKey<ProyectoTransicionSolicitudRecord, UsuariosRecord> PROYECTO_TRANSICION_SOLICITUD_IBFK_2 = Internal.createForeignKey(ProyectoTransicionSolicitud.PROYECTO_TRANSICION_SOLICITUD, DSL.name("proyecto_transicion_solicitud_ibfk_2"), new TableField[] { ProyectoTransicionSolicitud.PROYECTO_TRANSICION_SOLICITUD.SOLICITADO_POR }, com.odsProject.odsProject.database.jooq.ods_login.Keys.KEY_USUARIOS_PRIMARY, new TableField[] { Usuarios.USUARIOS.ID }, true);
    public static final ForeignKey<ProyectoTransicionSolicitudRecord, UsuariosRecord> PROYECTO_TRANSICION_SOLICITUD_IBFK_3 = Internal.createForeignKey(ProyectoTransicionSolicitud.PROYECTO_TRANSICION_SOLICITUD, DSL.name("proyecto_transicion_solicitud_ibfk_3"), new TableField[] { ProyectoTransicionSolicitud.PROYECTO_TRANSICION_SOLICITUD.RESUELTO_POR }, com.odsProject.odsProject.database.jooq.ods_login.Keys.KEY_USUARIOS_PRIMARY, new TableField[] { Usuarios.USUARIOS.ID }, true);
    public static final ForeignKey<ProyectosRecord, UsuariosRecord> PROYECTOS_IBFK_1 = Internal.createForeignKey(Proyectos.PROYECTOS, DSL.name("proyectos_ibfk_1"), new TableField[] { Proyectos.PROYECTOS.USUARIO_ID }, com.odsProject.odsProject.database.jooq.ods_login.Keys.KEY_USUARIOS_PRIMARY, new TableField[] { Usuarios.USUARIOS.ID }, true);
    public static final ForeignKey<ProyectosRecord, SedesRecord> PROYECTOS_IBFK_2 = Internal.createForeignKey(Proyectos.PROYECTOS, DSL.name("proyectos_ibfk_2"), new TableField[] { Proyectos.PROYECTOS.SEDE_ID }, com.odsProject.odsProject.database.jooq.ods_login.Keys.KEY_SEDES_PRIMARY, new TableField[] { Sedes.SEDES.ID }, true);
    public static final ForeignKey<ProyectosRecord, UsuariosRecord> PROYECTOS_IBFK_3 = Internal.createForeignKey(Proyectos.PROYECTOS, DSL.name("proyectos_ibfk_3"), new TableField[] { Proyectos.PROYECTOS.AUDITADO_POR }, com.odsProject.odsProject.database.jooq.ods_login.Keys.KEY_USUARIOS_PRIMARY, new TableField[] { Usuarios.USUARIOS.ID }, true);
}
