/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_master;


import com.odsProject.odsProject.database.jooq.DefaultCatalog;
import com.odsProject.odsProject.database.jooq.ods_master.tables.ProyectoChatMensajes;
import com.odsProject.odsProject.database.jooq.ods_master.tables.ProyectoDocumentos;
import com.odsProject.odsProject.database.jooq.ods_master.tables.ProyectoOds;
import com.odsProject.odsProject.database.jooq.ods_master.tables.ProyectoTransicionSolicitud;
import com.odsProject.odsProject.database.jooq.ods_master.tables.Proyectos;
import com.odsProject.odsProject.database.jooq.ods_master.tables.VistaResumenProyectosOds;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OdsMaster extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods_master</code>
     */
    public static final OdsMaster ODS_MASTER = new OdsMaster();

    /**
     * The table <code>ods_master.proyecto_chat_mensajes</code>.
     */
    public final ProyectoChatMensajes PROYECTO_CHAT_MENSAJES = ProyectoChatMensajes.PROYECTO_CHAT_MENSAJES;

    /**
     * The table <code>ods_master.proyecto_documentos</code>.
     */
    public final ProyectoDocumentos PROYECTO_DOCUMENTOS = ProyectoDocumentos.PROYECTO_DOCUMENTOS;

    /**
     * The table <code>ods_master.proyecto_ods</code>.
     */
    public final ProyectoOds PROYECTO_ODS = ProyectoOds.PROYECTO_ODS;

    /**
     * The table <code>ods_master.proyecto_transicion_solicitud</code>.
     */
    public final ProyectoTransicionSolicitud PROYECTO_TRANSICION_SOLICITUD = ProyectoTransicionSolicitud.PROYECTO_TRANSICION_SOLICITUD;

    /**
     * The table <code>ods_master.proyectos</code>.
     */
    public final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * VIEW
     */
    public final VistaResumenProyectosOds VISTA_RESUMEN_PROYECTOS_ODS = VistaResumenProyectosOds.VISTA_RESUMEN_PROYECTOS_ODS;

    /**
     * No further instances allowed
     */
    private OdsMaster() {
        super("ods_master", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ProyectoChatMensajes.PROYECTO_CHAT_MENSAJES,
            ProyectoDocumentos.PROYECTO_DOCUMENTOS,
            ProyectoOds.PROYECTO_ODS,
            ProyectoTransicionSolicitud.PROYECTO_TRANSICION_SOLICITUD,
            Proyectos.PROYECTOS,
            VistaResumenProyectosOds.VISTA_RESUMEN_PROYECTOS_ODS
        );
    }
}
