/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods_master;


import com.odsProject.odsProject.database.jooq.ods_master.tables.ProyectoOds;
import com.odsProject.odsProject.database.jooq.ods_master.tables.Proyectos;
import com.odsProject.odsProject.database.jooq.ods_master.tables.VistaResumenProyectosOds;


/**
 * Convenience access to all tables in ods_master.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>ods_master.proyecto_ods</code>.
     */
    public static final ProyectoOds PROYECTO_ODS = ProyectoOds.PROYECTO_ODS;

    /**
     * The table <code>ods_master.proyectos</code>.
     */
    public static final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * VIEW
     */
    public static final VistaResumenProyectosOds VISTA_RESUMEN_PROYECTOS_ODS = VistaResumenProyectosOds.VISTA_RESUMEN_PROYECTOS_ODS;
}
