/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods04;


import com.projectods.database.jooq.DefaultCatalog;
import com.projectods.database.jooq.ods04.tables.AuditoriaOds04;
import com.projectods.database.jooq.ods04.tables.Indicadores;
import com.projectods.database.jooq.ods04.tables.MedicionesHistoricas;
import com.projectods.database.jooq.ods04.tables.MetasProyecto;
import com.projectods.database.jooq.ods04.tables.Proyectos;
import com.projectods.database.jooq.ods04.tables.VistaAdminAuditoriaReciente;
import com.projectods.database.jooq.ods04.tables.VistaAdminDetalleIndicadores;
import com.projectods.database.jooq.ods04.tables.VistaAdminEstadisticasGenerales;
import com.projectods.database.jooq.ods04.tables.VistaAdminResumenGeneral;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ods04 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods04</code>
     */
    public static final Ods04 ODS04 = new Ods04();

    /**
     * Auditoría de cambios en el sistema ODS04
     */
    public final AuditoriaOds04 AUDITORIA_ODS04 = AuditoriaOds04.AUDITORIA_ODS04;

    /**
     * Indicadores medidos por cada proyecto ODS04
     */
    public final Indicadores INDICADORES = Indicadores.INDICADORES;

    /**
     * Historial de mediciones de indicadores ODS04
     */
    public final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * Metas específicas establecidas por cada proyecto ODS04
     */
    public final MetasProyecto METAS_PROYECTO = MetasProyecto.METAS_PROYECTO;

    /**
     * Proyectos ODS04 creados por usuarios
     */
    public final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * VIEW
     */
    public final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * VIEW
     */
    public final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * VIEW
     */
    public final VistaAdminEstadisticasGenerales VISTA_ADMIN_ESTADISTICAS_GENERALES = VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES;

    /**
     * VIEW
     */
    public final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;

    /**
     * No further instances allowed
     */
    private Ods04() {
        super("ods04", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuditoriaOds04.AUDITORIA_ODS04,
            Indicadores.INDICADORES,
            MedicionesHistoricas.MEDICIONES_HISTORICAS,
            MetasProyecto.METAS_PROYECTO,
            Proyectos.PROYECTOS,
            VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE,
            VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES,
            VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES,
            VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL
        );
    }
}
