/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods13;


import com.odsProject.odsProject.database.jooq.DefaultCatalog;
import com.odsProject.odsProject.database.jooq.ods13.tables.AuditoriaOds13;
import com.odsProject.odsProject.database.jooq.ods13.tables.MedicionParametroValores;
import com.odsProject.odsProject.database.jooq.ods13.tables.MedicionesHistoricas;
import com.odsProject.odsProject.database.jooq.ods13.tables.ProyectoIndicadorParametros;
import com.odsProject.odsProject.database.jooq.ods13.tables.ProyectoIndicadores;
import com.odsProject.odsProject.database.jooq.ods13.tables.VistaAdminAuditoriaReciente;
import com.odsProject.odsProject.database.jooq.ods13.tables.VistaAdminDetalleIndicadores;
import com.odsProject.odsProject.database.jooq.ods13.tables.VistaAdminResumenGeneral;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ods13 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods13</code>
     */
    public static final Ods13 ODS13 = new Ods13();

    /**
     * The table <code>ods13.auditoria_ods13</code>.
     */
    public final AuditoriaOds13 AUDITORIA_ODS13 = AuditoriaOds13.AUDITORIA_ODS13;

    /**
     * The table <code>ods13.medicion_parametro_valores</code>.
     */
    public final MedicionParametroValores MEDICION_PARAMETRO_VALORES = MedicionParametroValores.MEDICION_PARAMETRO_VALORES;

    /**
     * The table <code>ods13.mediciones_historicas</code>.
     */
    public final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * The table <code>ods13.proyecto_indicador_parametros</code>.
     */
    public final ProyectoIndicadorParametros PROYECTO_INDICADOR_PARAMETROS = ProyectoIndicadorParametros.PROYECTO_INDICADOR_PARAMETROS;

    /**
     * The table <code>ods13.proyecto_indicadores</code>.
     */
    public final ProyectoIndicadores PROYECTO_INDICADORES = ProyectoIndicadores.PROYECTO_INDICADORES;

    /**
     * The table <code>ods13.vista_admin_auditoria_reciente</code>.
     */
    public final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * The table <code>ods13.vista_admin_detalle_indicadores</code>.
     */
    public final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * The table <code>ods13.vista_admin_resumen_general</code>.
     */
    public final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;

    /**
     * No further instances allowed
     */
    private Ods13() {
        super("ods13", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuditoriaOds13.AUDITORIA_ODS13,
            MedicionParametroValores.MEDICION_PARAMETRO_VALORES,
            MedicionesHistoricas.MEDICIONES_HISTORICAS,
            ProyectoIndicadorParametros.PROYECTO_INDICADOR_PARAMETROS,
            ProyectoIndicadores.PROYECTO_INDICADORES,
            VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE,
            VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES,
            VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL
        );
    }
}
