spring.application.name=odsProject

# Database Configuration - Principal (ods_login)
spring.datasource.url=jdbc:mariadb://localhost:3306/ods_login
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# jOOQ Configuration
spring.jooq.sql-dialect=MARIADB

# Logging Configuration
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.jooq=DEBUG
logging.level.com.odsProject.odsProject.repository=DEBUG
