/*
 * This file is generated by jOOQ.
 */
package odsProject.database.jooq.ods17;


import odsProject.database.jooq.ods17.tables.AuditoriaOds17;
import odsProject.database.jooq.ods17.tables.Indicadores;
import odsProject.database.jooq.ods17.tables.MedicionesHistoricas;
import odsProject.database.jooq.ods17.tables.MetasProyecto;
import odsProject.database.jooq.ods17.tables.Proyectos;
import odsProject.database.jooq.ods17.tables.VistaAdminAuditoriaReciente;
import odsProject.database.jooq.ods17.tables.VistaAdminDetalleIndicadores;
import odsProject.database.jooq.ods17.tables.VistaAdminEstadisticasGenerales;
import odsProject.database.jooq.ods17.tables.VistaAdminResumenGeneral;


/**
 * Convenience access to all tables in ods17.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Auditoría de cambios en el sistema ODS17
     */
    public static final AuditoriaOds17 AUDITORIA_ODS17 = AuditoriaOds17.AUDITORIA_ODS17;

    /**
     * Indicadores medidos por cada proyecto ODS17
     */
    public static final Indicadores INDICADORES = Indicadores.INDICADORES;

    /**
     * Historial de mediciones de indicadores ODS17
     */
    public static final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * Metas específicas establecidas por cada proyecto ODS17
     */
    public static final MetasProyecto METAS_PROYECTO = MetasProyecto.METAS_PROYECTO;

    /**
     * Proyectos ODS17 creados por usuarios
     */
    public static final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * The table <code>ods17.vista_admin_auditoria_reciente</code>.
     */
    public static final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * The table <code>ods17.vista_admin_detalle_indicadores</code>.
     */
    public static final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * The table <code>ods17.vista_admin_estadisticas_generales</code>.
     */
    public static final VistaAdminEstadisticasGenerales VISTA_ADMIN_ESTADISTICAS_GENERALES = VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES;

    /**
     * The table <code>ods17.vista_admin_resumen_general</code>.
     */
    public static final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;
}
