/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods16;


import com.projectods.database.jooq.DefaultCatalog;
import com.projectods.database.jooq.ods16.tables.AuditoriaOds16;
import com.projectods.database.jooq.ods16.tables.Indicadores;
import com.projectods.database.jooq.ods16.tables.MedicionesHistoricas;
import com.projectods.database.jooq.ods16.tables.MetasProyecto;
import com.projectods.database.jooq.ods16.tables.Proyectos;
import com.projectods.database.jooq.ods16.tables.VistaAdminAuditoriaReciente;
import com.projectods.database.jooq.ods16.tables.VistaAdminDetalleIndicadores;
import com.projectods.database.jooq.ods16.tables.VistaAdminEstadisticasGenerales;
import com.projectods.database.jooq.ods16.tables.VistaAdminResumenGeneral;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ods16 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods16</code>
     */
    public static final Ods16 ODS16 = new Ods16();

    /**
     * Auditoría de cambios en el sistema ODS16
     */
    public final AuditoriaOds16 AUDITORIA_ODS16 = AuditoriaOds16.AUDITORIA_ODS16;

    /**
     * Indicadores medidos por cada proyecto
     */
    public final Indicadores INDICADORES = Indicadores.INDICADORES;

    /**
     * Historial de mediciones de indicadores
     */
    public final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * Metas específicas establecidas por cada proyecto
     */
    public final MetasProyecto METAS_PROYECTO = MetasProyecto.METAS_PROYECTO;

    /**
     * Proyectos ODS16 creados por usuarios
     */
    public final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * VIEW
     */
    public final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * VIEW
     */
    public final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * VIEW
     */
    public final VistaAdminEstadisticasGenerales VISTA_ADMIN_ESTADISTICAS_GENERALES = VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES;

    /**
     * VIEW
     */
    public final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;

    /**
     * No further instances allowed
     */
    private Ods16() {
        super("ods16", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuditoriaOds16.AUDITORIA_ODS16,
            Indicadores.INDICADORES,
            MedicionesHistoricas.MEDICIONES_HISTORICAS,
            MetasProyecto.METAS_PROYECTO,
            Proyectos.PROYECTOS,
            VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE,
            VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES,
            VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES,
            VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL
        );
    }
}
