/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods16.tables;


import com.odsProject.odsProject.database.jooq.ods16.Indexes;
import com.odsProject.odsProject.database.jooq.ods16.Keys;
import com.odsProject.odsProject.database.jooq.ods16.Ods16;
import com.odsProject.odsProject.database.jooq.ods16.tables.records.AuditoriaOds16Record;
import com.odsProject.odsProject.database.jooq.ods_login.tables.Usuarios.UsuariosPath;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Auditoría de cambios en el sistema ODS16
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditoriaOds16 extends TableImpl<AuditoriaOds16Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ods16.auditoria_ods16</code>
     */
    public static final AuditoriaOds16 AUDITORIA_ODS16 = new AuditoriaOds16();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditoriaOds16Record> getRecordType() {
        return AuditoriaOds16Record.class;
    }

    /**
     * The column <code>ods16.auditoria_ods16.id</code>.
     */
    public final TableField<AuditoriaOds16Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ods16.auditoria_ods16.tabla_afectada</code>.
     */
    public final TableField<AuditoriaOds16Record, String> TABLA_AFECTADA = createField(DSL.name("tabla_afectada"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>ods16.auditoria_ods16.registro_id</code>.
     */
    public final TableField<AuditoriaOds16Record, Integer> REGISTRO_ID = createField(DSL.name("registro_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ods16.auditoria_ods16.accion</code>.
     */
    public final TableField<AuditoriaOds16Record, String> ACCION = createField(DSL.name("accion"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>ods16.auditoria_ods16.usuario_id</code>.
     */
    public final TableField<AuditoriaOds16Record, Integer> USUARIO_ID = createField(DSL.name("usuario_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ods16.auditoria_ods16.valores_anteriores</code>.
     */
    public final TableField<AuditoriaOds16Record, String> VALORES_ANTERIORES = createField(DSL.name("valores_anteriores"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods16.auditoria_ods16.valores_nuevos</code>.
     */
    public final TableField<AuditoriaOds16Record, String> VALORES_NUEVOS = createField(DSL.name("valores_nuevos"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ods16.auditoria_ods16.fecha_cambio</code>.
     */
    public final TableField<AuditoriaOds16Record, LocalDateTime> FECHA_CAMBIO = createField(DSL.name("fecha_cambio"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>ods16.auditoria_ods16.ip_address</code>.
     */
    public final TableField<AuditoriaOds16Record, String> IP_ADDRESS = createField(DSL.name("ip_address"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private AuditoriaOds16(Name alias, Table<AuditoriaOds16Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuditoriaOds16(Name alias, Table<AuditoriaOds16Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Auditoría de cambios en el sistema ODS16"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ods16.auditoria_ods16</code> table reference
     */
    public AuditoriaOds16(String alias) {
        this(DSL.name(alias), AUDITORIA_ODS16);
    }

    /**
     * Create an aliased <code>ods16.auditoria_ods16</code> table reference
     */
    public AuditoriaOds16(Name alias) {
        this(alias, AUDITORIA_ODS16);
    }

    /**
     * Create a <code>ods16.auditoria_ods16</code> table reference
     */
    public AuditoriaOds16() {
        this(DSL.name("auditoria_ods16"), null);
    }

    public <O extends Record> AuditoriaOds16(Table<O> path, ForeignKey<O, AuditoriaOds16Record> childPath, InverseForeignKey<O, AuditoriaOds16Record> parentPath) {
        super(path, childPath, parentPath, AUDITORIA_ODS16);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuditoriaOds16Path extends AuditoriaOds16 implements Path<AuditoriaOds16Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuditoriaOds16Path(Table<O> path, ForeignKey<O, AuditoriaOds16Record> childPath, InverseForeignKey<O, AuditoriaOds16Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuditoriaOds16Path(Name alias, Table<AuditoriaOds16Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuditoriaOds16Path as(String alias) {
            return new AuditoriaOds16Path(DSL.name(alias), this);
        }

        @Override
        public AuditoriaOds16Path as(Name alias) {
            return new AuditoriaOds16Path(alias, this);
        }

        @Override
        public AuditoriaOds16Path as(Table<?> alias) {
            return new AuditoriaOds16Path(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ods16.ODS16;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUDITORIA_ODS16_IDX_AUDITORIA_FECHA_TABLA, Indexes.AUDITORIA_ODS16_IDX_FECHA, Indexes.AUDITORIA_ODS16_IDX_TABLA_REGISTRO, Indexes.AUDITORIA_ODS16_USUARIO_ID);
    }

    @Override
    public Identity<AuditoriaOds16Record, Integer> getIdentity() {
        return (Identity<AuditoriaOds16Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuditoriaOds16Record> getPrimaryKey() {
        return Keys.KEY_AUDITORIA_ODS16_PRIMARY;
    }

    @Override
    public List<ForeignKey<AuditoriaOds16Record, ?>> getReferences() {
        return Arrays.asList(Keys.AUDITORIA_ODS16_IBFK_1);
    }

    private transient UsuariosPath _usuarios;

    /**
     * Get the implicit join path to the <code>ods_login.usuarios</code> table.
     */
    public UsuariosPath usuarios() {
        if (_usuarios == null)
            _usuarios = new UsuariosPath(this, Keys.AUDITORIA_ODS16_IBFK_1, null);

        return _usuarios;
    }

    @Override
    public List<Check<AuditoriaOds16Record>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("valores_anteriores"), "json_valid(`valores_anteriores`)", true),
            Internal.createCheck(this, DSL.name("valores_nuevos"), "json_valid(`valores_nuevos`)", true)
        );
    }

    @Override
    public AuditoriaOds16 as(String alias) {
        return new AuditoriaOds16(DSL.name(alias), this);
    }

    @Override
    public AuditoriaOds16 as(Name alias) {
        return new AuditoriaOds16(alias, this);
    }

    @Override
    public AuditoriaOds16 as(Table<?> alias) {
        return new AuditoriaOds16(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds16 rename(String name) {
        return new AuditoriaOds16(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds16 rename(Name name) {
        return new AuditoriaOds16(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditoriaOds16 rename(Table<?> name) {
        return new AuditoriaOds16(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds16 where(Condition condition) {
        return new AuditoriaOds16(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds16 where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds16 where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds16 where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds16 where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds16 where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds16 where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditoriaOds16 where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds16 whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditoriaOds16 whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
