/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods11.tables.daos;


import com.projectods.database.jooq.ods11.enums.ProyectosEstado;
import com.projectods.database.jooq.ods11.tables.Proyectos;
import com.projectods.database.jooq.ods11.tables.records.ProyectosRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * Proyectos ODS11 creados por usuarios
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ProyectosDao extends DAOImpl<ProyectosRecord, com.projectods.database.jooq.ods11.tables.pojos.Proyectos, Integer> {

    /**
     * Create a new ProyectosDao without any configuration
     */
    public ProyectosDao() {
        super(Proyectos.PROYECTOS, com.projectods.database.jooq.ods11.tables.pojos.Proyectos.class);
    }

    /**
     * Create a new ProyectosDao with an attached configuration
     */
    @Autowired
    public ProyectosDao(Configuration configuration) {
        super(Proyectos.PROYECTOS, com.projectods.database.jooq.ods11.tables.pojos.Proyectos.class, configuration);
    }

    @Override
    public Integer getId(com.projectods.database.jooq.ods11.tables.pojos.Proyectos object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchById(Integer... values) {
        return fetch(Proyectos.PROYECTOS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.projectods.database.jooq.ods11.tables.pojos.Proyectos fetchOneById(Integer value) {
        return fetchOne(Proyectos.PROYECTOS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchOptionalById(Integer value) {
        return fetchOptional(Proyectos.PROYECTOS.ID, value);
    }

    /**
     * Fetch records that have <code>usuario_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfUsuarioId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.USUARIO_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>usuario_id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchByUsuarioId(Integer... values) {
        return fetch(Proyectos.PROYECTOS.USUARIO_ID, values);
    }

    /**
     * Fetch records that have <code>nombre_proyecto BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfNombreProyecto(String lowerInclusive, String upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.NOMBRE_PROYECTO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>nombre_proyecto IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchByNombreProyecto(String... values) {
        return fetch(Proyectos.PROYECTOS.NOMBRE_PROYECTO, values);
    }

    /**
     * Fetch records that have <code>objetivo_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfObjetivoId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.OBJETIVO_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>objetivo_id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchByObjetivoId(Integer... values) {
        return fetch(Proyectos.PROYECTOS.OBJETIVO_ID, values);
    }

    /**
     * Fetch records that have <code>descripcion BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfDescripcion(String lowerInclusive, String upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.DESCRIPCION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>descripcion IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchByDescripcion(String... values) {
        return fetch(Proyectos.PROYECTOS.DESCRIPCION, values);
    }

    /**
     * Fetch records that have <code>fecha_inicio BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfFechaInicio(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.FECHA_INICIO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fecha_inicio IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchByFechaInicio(LocalDate... values) {
        return fetch(Proyectos.PROYECTOS.FECHA_INICIO, values);
    }

    /**
     * Fetch records that have <code>fecha_fin BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfFechaFin(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.FECHA_FIN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fecha_fin IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchByFechaFin(LocalDate... values) {
        return fetch(Proyectos.PROYECTOS.FECHA_FIN, values);
    }

    /**
     * Fetch records that have <code>meta_general BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfMetaGeneral(String lowerInclusive, String upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.META_GENERAL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>meta_general IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchByMetaGeneral(String... values) {
        return fetch(Proyectos.PROYECTOS.META_GENERAL, values);
    }

    /**
     * Fetch records that have <code>estado BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfEstado(ProyectosEstado lowerInclusive, ProyectosEstado upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.ESTADO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>estado IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchByEstado(ProyectosEstado... values) {
        return fetch(Proyectos.PROYECTOS.ESTADO, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(Proyectos.PROYECTOS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Proyectos.PROYECTOS.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods11.tables.pojos.Proyectos> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(Proyectos.PROYECTOS.UPDATED_AT, values);
    }
}
