/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods03;


import com.odsProject.odsProject.database.jooq.ods03.tables.AuditoriaOds03;
import com.odsProject.odsProject.database.jooq.ods03.tables.Indicadores;
import com.odsProject.odsProject.database.jooq.ods03.tables.MedicionesHistoricas;
import com.odsProject.odsProject.database.jooq.ods03.tables.MetasProyecto;
import com.odsProject.odsProject.database.jooq.ods03.tables.Proyectos;
import com.odsProject.odsProject.database.jooq.ods03.tables.VistaAdminAuditoriaReciente;
import com.odsProject.odsProject.database.jooq.ods03.tables.VistaAdminDetalleIndicadores;
import com.odsProject.odsProject.database.jooq.ods03.tables.VistaAdminEstadisticasGenerales;
import com.odsProject.odsProject.database.jooq.ods03.tables.VistaAdminResumenGeneral;


/**
 * Convenience access to all tables in ods03.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Auditoría de cambios en el sistema ODS03
     */
    public static final AuditoriaOds03 AUDITORIA_ODS03 = AuditoriaOds03.AUDITORIA_ODS03;

    /**
     * Indicadores medidos por cada proyecto ODS03
     */
    public static final Indicadores INDICADORES = Indicadores.INDICADORES;

    /**
     * Historial de mediciones de indicadores ODS03
     */
    public static final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * Metas específicas establecidas por cada proyecto ODS03
     */
    public static final MetasProyecto METAS_PROYECTO = MetasProyecto.METAS_PROYECTO;

    /**
     * Proyectos ODS03 creados por usuarios
     */
    public static final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * The table <code>ods03.vista_admin_auditoria_reciente</code>.
     */
    public static final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * The table <code>ods03.vista_admin_detalle_indicadores</code>.
     */
    public static final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * The table <code>ods03.vista_admin_estadisticas_generales</code>.
     */
    public static final VistaAdminEstadisticasGenerales VISTA_ADMIN_ESTADISTICAS_GENERALES = VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES;

    /**
     * The table <code>ods03.vista_admin_resumen_general</code>.
     */
    public static final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;
}
