/*
 * This file is generated by jOOQ.
 */
package com.odsProject.odsProject.database.jooq.ods11;


import com.odsProject.odsProject.database.jooq.ods11.tables.AuditoriaOds11;
import com.odsProject.odsProject.database.jooq.ods11.tables.MedicionParametroValores;
import com.odsProject.odsProject.database.jooq.ods11.tables.MedicionesHistoricas;
import com.odsProject.odsProject.database.jooq.ods11.tables.ProyectoIndicadorParametros;
import com.odsProject.odsProject.database.jooq.ods11.tables.ProyectoIndicadores;
import com.odsProject.odsProject.database.jooq.ods11.tables.VistaAdminAuditoriaReciente;
import com.odsProject.odsProject.database.jooq.ods11.tables.VistaAdminDetalleIndicadores;
import com.odsProject.odsProject.database.jooq.ods11.tables.VistaAdminResumenGeneral;


/**
 * Convenience access to all tables in ods11.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>ods11.auditoria_ods11</code>.
     */
    public static final AuditoriaOds11 AUDITORIA_ODS11 = AuditoriaOds11.AUDITORIA_ODS11;

    /**
     * The table <code>ods11.medicion_parametro_valores</code>.
     */
    public static final MedicionParametroValores MEDICION_PARAMETRO_VALORES = MedicionParametroValores.MEDICION_PARAMETRO_VALORES;

    /**
     * The table <code>ods11.mediciones_historicas</code>.
     */
    public static final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * The table <code>ods11.proyecto_indicador_parametros</code>.
     */
    public static final ProyectoIndicadorParametros PROYECTO_INDICADOR_PARAMETROS = ProyectoIndicadorParametros.PROYECTO_INDICADOR_PARAMETROS;

    /**
     * The table <code>ods11.proyecto_indicadores</code>.
     */
    public static final ProyectoIndicadores PROYECTO_INDICADORES = ProyectoIndicadores.PROYECTO_INDICADORES;

    /**
     * The table <code>ods11.vista_admin_auditoria_reciente</code>.
     */
    public static final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * The table <code>ods11.vista_admin_detalle_indicadores</code>.
     */
    public static final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * The table <code>ods11.vista_admin_resumen_general</code>.
     */
    public static final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;
}
