/*
 * This file is generated by jOOQ.
 */
package odsProject.database.jooq.ods11;


import odsProject.database.jooq.ods11.tables.AuditoriaOds11;
import odsProject.database.jooq.ods11.tables.Indicadores;
import odsProject.database.jooq.ods11.tables.MedicionesHistoricas;
import odsProject.database.jooq.ods11.tables.MetasProyecto;
import odsProject.database.jooq.ods11.tables.Proyectos;
import odsProject.database.jooq.ods11.tables.VistaAdminAuditoriaReciente;
import odsProject.database.jooq.ods11.tables.VistaAdminDetalleIndicadores;
import odsProject.database.jooq.ods11.tables.VistaAdminEstadisticasGenerales;
import odsProject.database.jooq.ods11.tables.VistaAdminResumenGeneral;


/**
 * Convenience access to all tables in ods11.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Auditoría de cambios en el sistema ODS11
     */
    public static final AuditoriaOds11 AUDITORIA_ODS11 = AuditoriaOds11.AUDITORIA_ODS11;

    /**
     * Indicadores medidos por cada proyecto ODS11
     */
    public static final Indicadores INDICADORES = Indicadores.INDICADORES;

    /**
     * Historial de mediciones de indicadores ODS11
     */
    public static final MedicionesHistoricas MEDICIONES_HISTORICAS = MedicionesHistoricas.MEDICIONES_HISTORICAS;

    /**
     * Metas específicas establecidas por cada proyecto ODS11
     */
    public static final MetasProyecto METAS_PROYECTO = MetasProyecto.METAS_PROYECTO;

    /**
     * Proyectos ODS11 creados por usuarios
     */
    public static final Proyectos PROYECTOS = Proyectos.PROYECTOS;

    /**
     * The table <code>ods11.vista_admin_auditoria_reciente</code>.
     */
    public static final VistaAdminAuditoriaReciente VISTA_ADMIN_AUDITORIA_RECIENTE = VistaAdminAuditoriaReciente.VISTA_ADMIN_AUDITORIA_RECIENTE;

    /**
     * The table <code>ods11.vista_admin_detalle_indicadores</code>.
     */
    public static final VistaAdminDetalleIndicadores VISTA_ADMIN_DETALLE_INDICADORES = VistaAdminDetalleIndicadores.VISTA_ADMIN_DETALLE_INDICADORES;

    /**
     * The table <code>ods11.vista_admin_estadisticas_generales</code>.
     */
    public static final VistaAdminEstadisticasGenerales VISTA_ADMIN_ESTADISTICAS_GENERALES = VistaAdminEstadisticasGenerales.VISTA_ADMIN_ESTADISTICAS_GENERALES;

    /**
     * The table <code>ods11.vista_admin_resumen_general</code>.
     */
    public static final VistaAdminResumenGeneral VISTA_ADMIN_RESUMEN_GENERAL = VistaAdminResumenGeneral.VISTA_ADMIN_RESUMEN_GENERAL;
}
