/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods05;


import com.projectods.database.jooq.ods05.routines.SpAdminDashboard;
import com.projectods.database.jooq.ods05.routines.SpAdminReporteProyecto;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in ods05.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>ods05.sp_admin_dashboard</code>
     */
    public static void spAdminDashboard(
          Configuration configuration
    ) {
        SpAdminDashboard p = new SpAdminDashboard();

        p.execute(configuration);
    }

    /**
     * Call <code>ods05.sp_admin_reporte_proyecto</code>
     */
    public static void spAdminReporteProyecto(
          Configuration configuration
        , Integer proyectoIdParam
    ) {
        SpAdminReporteProyecto p = new SpAdminReporteProyecto();
        p.setProyectoIdParam(proyectoIdParam);

        p.execute(configuration);
    }
}
