/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods_login.tables.daos;


import com.projectods.database.jooq.ods_login.tables.Sesiones;
import com.projectods.database.jooq.ods_login.tables.records.SesionesRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * Sesiones activas de usuarios
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class SesionesDao extends DAOImpl<SesionesRecord, com.projectods.database.jooq.ods_login.tables.pojos.Sesiones, Integer> {

    /**
     * Create a new SesionesDao without any configuration
     */
    public SesionesDao() {
        super(Sesiones.SESIONES, com.projectods.database.jooq.ods_login.tables.pojos.Sesiones.class);
    }

    /**
     * Create a new SesionesDao with an attached configuration
     */
    @Autowired
    public SesionesDao(Configuration configuration) {
        super(Sesiones.SESIONES, com.projectods.database.jooq.ods_login.tables.pojos.Sesiones.class, configuration);
    }

    @Override
    public Integer getId(com.projectods.database.jooq.ods_login.tables.pojos.Sesiones object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Sesiones.SESIONES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchById(Integer... values) {
        return fetch(Sesiones.SESIONES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.projectods.database.jooq.ods_login.tables.pojos.Sesiones fetchOneById(Integer value) {
        return fetchOne(Sesiones.SESIONES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchOptionalById(Integer value) {
        return fetchOptional(Sesiones.SESIONES.ID, value);
    }

    /**
     * Fetch records that have <code>usuario_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchRangeOfUsuarioId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Sesiones.SESIONES.USUARIO_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>usuario_id IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchByUsuarioId(Integer... values) {
        return fetch(Sesiones.SESIONES.USUARIO_ID, values);
    }

    /**
     * Fetch records that have <code>session_token BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchRangeOfSessionToken(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sesiones.SESIONES.SESSION_TOKEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>session_token IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchBySessionToken(String... values) {
        return fetch(Sesiones.SESIONES.SESSION_TOKEN, values);
    }

    /**
     * Fetch a unique record that has <code>session_token = value</code>
     */
    public com.projectods.database.jooq.ods_login.tables.pojos.Sesiones fetchOneBySessionToken(String value) {
        return fetchOne(Sesiones.SESIONES.SESSION_TOKEN, value);
    }

    /**
     * Fetch a unique record that has <code>session_token = value</code>
     */
    public Optional<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchOptionalBySessionToken(String value) {
        return fetchOptional(Sesiones.SESIONES.SESSION_TOKEN, value);
    }

    /**
     * Fetch records that have <code>refresh_token BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchRangeOfRefreshToken(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sesiones.SESIONES.REFRESH_TOKEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>refresh_token IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchByRefreshToken(String... values) {
        return fetch(Sesiones.SESIONES.REFRESH_TOKEN, values);
    }

    /**
     * Fetch a unique record that has <code>refresh_token = value</code>
     */
    public com.projectods.database.jooq.ods_login.tables.pojos.Sesiones fetchOneByRefreshToken(String value) {
        return fetchOne(Sesiones.SESIONES.REFRESH_TOKEN, value);
    }

    /**
     * Fetch a unique record that has <code>refresh_token = value</code>
     */
    public Optional<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchOptionalByRefreshToken(String value) {
        return fetchOptional(Sesiones.SESIONES.REFRESH_TOKEN, value);
    }

    /**
     * Fetch records that have <code>ip_address BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchRangeOfIpAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sesiones.SESIONES.IP_ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ip_address IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchByIpAddress(String... values) {
        return fetch(Sesiones.SESIONES.IP_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>user_agent BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchRangeOfUserAgent(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sesiones.SESIONES.USER_AGENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_agent IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchByUserAgent(String... values) {
        return fetch(Sesiones.SESIONES.USER_AGENT, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Sesiones.SESIONES.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(Sesiones.SESIONES.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>expires_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchRangeOfExpiresAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Sesiones.SESIONES.EXPIRES_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>expires_at IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchByExpiresAt(LocalDateTime... values) {
        return fetch(Sesiones.SESIONES.EXPIRES_AT, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchRangeOfIsActive(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Sesiones.SESIONES.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.projectods.database.jooq.ods_login.tables.pojos.Sesiones> fetchByIsActive(Byte... values) {
        return fetch(Sesiones.SESIONES.IS_ACTIVE, values);
    }
}
