/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods11.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * Indicadores medidos por cada proyecto ODS11
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indicadores implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer proyectoId;
    private String indicadorCodigo;
    private String indicadorDescripcion;
    private BigDecimal valorActual;
    private BigDecimal valorMeta;
    private String unidadMedida;
    private LocalDate fechaMedicion;
    private String fuenteDatos;
    private String observaciones;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Indicadores() {}

    public Indicadores(Indicadores value) {
        this.id = value.id;
        this.proyectoId = value.proyectoId;
        this.indicadorCodigo = value.indicadorCodigo;
        this.indicadorDescripcion = value.indicadorDescripcion;
        this.valorActual = value.valorActual;
        this.valorMeta = value.valorMeta;
        this.unidadMedida = value.unidadMedida;
        this.fechaMedicion = value.fechaMedicion;
        this.fuenteDatos = value.fuenteDatos;
        this.observaciones = value.observaciones;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Indicadores(
        Integer id,
        Integer proyectoId,
        String indicadorCodigo,
        String indicadorDescripcion,
        BigDecimal valorActual,
        BigDecimal valorMeta,
        String unidadMedida,
        LocalDate fechaMedicion,
        String fuenteDatos,
        String observaciones,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.proyectoId = proyectoId;
        this.indicadorCodigo = indicadorCodigo;
        this.indicadorDescripcion = indicadorDescripcion;
        this.valorActual = valorActual;
        this.valorMeta = valorMeta;
        this.unidadMedida = unidadMedida;
        this.fechaMedicion = fechaMedicion;
        this.fuenteDatos = fuenteDatos;
        this.observaciones = observaciones;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>ods11.indicadores.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ods11.indicadores.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>ods11.indicadores.proyecto_id</code>.
     */
    @NotNull
    public Integer getProyectoId() {
        return this.proyectoId;
    }

    /**
     * Setter for <code>ods11.indicadores.proyecto_id</code>.
     */
    public void setProyectoId(Integer proyectoId) {
        this.proyectoId = proyectoId;
    }

    /**
     * Getter for <code>ods11.indicadores.indicador_codigo</code>.
     */
    @NotNull
    @Size(max = 10)
    public String getIndicadorCodigo() {
        return this.indicadorCodigo;
    }

    /**
     * Setter for <code>ods11.indicadores.indicador_codigo</code>.
     */
    public void setIndicadorCodigo(String indicadorCodigo) {
        this.indicadorCodigo = indicadorCodigo;
    }

    /**
     * Getter for <code>ods11.indicadores.indicador_descripcion</code>.
     */
    @NotNull
    @Size(max = 65535)
    public String getIndicadorDescripcion() {
        return this.indicadorDescripcion;
    }

    /**
     * Setter for <code>ods11.indicadores.indicador_descripcion</code>.
     */
    public void setIndicadorDescripcion(String indicadorDescripcion) {
        this.indicadorDescripcion = indicadorDescripcion;
    }

    /**
     * Getter for <code>ods11.indicadores.valor_actual</code>.
     */
    public BigDecimal getValorActual() {
        return this.valorActual;
    }

    /**
     * Setter for <code>ods11.indicadores.valor_actual</code>.
     */
    public void setValorActual(BigDecimal valorActual) {
        this.valorActual = valorActual;
    }

    /**
     * Getter for <code>ods11.indicadores.valor_meta</code>.
     */
    @NotNull
    public BigDecimal getValorMeta() {
        return this.valorMeta;
    }

    /**
     * Setter for <code>ods11.indicadores.valor_meta</code>.
     */
    public void setValorMeta(BigDecimal valorMeta) {
        this.valorMeta = valorMeta;
    }

    /**
     * Getter for <code>ods11.indicadores.unidad_medida</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getUnidadMedida() {
        return this.unidadMedida;
    }

    /**
     * Setter for <code>ods11.indicadores.unidad_medida</code>.
     */
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

    /**
     * Getter for <code>ods11.indicadores.fecha_medicion</code>.
     */
    @NotNull
    public LocalDate getFechaMedicion() {
        return this.fechaMedicion;
    }

    /**
     * Setter for <code>ods11.indicadores.fecha_medicion</code>.
     */
    public void setFechaMedicion(LocalDate fechaMedicion) {
        this.fechaMedicion = fechaMedicion;
    }

    /**
     * Getter for <code>ods11.indicadores.fuente_datos</code>.
     */
    @Size(max = 100)
    public String getFuenteDatos() {
        return this.fuenteDatos;
    }

    /**
     * Setter for <code>ods11.indicadores.fuente_datos</code>.
     */
    public void setFuenteDatos(String fuenteDatos) {
        this.fuenteDatos = fuenteDatos;
    }

    /**
     * Getter for <code>ods11.indicadores.observaciones</code>.
     */
    @Size(max = 65535)
    public String getObservaciones() {
        return this.observaciones;
    }

    /**
     * Setter for <code>ods11.indicadores.observaciones</code>.
     */
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    /**
     * Getter for <code>ods11.indicadores.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>ods11.indicadores.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>ods11.indicadores.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>ods11.indicadores.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Indicadores other = (Indicadores) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.proyectoId == null) {
            if (other.proyectoId != null)
                return false;
        }
        else if (!this.proyectoId.equals(other.proyectoId))
            return false;
        if (this.indicadorCodigo == null) {
            if (other.indicadorCodigo != null)
                return false;
        }
        else if (!this.indicadorCodigo.equals(other.indicadorCodigo))
            return false;
        if (this.indicadorDescripcion == null) {
            if (other.indicadorDescripcion != null)
                return false;
        }
        else if (!this.indicadorDescripcion.equals(other.indicadorDescripcion))
            return false;
        if (this.valorActual == null) {
            if (other.valorActual != null)
                return false;
        }
        else if (!this.valorActual.equals(other.valorActual))
            return false;
        if (this.valorMeta == null) {
            if (other.valorMeta != null)
                return false;
        }
        else if (!this.valorMeta.equals(other.valorMeta))
            return false;
        if (this.unidadMedida == null) {
            if (other.unidadMedida != null)
                return false;
        }
        else if (!this.unidadMedida.equals(other.unidadMedida))
            return false;
        if (this.fechaMedicion == null) {
            if (other.fechaMedicion != null)
                return false;
        }
        else if (!this.fechaMedicion.equals(other.fechaMedicion))
            return false;
        if (this.fuenteDatos == null) {
            if (other.fuenteDatos != null)
                return false;
        }
        else if (!this.fuenteDatos.equals(other.fuenteDatos))
            return false;
        if (this.observaciones == null) {
            if (other.observaciones != null)
                return false;
        }
        else if (!this.observaciones.equals(other.observaciones))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.proyectoId == null) ? 0 : this.proyectoId.hashCode());
        result = prime * result + ((this.indicadorCodigo == null) ? 0 : this.indicadorCodigo.hashCode());
        result = prime * result + ((this.indicadorDescripcion == null) ? 0 : this.indicadorDescripcion.hashCode());
        result = prime * result + ((this.valorActual == null) ? 0 : this.valorActual.hashCode());
        result = prime * result + ((this.valorMeta == null) ? 0 : this.valorMeta.hashCode());
        result = prime * result + ((this.unidadMedida == null) ? 0 : this.unidadMedida.hashCode());
        result = prime * result + ((this.fechaMedicion == null) ? 0 : this.fechaMedicion.hashCode());
        result = prime * result + ((this.fuenteDatos == null) ? 0 : this.fuenteDatos.hashCode());
        result = prime * result + ((this.observaciones == null) ? 0 : this.observaciones.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Indicadores (");

        sb.append(id);
        sb.append(", ").append(proyectoId);
        sb.append(", ").append(indicadorCodigo);
        sb.append(", ").append(indicadorDescripcion);
        sb.append(", ").append(valorActual);
        sb.append(", ").append(valorMeta);
        sb.append(", ").append(unidadMedida);
        sb.append(", ").append(fechaMedicion);
        sb.append(", ").append(fuenteDatos);
        sb.append(", ").append(observaciones);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
