/*
 * This file is generated by jOOQ.
 */
package com.projectods.database.jooq.ods11.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAdminDetalleIndicadores implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer proyectoId;
    private String nombreProyecto;
    private String usuarioCreador;
    private String indicadorCodigo;
    private String indicadorDescripcion;
    private BigDecimal valorActual;
    private BigDecimal valorMeta;
    private String unidadMedida;
    private String estadoIndicador;
    private BigDecimal porcentajeLogro;
    private LocalDate fechaMedicion;
    private String fuenteDatos;
    private LocalDateTime ultimaActualizacion;

    public VistaAdminDetalleIndicadores() {}

    public VistaAdminDetalleIndicadores(VistaAdminDetalleIndicadores value) {
        this.proyectoId = value.proyectoId;
        this.nombreProyecto = value.nombreProyecto;
        this.usuarioCreador = value.usuarioCreador;
        this.indicadorCodigo = value.indicadorCodigo;
        this.indicadorDescripcion = value.indicadorDescripcion;
        this.valorActual = value.valorActual;
        this.valorMeta = value.valorMeta;
        this.unidadMedida = value.unidadMedida;
        this.estadoIndicador = value.estadoIndicador;
        this.porcentajeLogro = value.porcentajeLogro;
        this.fechaMedicion = value.fechaMedicion;
        this.fuenteDatos = value.fuenteDatos;
        this.ultimaActualizacion = value.ultimaActualizacion;
    }

    public VistaAdminDetalleIndicadores(
        Integer proyectoId,
        String nombreProyecto,
        String usuarioCreador,
        String indicadorCodigo,
        String indicadorDescripcion,
        BigDecimal valorActual,
        BigDecimal valorMeta,
        String unidadMedida,
        String estadoIndicador,
        BigDecimal porcentajeLogro,
        LocalDate fechaMedicion,
        String fuenteDatos,
        LocalDateTime ultimaActualizacion
    ) {
        this.proyectoId = proyectoId;
        this.nombreProyecto = nombreProyecto;
        this.usuarioCreador = usuarioCreador;
        this.indicadorCodigo = indicadorCodigo;
        this.indicadorDescripcion = indicadorDescripcion;
        this.valorActual = valorActual;
        this.valorMeta = valorMeta;
        this.unidadMedida = unidadMedida;
        this.estadoIndicador = estadoIndicador;
        this.porcentajeLogro = porcentajeLogro;
        this.fechaMedicion = fechaMedicion;
        this.fuenteDatos = fuenteDatos;
        this.ultimaActualizacion = ultimaActualizacion;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.proyecto_id</code>.
     */
    public Integer getProyectoId() {
        return this.proyectoId;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.proyecto_id</code>.
     */
    public void setProyectoId(Integer proyectoId) {
        this.proyectoId = proyectoId;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.nombre_proyecto</code>.
     */
    @NotNull
    @Size(max = 200)
    public String getNombreProyecto() {
        return this.nombreProyecto;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.nombre_proyecto</code>.
     */
    public void setNombreProyecto(String nombreProyecto) {
        this.nombreProyecto = nombreProyecto;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.usuario_creador</code>.
     */
    @Size(max = 50)
    public String getUsuarioCreador() {
        return this.usuarioCreador;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.usuario_creador</code>.
     */
    public void setUsuarioCreador(String usuarioCreador) {
        this.usuarioCreador = usuarioCreador;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.indicador_codigo</code>.
     */
    @Size(max = 10)
    public String getIndicadorCodigo() {
        return this.indicadorCodigo;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.indicador_codigo</code>.
     */
    public void setIndicadorCodigo(String indicadorCodigo) {
        this.indicadorCodigo = indicadorCodigo;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.indicador_descripcion</code>.
     */
    @Size(max = 65535)
    public String getIndicadorDescripcion() {
        return this.indicadorDescripcion;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.indicador_descripcion</code>.
     */
    public void setIndicadorDescripcion(String indicadorDescripcion) {
        this.indicadorDescripcion = indicadorDescripcion;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.valor_actual</code>.
     */
    public BigDecimal getValorActual() {
        return this.valorActual;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.valor_actual</code>.
     */
    public void setValorActual(BigDecimal valorActual) {
        this.valorActual = valorActual;
    }

    /**
     * Getter for <code>ods11.vista_admin_detalle_indicadores.valor_meta</code>.
     */
    public BigDecimal getValorMeta() {
        return this.valorMeta;
    }

    /**
     * Setter for <code>ods11.vista_admin_detalle_indicadores.valor_meta</code>.
     */
    public void setValorMeta(BigDecimal valorMeta) {
        this.valorMeta = valorMeta;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.unidad_medida</code>.
     */
    @Size(max = 50)
    public String getUnidadMedida() {
        return this.unidadMedida;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.unidad_medida</code>.
     */
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.estado_indicador</code>.
     */
    @Size(max = 10)
    public String getEstadoIndicador() {
        return this.estadoIndicador;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.estado_indicador</code>.
     */
    public void setEstadoIndicador(String estadoIndicador) {
        this.estadoIndicador = estadoIndicador;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.porcentaje_logro</code>.
     */
    public BigDecimal getPorcentajeLogro() {
        return this.porcentajeLogro;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.porcentaje_logro</code>.
     */
    public void setPorcentajeLogro(BigDecimal porcentajeLogro) {
        this.porcentajeLogro = porcentajeLogro;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.fecha_medicion</code>.
     */
    public LocalDate getFechaMedicion() {
        return this.fechaMedicion;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.fecha_medicion</code>.
     */
    public void setFechaMedicion(LocalDate fechaMedicion) {
        this.fechaMedicion = fechaMedicion;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.fuente_datos</code>.
     */
    @Size(max = 100)
    public String getFuenteDatos() {
        return this.fuenteDatos;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.fuente_datos</code>.
     */
    public void setFuenteDatos(String fuenteDatos) {
        this.fuenteDatos = fuenteDatos;
    }

    /**
     * Getter for
     * <code>ods11.vista_admin_detalle_indicadores.ultima_actualizacion</code>.
     */
    public LocalDateTime getUltimaActualizacion() {
        return this.ultimaActualizacion;
    }

    /**
     * Setter for
     * <code>ods11.vista_admin_detalle_indicadores.ultima_actualizacion</code>.
     */
    public void setUltimaActualizacion(LocalDateTime ultimaActualizacion) {
        this.ultimaActualizacion = ultimaActualizacion;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VistaAdminDetalleIndicadores other = (VistaAdminDetalleIndicadores) obj;
        if (this.proyectoId == null) {
            if (other.proyectoId != null)
                return false;
        }
        else if (!this.proyectoId.equals(other.proyectoId))
            return false;
        if (this.nombreProyecto == null) {
            if (other.nombreProyecto != null)
                return false;
        }
        else if (!this.nombreProyecto.equals(other.nombreProyecto))
            return false;
        if (this.usuarioCreador == null) {
            if (other.usuarioCreador != null)
                return false;
        }
        else if (!this.usuarioCreador.equals(other.usuarioCreador))
            return false;
        if (this.indicadorCodigo == null) {
            if (other.indicadorCodigo != null)
                return false;
        }
        else if (!this.indicadorCodigo.equals(other.indicadorCodigo))
            return false;
        if (this.indicadorDescripcion == null) {
            if (other.indicadorDescripcion != null)
                return false;
        }
        else if (!this.indicadorDescripcion.equals(other.indicadorDescripcion))
            return false;
        if (this.valorActual == null) {
            if (other.valorActual != null)
                return false;
        }
        else if (!this.valorActual.equals(other.valorActual))
            return false;
        if (this.valorMeta == null) {
            if (other.valorMeta != null)
                return false;
        }
        else if (!this.valorMeta.equals(other.valorMeta))
            return false;
        if (this.unidadMedida == null) {
            if (other.unidadMedida != null)
                return false;
        }
        else if (!this.unidadMedida.equals(other.unidadMedida))
            return false;
        if (this.estadoIndicador == null) {
            if (other.estadoIndicador != null)
                return false;
        }
        else if (!this.estadoIndicador.equals(other.estadoIndicador))
            return false;
        if (this.porcentajeLogro == null) {
            if (other.porcentajeLogro != null)
                return false;
        }
        else if (!this.porcentajeLogro.equals(other.porcentajeLogro))
            return false;
        if (this.fechaMedicion == null) {
            if (other.fechaMedicion != null)
                return false;
        }
        else if (!this.fechaMedicion.equals(other.fechaMedicion))
            return false;
        if (this.fuenteDatos == null) {
            if (other.fuenteDatos != null)
                return false;
        }
        else if (!this.fuenteDatos.equals(other.fuenteDatos))
            return false;
        if (this.ultimaActualizacion == null) {
            if (other.ultimaActualizacion != null)
                return false;
        }
        else if (!this.ultimaActualizacion.equals(other.ultimaActualizacion))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.proyectoId == null) ? 0 : this.proyectoId.hashCode());
        result = prime * result + ((this.nombreProyecto == null) ? 0 : this.nombreProyecto.hashCode());
        result = prime * result + ((this.usuarioCreador == null) ? 0 : this.usuarioCreador.hashCode());
        result = prime * result + ((this.indicadorCodigo == null) ? 0 : this.indicadorCodigo.hashCode());
        result = prime * result + ((this.indicadorDescripcion == null) ? 0 : this.indicadorDescripcion.hashCode());
        result = prime * result + ((this.valorActual == null) ? 0 : this.valorActual.hashCode());
        result = prime * result + ((this.valorMeta == null) ? 0 : this.valorMeta.hashCode());
        result = prime * result + ((this.unidadMedida == null) ? 0 : this.unidadMedida.hashCode());
        result = prime * result + ((this.estadoIndicador == null) ? 0 : this.estadoIndicador.hashCode());
        result = prime * result + ((this.porcentajeLogro == null) ? 0 : this.porcentajeLogro.hashCode());
        result = prime * result + ((this.fechaMedicion == null) ? 0 : this.fechaMedicion.hashCode());
        result = prime * result + ((this.fuenteDatos == null) ? 0 : this.fuenteDatos.hashCode());
        result = prime * result + ((this.ultimaActualizacion == null) ? 0 : this.ultimaActualizacion.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VistaAdminDetalleIndicadores (");

        sb.append(proyectoId);
        sb.append(", ").append(nombreProyecto);
        sb.append(", ").append(usuarioCreador);
        sb.append(", ").append(indicadorCodigo);
        sb.append(", ").append(indicadorDescripcion);
        sb.append(", ").append(valorActual);
        sb.append(", ").append(valorMeta);
        sb.append(", ").append(unidadMedida);
        sb.append(", ").append(estadoIndicador);
        sb.append(", ").append(porcentajeLogro);
        sb.append(", ").append(fechaMedicion);
        sb.append(", ").append(fuenteDatos);
        sb.append(", ").append(ultimaActualizacion);

        sb.append(")");
        return sb.toString();
    }
}
